Repository dolthub/dolt, pull requests merged in 2022-09, with the labels that each got.

#4280 [auto-bump] [no-release-notes] dependency by Hydrocharged
  go/go.mod
  go/go.sum
Labels: gms-bump

#4294 [auto-bump] [no-release-notes] dependency by JCOR11599
  go/go.mod
  go/go.sum
Labels: gms-bump

#4305 [auto-bump] [no-release-notes] dependency by max-hoffman
  go/go.mod
  go/go.sum
Labels: gms-bump

#4308 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump

#4267 Add dolt diff --skinny flag
  go/cmd/dolt/commands/diff.go
  integration-tests/bats/diff.bats
Labels: contribution

#4312 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump

#4338 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/sqlddl_test.go
Labels: gms-bump

#4346 [auto-bump] [no-release-notes] dependency by reltuk
  go/go.mod
  go/go.sum
Labels: gms-bump

#4351 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump

#4356 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump

#4359 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump

#4362 [auto-bump] [no-release-notes] dependency by jennifersp
  go/go.mod
  go/go.sum
Labels: gms-bump

#4366 Fix bug in colDiffs
  go/cmd/dolt/commands/diffsplitter.go
  go/cmd/dolt/commands/diffsplitter_test.go
Labels: contribution

#4377 [auto-bump] [no-release-notes] dependency by JCOR11599
  go/go.mod
  go/go.sum
Labels: gms-bump

#4381 [auto-bump] [no-release-notes] dependency by Hydrocharged
  go/go.mod
  go/go.sum
Labels: gms-bump

#4388 [auto-bump] [no-release-notes] dependency by reltuk
  go/go.mod
  go/go.sum
Labels: gms-bump

#4398 [auto-bump] [no-release-notes] dependency by JCOR11599
  go/go.mod
  go/go.sum
Labels: gms-bump

#4268 Feat/support aliyun oss store
  go/cmd/dolt/cli/arg_parser_helpers.go
  go/cmd/dolt/commands/remote.go
  go/go.mod
  go/go.sum
  go/libraries/doltcore/dbfactory/factory.go
  go/libraries/doltcore/dbfactory/oss.go
  go/libraries/doltcore/dbfactory/oss_test.go
  go/libraries/doltcore/dbfactory/testdata/osscred/dolt_oss_credentials
  go/libraries/doltcore/dbfactory/testdata/osscred/empty_oss_cred
  go/libraries/doltcore/dbfactory/testdata/osscred/single_oss_cred
  go/libraries/doltcore/sqle/dprocedures/dolt_remote.go
  go/store/blobstore/oss.go
  go/store/blobstore/oss_test.go
Labels: contribution

#4418 [auto-bump] [no-release-notes] dependency by max-hoffman
  go/go.mod
  go/go.sum
Labels: gms-bump, keep-alive

#4425 [auto-bump] [no-release-notes] dependency by Hydrocharged
  go/go.mod
  go/go.sum
Labels: gms-bump

#4432 [auto-bump] [no-release-notes] dependency by reltuk
  go/go.mod
  go/go.sum
Labels: gms-bump
