Repository dolthub/dolt, pull requests merged in 2022-11, with the labels that each got.

#4709 [auto-bump] [no-release-notes] dependency by PavelSafronov
  go/go.mod
  go/go.sum
Labels: gms-bump

#4719 [auto-bump] [no-release-notes] dependency by JCOR11599
  go/go.mod
  go/go.sum
Labels: gms-bump

#4734 [ga-bump-dep] [no-release-notes] Bump dependency in Dolt by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump, keep-alive

#4748 [auto-bump] [no-release-notes] dependency by max-hoffman
  go/go.mod
  go/go.sum
Labels: gms-bump

#4758 [auto-bump] [no-release-notes] dependency by druvv
  go/go.mod
  go/go.sum
Labels: gms-bump

#4766 [auto-bump] [no-release-notes] dependency by jennifersp
  go/go.mod
  go/go.sum
Labels: gms-bump

#4770 [auto-bump] [no-release-notes] dependency by JCOR11599
  go/go.mod
  go/go.sum
Labels: gms-bump

#4772 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump

#4809 [auto-bump] [no-release-notes] dependency by JCOR11599
  go/go.mod
  go/go.sum
Labels: gms-bump

#4819 [auto-bump] [no-release-notes] dependency by JCOR11599
  go/go.mod
  go/go.sum
Labels: gms-bump

#4822 [auto-bump] [no-release-notes] dependency by JCOR11599
  go/go.mod
  go/go.sum
Labels: gms-bump

#4828 [auto-bump] [no-release-notes] dependency by jennifersp
  go/go.mod
  go/go.sum
Labels: gms-bump

#4835 [auto-bump] [no-release-notes] dependency by PavelSafronov
  go/go.mod
  go/go.sum
Labels: gms-bump

#4831 Fix issues with docker entrypoint
  docker/docker-entrypoint.sh
  docker/serverDockerfile
Labels: contribution

#4842 [auto-bump] [no-release-notes] dependency by JCOR11599
  go/go.mod
  go/go.sum
Labels: gms-bump

#4852 [auto-bump] [no-release-notes] dependency by Hydrocharged
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/sqlinsert_test.go
Labels: gms-bump

#4855 [auto-bump] [no-release-notes] dependency by JCOR11599
  go/go.mod
  go/go.sum
Labels: gms-bump

#4870 [auto-bump] [no-release-notes] dependency by max-hoffman
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/integration_test/stockmarket_test.go
Labels: gms-bump

#4876 [auto-bump] [no-release-notes] dependency by bheni
  go/go.mod
  go/go.sum
Labels: gms-bump

#4880 [auto-bump] [no-release-notes] dependency by Hydrocharged
  go/go.mod
  go/go.sum
Labels: gms-bump

#4888 [auto-bump] [no-release-notes] dependency by max-hoffman
  go/go.mod
  go/go.sum
  integration-tests/go-sql-server-driver/go.mod
  integration-tests/go-sql-server-driver/go.sum
Labels: gms-bump

#4879 Fix value being read in param suffix
  go/libraries/utils/argparser/args_test.go
  go/libraries/utils/argparser/parser.go
  go/libraries/utils/argparser/parser_test.go
Labels: contribution
