Repository dolthub/dolt, pull requests merged in 2022-12, with the labels that each got.

#4897 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
  go/libraries/doltcore/schema/typeinfo/time_test.go
Labels: gms-bump, keep-alive

#4905 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump

#4910 [auto-bump] [no-release-notes] dependency by Hydrocharged
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/dtables/conflicts_tables_prolly.go
Labels: gms-bump

#4924 found another minor bug in results.go
  go/libraries/utils/argparser/results.go
Labels: contribution

#4938 [auto-bump] [no-release-notes] dependency by JCOR11599
  go/go.mod
  go/go.sum
Labels: gms-bump

#4951 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump

#4983 [auto-bump] [no-release-notes] dependency by JCOR11599
  go/go.mod
  go/go.sum
Labels: gms-bump

#4984 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump

#4990 [auto-bump] [no-release-notes] dependency by jennifersp
  go/go.mod
  go/go.sum
  go/libraries/doltcore/schema/typeinfo/decimal_test.go
Labels: gms-bump, keep-alive

#4993 [auto-bump] [no-release-notes] dependency by Hydrocharged
  go/go.mod
  go/go.sum
Labels: gms-bump

#5009 [auto-bump] [no-release-notes] dependency by JCOR11599
  go/go.mod
  go/go.sum
Labels: gms-bump

#5016 [auto-bump] [no-release-notes] dependency by max-hoffman
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries.go
  go/libraries/doltcore/sqle/enginetest/dolt_query_plans.go
  go/libraries/doltcore/sqle/integration_test/stockmarket_test.go
  go/libraries/doltcore/sqle/tables.go
Labels: gms-bump

#5020 [auto-bump] [no-release-notes] dependency by jennifersp
  go/go.mod
  go/go.sum
  integration-tests/bats/default-values.bats
Labels: gms-bump, keep-alive

#5021 [auto-bump] [no-release-notes] dependency by Hydrocharged
  go/go.mod
  go/go.sum
Labels: gms-bump

#5025 Fix instructions for first connect
  README.md
Labels: contribution

#5029 [auto-bump] [no-release-notes] dependency by JCOR11599
  go/go.mod
  go/go.sum
Labels: gms-bump

#5036 [auto-bump] [no-release-notes] dependency by JCOR11599
  go/go.mod
  go/go.sum
Labels: gms-bump

#5041 [auto-bump] [no-release-notes] dependency by JCOR11599
  go/go.mod
  go/go.sum
Labels: gms-bump

#5046 [auto-bump] [no-release-notes] dependency by Hydrocharged
  go/go.mod
  go/go.sum
  go/libraries/doltcore/schema/typeinfo/datetime_test.go
Labels: gms-bump

#5047 [auto-bump] [no-release-notes] dependency by jennifersp
  go/cmd/dolt/commands/engine/sqlengine.go
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/enginetest/dolt_harness.go
Labels: gms-bump, keep-alive

#5048 docs(README): add info about sql command
  README.md
Labels: contribution

#5051 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump

#5056 [auto-bump] [no-release-notes] dependency by coffeegoddd
  go/go.mod
  go/go.sum
Labels: gms-bump

#5069 [auto-bump] [no-release-notes] dependency by zachmu
  go/go.mod
  go/go.sum
Labels: gms-bump
