Repository dolthub/dolt, pull requests merged in 2023-08, with the labels that each got.

#6451 [auto-bump] [no-release-notes] dependency by nicktobey
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
  go/performance/continuous_integration/SysbenchDockerfile.dockerignore
Labels: gms-bump, keep-alive

#6463 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump

#6459 Log a SQL warning when historical values don't fit in `dolt_diff_<tablename>`'s schema
  go/libraries/doltcore/rowconv/row_converter.go
  go/libraries/doltcore/sqle/dtables/diff_table.go
  go/libraries/doltcore/sqle/dtables/prolly_row_conv.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_diff.go
  integration-tests/bats/system-tables.bats
Labels: minor version bump

#6472 [auto-bump] [no-release-notes] dependency by nicktobey
  go/go.mod
  go/go.sum
Labels: gms-bump

#6477 [auto-bump] [no-release-notes] dependency by macneale4
  go/go.mod
  go/go.sum
Labels: gms-bump

#6470 Bug Fix: Error on merges that produce schema conflicts when `@@autocommit` is enabled
  go/libraries/doltcore/sqle/dsess/transactions.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_merge.go
  integration-tests/bats/schema-conflicts.bats
  integration-tests/bats/sql-merge.bats
Labels: minor version bump

#6487 feat: adding zsh plugin
  dolt.plugin.zsh
Labels: contribution

#6495 [auto-bump] [no-release-notes] dependency by macneale4
  go/go.mod
  go/go.sum
Labels: gms-bump

#6501 [auto-bump] [no-release-notes] dependency by nicktobey
  go/go.mod
  go/go.sum
Labels: gms-bump

#6512 [auto-bump] [no-release-notes] dependency by Hydrocharged
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
Labels: gms-bump

#6506 Drop the aws flags from the `dolt_remote()` procedure
  go/cmd/dolt/cli/arg_parser_helpers.go
  go/cmd/dolt/commands/remote.go
  go/libraries/doltcore/sqle/dprocedures/dolt_clone.go
  go/libraries/doltcore/sqle/dprocedures/dolt_remote.go
Labels: minor version bump

#6535 [auto-bump] [no-release-notes] dependency by JCOR11599
  go/go.mod
  go/go.sum
Labels: gms-bump

#6545 [auto-bump] [no-release-notes] dependency by Hydrocharged
  go/go.mod
  go/go.sum
  go/libraries/doltcore/diff/table_deltas.go
  go/libraries/doltcore/mvdata/engine_table_writer.go
  go/libraries/doltcore/sqle/dolt_patch_table_function.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries.go
  go/libraries/doltcore/sqle/sqlfmt/schema_fmt.go
  integration-tests/bats/sql-charsets-collations.bats
Labels: gms-bump

#6555 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump

#6557 [auto-bump] [no-release-notes] dependency by Hydrocharged
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
  go/libraries/doltcore/table/editor/creation/index.go
Labels: gms-bump

#6474 `dolt_status` system table shows if merge is active when there are no conflicts
  go/libraries/doltcore/doltdb/workingset.go
  go/libraries/doltcore/sqle/dprocedures/dolt_conflicts_resolve.go
  go/libraries/doltcore/sqle/dtables/status_table.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_merge.go
Labels: minor version bump

#6561 [auto-bump] [no-release-notes] dependency by Hydrocharged
  go/go.mod
  go/go.sum
Labels: gms-bump

#6569 [auto-bump] [no-release-notes] dependency by macneale4
  go/go.mod
  go/go.sum
  go/libraries/doltcore/mvdata/engine_table_writer.go
Labels: gms-bump, keep-alive

#6537 Added a `--branch` parameter to Dolt global arguments on the command line.
  go/cmd/dolt/cli/arg_parser_helpers.go
  go/cmd/dolt/commands/utils.go
  go/cmd/dolt/dolt.go
  integration-tests/bats/global-args.bats
Labels: contribution

#6587 [auto-bump] [no-release-notes] dependency by reltuk
  go/go.mod
  go/go.sum
  go/libraries/doltcore/mvdata/channel_row_source.go
  go/libraries/doltcore/sqle/dolt_diff_stat_table_function.go
  go/libraries/doltcore/sqle/dolt_diff_summary_table_function.go
  go/libraries/doltcore/sqle/dolt_diff_table_function.go
  go/libraries/doltcore/sqle/dolt_log_table_function.go
  go/libraries/doltcore/sqle/dolt_patch_table_function.go
  go/libraries/doltcore/sqle/dolt_query_diff_table_function.go
  go/libraries/doltcore/sqle/dolt_schema_diff_table_function.go
  go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
Labels: gms-bump, keep-alive

#6589 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump

#6592 [auto-bump] [no-release-notes] dependency by reltuk
  go/go.mod
  go/go.sum
Labels: gms-bump

#6597 [auto-bump] [no-release-notes] dependency by max-hoffman
  go/go.mod
  go/go.sum
Labels: gms-bump

#6602 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump, keep-alive

#6604 [auto-bump] [no-release-notes] dependency by nicktobey
  go/go.mod
  go/go.sum
Labels: gms-bump
