Repository dolthub/dolt, pull requests merged in 2023-10, with the labels that each got.

#6775 [auto-bump] [no-release-notes] dependency by JCOR11599
  go/go.mod
  go/go.sum
  integration-tests/MySQLDockerfile
Labels: gms-bump, keep-alive

#6778 [auto-bump] [no-release-notes] dependency by zachmu
  go/go.mod
  go/go.sum
Labels: gms-bump

#6791 [auto-bump] [no-release-notes] dependency by nicktobey
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
Labels: gms-bump

#6804 [auto-bump] [no-release-notes] dependency by max-hoffman
  go/go.mod
  go/go.sum
Labels: gms-bump, keep-alive

#6811 [auto-bump] [no-release-notes] dependency by jennifersp
  go/go.mod
  go/go.sum
Labels: gms-bump

#6812 [auto-bump] [no-release-notes] dependency by macneale4
  go/go.mod
  go/go.sum
Labels: gms-bump

#6814 [auto-bump] [no-release-notes] dependency by JCOR11599
  go/go.mod
  go/go.sum
  integration-tests/bats/sql-batch.bats
Labels: gms-bump, keep-alive

#6825 [auto-bump] [no-release-notes] dependency by jennifersp
  go/go.mod
  go/go.sum
Labels: gms-bump

#6827 Automatically create `dolt_docs` table
  go/cmd/dolt/commands/docscmds/read.go
  go/libraries/doltcore/doltdb/system_table.go
  go/libraries/doltcore/sqle/database.go
  go/libraries/doltcore/sqle/dtables/docs_table.go
  go/libraries/doltcore/sqle/sqlddl_test.go
  go/libraries/doltcore/sqle/sqlselect_test.go
  integration-tests/bats/cp-and-mv.bats
  integration-tests/bats/docs.bats
  integration-tests/mysql-client-tests/node/workbenchTests/docs.js
Labels: minor version bump

#6830 [auto-bump] [no-release-notes] dependency by JCOR11599
  go/go.mod
  go/go.sum
Labels: gms-bump

#6837 [auto-bump] [no-release-notes] dependency by macneale4
  go/go.mod
  go/go.sum
Labels: gms-bump

#6839 [auto-bump] [no-release-notes] dependency by JCOR11599
  go/go.mod
  go/go.sum
Labels: gms-bump

#6842 [auto-bump] [no-release-notes] dependency by JCOR11599
  go/go.mod
  go/go.sum
Labels: gms-bump, keep-alive

#6846 [auto-bump] [no-release-notes] dependency by jennifersp
  go/go.mod
  go/go.sum
Labels: gms-bump

#6851 [auto-bump] [no-release-notes] dependency by JCOR11599
  go/go.mod
  go/go.sum
Labels: gms-bump

#6856 [auto-bump] [no-release-notes] dependency by max-hoffman
  go/go.mod
  go/go.sum
Labels: gms-bump

#6877 [auto-bump] [no-release-notes] dependency by max-hoffman
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/dolt_diff_stat_table_function.go
  go/libraries/doltcore/sqle/dolt_diff_summary_table_function.go
  go/libraries/doltcore/sqle/dolt_diff_table_function.go
  go/libraries/doltcore/sqle/dolt_log_table_function.go
  go/libraries/doltcore/sqle/dolt_patch_table_function.go
  go/libraries/doltcore/sqle/dolt_query_diff_table_function.go
  go/libraries/doltcore/sqle/dolt_schema_diff_table_function.go
Labels: gms-bump

#6913 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
  go/libraries/doltcore/sqle/enginetest/dolt_harness.go
Labels: gms-bump

#6914 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump

#6915 [auto-bump] [no-release-notes] dependency by macneale4
  go/go.mod
  go/go.sum
Labels: gms-bump

#6917 Dolt admin procedures
  go/libraries/doltcore/sqle/dprocedures/init.go
  integration-tests/bats/sql-mysqldb-privs.bats
  integration-tests/bats/sql-privs.bats
  integration-tests/bats/sql-procedure-privs.bats
Labels: minor version bump
