Repository dolthub/dolt, pull requests merged in 2023-06, with the labels that each got.

#6070 [auto-bump] [no-release-notes] dependency by Hydrocharged
  go/go.mod
  go/go.sum
Labels: gms-bump

#6075 [auto-bump] [no-release-notes] dependency by bheni
  go/go.mod
  go/go.sum
Labels: gms-bump

#6065 update dolt blame to use sql backend and accept specific revision
  go/cmd/dolt/commands/blame.go
  integration-tests/bats/blame.bats
  integration-tests/bats/sql-local-remote.bats
Labels: cli

#6015 Migrate `dolt add` to use Sql backend.
  go/cmd/dolt/commands/add.go
  go/cmd/dolt/commands/cherry-pick.go
  go/cmd/dolt/commands/revert.go
  go/cmd/dolt/dolt.go
  go/libraries/doltcore/doltdb/errors.go
  integration-tests/bats/add.bats
  integration-tests/bats/helper/local-remote.bash
  integration-tests/bats/sql-local-remote.bats
Labels: cli

#6091 [auto-bump] [no-release-notes] dependency by max-hoffman
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/binlogreplication/binlog_replication_test.go
Labels: gms-bump

#6098 [auto-bump] [no-release-notes] dependency by max-hoffman
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
  go/libraries/doltcore/sqle/index/dolt_index.go
Labels: gms-bump

#6129 [auto-bump] [no-release-notes] dependency by fulghum
  .github/workflows/ci-bats-unix-remote.yaml
  .github/workflows/ci-bats-unix.yaml
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/binlogreplication/binlog_replica_controller.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_replica_filtering.go
  integration-tests/bats/remotes-sql-server.bats
  integration-tests/bats/sql-shell.bats
  integration-tests/bats/sql.bats
Labels: gms-bump, keep-alive

#6133 Update README.md
  README.md
Labels: contribution

#6135 [auto-bump] [no-release-notes] dependency by jennifersp
  go/go.mod
  go/go.sum
Labels: gms-bump

#6011 Rewrite `dolt status` subcommand to use SQL queries to generate results.
  go/cmd/dolt/cli/arg_parser_helpers.go
  go/cmd/dolt/commands/stashcmds/pop.go
  go/cmd/dolt/commands/status.go
  go/cmd/dolt/dolt.go
  go/libraries/doltcore/doltdb/ignore.go
  go/libraries/doltcore/sqle/dprocedures/dolt_count_commits.go
  go/libraries/doltcore/sqle/dprocedures/init.go
  go/libraries/doltcore/sqle/dtables/branches_table.go
  go/libraries/doltcore/sqle/sqlselect_test.go
  integration-tests/bats/replication.bats
  integration-tests/bats/sql-local-remote.bats
  integration-tests/bats/sql-server.bats
  integration-tests/bats/status.bats
  integration-tests/mysql-client-tests/node/workbenchTests/branches.js
Labels: cli

#6140 [auto-bump] [no-release-notes] dependency by max-hoffman
  go/go.mod
  go/go.sum
Labels: gms-bump

#6147 [auto-bump] [no-release-notes] dependency by JCOR11599
  go/go.mod
  go/go.sum
Labels: gms-bump

#6177 [auto-bump] [no-release-notes] dependency by max-hoffman
  go/go.mod
  go/go.sum
Labels: gms-bump

#6202 [auto-bump] [no-release-notes] dependency by JCOR11599
  go/go.mod
  go/go.sum
Labels: gms-bump

#6211 [auto-bump] [no-release-notes] dependency by JCOR11599
  go/go.mod
  go/go.sum
Labels: gms-bump

#6219 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump

#6222 [auto-bump] [no-release-notes] dependency by JCOR11599
  go/go.mod
  go/go.sum
Labels: gms-bump, keep-alive

#6237 chore: fmt modify
  go/cmd/dolt/commands/assist.go
  go/cmd/dolt/commands/dump.go
  go/cmd/dolt/commands/engine/jwtplugin_test.go
  go/cmd/dolt/commands/log.go
  go/cmd/dolt/commands/sqlserver/sqlserver.go
  go/cmd/dolt/commands/status.go
  go/libraries/doltcore/mvdata/channel_row_source.go
  go/libraries/doltcore/mvdata/engine_table_writer.go
  go/libraries/doltcore/mvdata/file_data_loc.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_replication_reconnect_test.go
  go/libraries/doltcore/sqle/dfunctions/active_branch.go
  go/libraries/doltcore/sqle/dprocedures/dolt_branch.go
  go/libraries/doltcore/sqle/dtables/diff_table.go
  go/libraries/doltcore/sqle/index/mergeable_indexes_test.go
  go/libraries/doltcore/sqle/integration_test/history_table_test.go
  go/libraries/doltcore/table/untyped/csv/reader.go
  go/performance/utils/sysbench_runner/mysql.go
  go/performance/utils/sysbench_runner/run.go
  go/performance/utils/tpcc_runner/run.go
  go/store/datas/stashlist.go
  go/store/prolly/benchmark/benchmark_read_test.go
  go/store/prolly/tree/node_splitter_test.go
  go/store/spec/absolute_path_test.go
Labels: contribution

#6268 chore: slice replace loop
  go/cmd/dolt/commands/diff.go
  go/libraries/doltcore/sqle/sqlfmt/schema_fmt.go
  go/libraries/events/event_flush_test.go
Labels: contribution
