Repository dolthub/dolt, pull requests merged in 2023-12, with the labels that each got.

#7097 [auto-bump] [no-release-notes] dependency by JCOR11599
  go/go.mod
  go/go.sum
Labels: gms-bump

#7102 [auto-bump] [no-release-notes] dependency by max-hoffman
  .github/workflows/ci-bats-unix-remote.yaml
  .github/workflows/ci-bats-unix.yaml
  go/go.mod
  go/go.sum
Labels: gms-bump

#7131 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump

#7134 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump

#7142 [auto-bump] [no-release-notes] dependency by max-hoffman
  go/go.mod
  go/go.sum
Labels: gms-bump

#7144 [auto-bump] [no-release-notes] dependency by JCOR11599
  go/go.mod
  go/go.sum
Labels: gms-bump

#7150 [auto-bump] [no-release-notes] dependency by JCOR11599
  go/go.mod
  go/go.sum
Labels: gms-bump

#7160 [auto-bump] [no-release-notes] dependency by jennifersp
  go/go.mod
  go/go.sum
Labels: gms-bump

#7115 serialize `on update` expressions
  go/cmd/dolt/commands/diff.go
  go/gen/fb/serial/schema.go
  go/go.mod
  go/go.sum
  go/libraries/doltcore/merge/merge_prolly_rows.go
  go/libraries/doltcore/mvdata/engine_table_writer.go
  go/libraries/doltcore/schema/column.go
  go/libraries/doltcore/schema/encoding/serialization.go
  go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
  go/libraries/doltcore/sqle/sqlfmt/schema_fmt.go
  go/libraries/doltcore/sqle/sqlutil/convert.go
  go/serial/schema.fbs
Labels: minor version bump

#7184 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
  go/libraries/doltcore/schema/typeinfo/decimal_test.go
Labels: gms-bump

#7189 [auto-bump] [no-release-notes] dependency by jennifersp
  go/Godeps/LICENSES
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/enginetest/branch_control_test.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_merge.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_schema_merge.go
  go/libraries/doltcore/sqle/enginetest/privilege_test.go
  integration-tests/go-sql-server-driver/go.mod
  integration-tests/go-sql-server-driver/go.sum
Labels: gms-bump, keep-alive

#7193 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump

#7202 [auto-bump] [no-release-notes] dependency by max-hoffman
  go/go.mod
  go/go.sum
Labels: gms-bump

#7152 Support pushing to a sql-server instance
  go/cmd/dolt/cli/arg_parser_helpers.go
  go/cmd/dolt/commands/push.go
  go/cmd/dolt/commands/sqlserver/server.go
  go/cmd/dolt/commands/sqlserver/serverconfig.go
  go/cmd/dolt/commands/sqlserver/sqlserver.go
  go/cmd/dolt/commands/sqlserver/yaml_config.go
  go/libraries/doltcore/doltdb/commit_hooks.go
  go/libraries/doltcore/doltdb/doltdb.go
  go/libraries/doltcore/doltdb/hooksdatabase.go
  go/libraries/doltcore/env/actions/remotes.go
  go/libraries/doltcore/env/actions/reset.go
  go/libraries/doltcore/merge/action.go
  go/libraries/doltcore/remotesrv/interceptors.go
  go/libraries/doltcore/remotesrv/server.go
  go/libraries/doltcore/sqle/cluster/controller.go
  go/libraries/doltcore/sqle/dprocedures/dolt_push.go
  go/libraries/doltcore/sqle/dprocedures/dolt_reset.go
  go/libraries/doltcore/sqle/remotesrv.go
  go/store/cmd/noms/noms_ds.go
  go/store/datas/commit.go
  go/store/datas/database.go
  go/store/datas/database_common.go
  go/store/datas/database_test.go
  go/store/datas/pull/puller_test.go
  integration-tests/bats/helper/query-server-common.bash
  integration-tests/bats/sql-server-remotesrv.bats
Labels: minor version bump

#7135 Removing `--old-format` option from `dolt init`
  go/cmd/dolt/commands/init.go
  integration-tests/bats/migrate.bats
  integration-tests/bats/spatial-index.bats
Labels: minor version bump

#7212 [auto-bump] [no-release-notes] dependency by max-hoffman
  go/go.mod
  go/go.sum
Labels: gms-bump

#7215 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump

#7219 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump

#7220 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump

#7225 [auto-bump] [no-release-notes] dependency by max-hoffman
  go/go.mod
  go/go.sum
Labels: gms-bump

#7226 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, keep-alive
