Repository dolthub/dolt, pull requests merged in 2023-11, with the labels that each got.

#6922 [auto-bump] [no-release-notes] dependency by JCOR11599
  go/go.mod
  go/go.sum
  integration-tests/go-sql-server-driver/testdata/test_jwks.json
  integration-tests/go-sql-server-driver/testdata/token.jwt
Labels: gms-bump, keep-alive

#6928 [auto-bump] [no-release-notes] dependency by zachmu
  go/go.mod
  go/go.sum
Labels: gms-bump

#6882 Feature: Dolt reflog support
  go/libraries/doltcore/doltdb/doltdb.go
  go/libraries/doltcore/sqle/database_provider.go
  go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries.go
  go/libraries/doltcore/sqle/reflog_table_function.go
  go/store/nbs/journal.go
  go/store/nbs/journal_chunk_source.go
  go/store/nbs/journal_record.go
  go/store/nbs/journal_record_test.go
  go/store/nbs/journal_test.go
  go/store/nbs/journal_writer.go
  go/store/nbs/journal_writer_test.go
  go/store/nbs/store.go
Labels: minor version bump

#6949 [auto-bump] [no-release-notes] dependency by JCOR11599
  go/go.mod
  go/go.sum
Labels: gms-bump

#6962 [auto-bump] [no-release-notes] dependency by jennifersp
  go/go.mod
  go/go.sum
Labels: gms-bump, keep-alive

#6968 [auto-bump] [no-release-notes] dependency by max-hoffman
  go/go.mod
  go/go.sum
Labels: gms-bump

#6981 [auto-bump] [no-release-notes] dependency by Hydrocharged
  go/go.mod
  go/go.sum
Labels: gms-bump

#6984 [auto-bump] [no-release-notes] dependency by jennifersp
  go/go.mod
  go/go.sum
Labels: gms-bump

#6985 [no-release-notes] bump feature version
  go/libraries/doltcore/doltdb/root_val.go
  go/libraries/doltcore/sqle/sqlselect_test.go
  integration-tests/bats/helper/common.bash
Labels: minor version bump

#6988 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump, keep-alive

#6990 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump

#7002 [auto-bump] [no-release-notes] dependency by max-hoffman
  go/go.mod
  go/go.sum
Labels: gms-bump

#6994 Concurrent remotes map
  .github/workflows/ci-go-race-tests.yaml
  go/cmd/dolt/commands/remote.go
  go/libraries/doltcore/env/actions/branch.go
  go/libraries/doltcore/env/environment.go
  go/libraries/doltcore/env/environment_test.go
  go/libraries/doltcore/env/memory.go
  go/libraries/doltcore/env/remotes.go
  go/libraries/doltcore/env/repo_state.go
  go/libraries/doltcore/sqle/cluster/controller.go
  go/libraries/doltcore/sqle/cluster/initdbhook.go
  go/libraries/doltcore/sqle/clusterdb/database.go
  go/libraries/doltcore/sqle/database.go
  go/libraries/doltcore/sqle/database_provider.go
  go/libraries/doltcore/sqle/dprocedures/dolt_remote.go
  go/libraries/doltcore/sqle/dsess/database_session_state.go
  go/libraries/doltcore/sqle/dsess/session_state_adapter.go
  go/libraries/doltcore/sqle/dtables/remotes_table.go
  go/libraries/doltcore/sqle/read_replica_database.go
  go/libraries/doltcore/sqle/replication.go
  go/libraries/doltcore/sqle/user_space_database.go
  go/libraries/utils/concurrentmap/concurrentmap.go
  go/libraries/utils/concurrentmap/concurrentmap_test.go
Labels: contribution

#6995 allow hyphen in db name to match its dir name
  go/cmd/dolt/commands/query_diff.go
  go/cmd/dolt/commands/sqlserver/sqlclient.go
  go/libraries/doltcore/dbfactory/dirtodbname.go
  go/libraries/doltcore/dconfig/envvars.go
  go/libraries/doltcore/env/multi_repo_env_test.go
  integration-tests/bats/blame.bats
  integration-tests/bats/branch-control.bats
  integration-tests/bats/create-views.bats
  integration-tests/bats/db-revision-specifiers.bats
  integration-tests/bats/deleted-branches.bats
  integration-tests/bats/dump.bats
  integration-tests/bats/foreign-keys.bats
  integration-tests/bats/remotes.bats
  integration-tests/bats/sql-checkout.bats
  integration-tests/bats/sql-client.bats
  integration-tests/bats/sql-commit.bats
  integration-tests/bats/sql-create-database.bats
  integration-tests/bats/sql-merge.bats
  integration-tests/bats/sql-reset.bats
  integration-tests/bats/sql-server.bats
  integration-tests/bats/sql-shell.bats
  integration-tests/bats/sql.bats
  integration-tests/bats/system-tables.bats
  integration-tests/bats/undrop.bats
Labels: minor version bump

#7013 [auto-bump] [no-release-notes] dependency by jennifersp
  go/go.mod
  go/go.sum
Labels: gms-bump

#7021 [auto-bump] [no-release-notes] dependency by JCOR11599
  go/go.mod
  go/go.sum
Labels: gms-bump

#7024 Concurrent branches map
  go/libraries/doltcore/env/actions/branch.go
  go/libraries/doltcore/env/environment.go
  go/libraries/doltcore/env/environment_test.go
  go/libraries/doltcore/env/memory.go
  go/libraries/doltcore/env/remotes.go
  go/libraries/doltcore/env/repo_state.go
  go/libraries/doltcore/sqle/database.go
  go/libraries/doltcore/sqle/dsess/database_session_state.go
  go/libraries/doltcore/sqle/dsess/session_state_adapter.go
  go/libraries/doltcore/sqle/dtables/branches_table.go
Labels: contribution

#7037 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
  integration-tests/bats/default-values.bats
Labels: gms-bump, keep-alive

#7041 [auto-bump] [no-release-notes] dependency by JCOR11599
  go/go.mod
  go/go.sum
Labels: gms-bump

#7047 [auto-bump] [no-release-notes] dependency by JCOR11599
  go/go.mod
  go/go.sum
  go/libraries/doltcore/merge/merge_prolly_rows.go
Labels: gms-bump

#7053 [auto-bump] [no-release-notes] dependency by JCOR11599
  go/go.mod
  go/go.sum
Labels: gms-bump

#7058 [auto-bump] [no-release-notes] dependency by JCOR11599
  go/go.mod
  go/go.sum
Labels: gms-bump
