Repository dolthub/dolt, pull requests merged in 2023-02, with the labels that each got.

#5284 [auto-bump] [no-release-notes] dependency by max-hoffman
  go/go.mod
  go/go.sum
Labels: gms-bump

#5252 Fix int overflow on 32-bit architectures
  go/store/prolly/tree/testutils.go
  go/store/skip/list.go
Labels: contribution

#5320 store/datas: fix dropped errors
  go/store/datas/commit.go
Labels: contribution

#5343 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump

#5354 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump

#5363 [auto-bump] [no-release-notes] dependency by max-hoffman
  go/go.mod
  go/go.sum
Labels: gms-bump

#5382 [auto-bump] [no-release-notes] dependency by reltuk
  go/go.mod
  go/go.sum
Labels: gms-bump, keep-alive

#5391 Fixes comments in entrypoint
  docker/docker-entrypoint.sh
Labels: contribution

#5419 [auto-bump] [no-release-notes] dependency by Hydrocharged
  go/go.mod
  go/go.sum
Labels: gms-bump
