Repository dolthub/dolt, pull requests merged in 2023-04, with the labels that each got.

#5674 [auto-bump] [no-release-notes] dependency by PavelSafronov
  go/go.mod
  go/go.sum
  integration-tests/bats/json-new-fmt.bats
  integration-tests/bats/sql-vertical-format.expect
Labels: gms-bump

#5682 [auto-bump] [no-release-notes] dependency by jennifersp
  go/go.mod
  go/go.sum
Labels: gms-bump

#5697 [auto-bump] [no-release-notes] dependency by JCOR11599
  go/go.mod
  go/go.sum
  integration-tests/MySQLDockerfile
Labels: gms-bump, keep-alive

#5709 [auto-bump] [no-release-notes] dependency by reltuk
  go/go.mod
  go/go.sum
  integration-tests/go-sql-server-driver/go.mod
  integration-tests/go-sql-server-driver/go.sum
Labels: gms-bump, keep-alive

#5727 [auto-bump] [no-release-notes] dependency by timsehn
  go/go.mod
  go/go.sum
  go/libraries/doltcore/merge/violations_fk_prolly.go
  go/libraries/doltcore/merge/violations_unique_prolly.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_replication_alltypes_test.go
  go/libraries/doltcore/sqle/enginetest/ddl_queries.go
  go/libraries/doltcore/sqle/json/noms_json_value.go
  integration-tests/bats/blame-system-view.bats
  integration-tests/bats/constraint-violations.bats
  integration-tests/bats/json.bats
  integration-tests/bats/migration-integration.bats
  integration-tests/bats/types.bats
Labels: gms-bump, keep-alive

#5746 [auto-bump] [no-release-notes] dependency by jennifersp
  go/go.mod
  go/go.sum
Labels: gms-bump

#5747 [auto-bump] [no-release-notes] dependency by Hydrocharged
  go/go.mod
  go/go.sum
Labels: gms-bump

#5757 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/tables.go
Labels: gms-bump, keep-alive

#5655 Add BATS test that dolt log correctly tags HEAD commits.
  integration-tests/bats/log.bats
Labels: contribution

#5827 [auto-bump] [no-release-notes] dependency by JCOR11599
  go/go.mod
  go/go.sum
Labels: gms-bump, keep-alive

#5837 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump, keep-alive
