Repository dolthub/dolt, pull requests merged in 2023-09, with the labels that each got.

#6623 [auto-bump] [no-release-notes] dependency by max-hoffman
  go/go.mod
  go/go.sum
Labels: gms-bump

#6634 [auto-bump] [no-release-notes] dependency by max-hoffman
  go/go.mod
  go/go.sum
Labels: gms-bump

#6636 [auto-bump] [no-release-notes] dependency by macneale4
  go/go.mod
  go/go.sum
Labels: gms-bump

#6635 Change default of replication pull to force
  go/cmd/dolt/cli/arg_parser_helpers.go
  go/cmd/dolt/commands/merge.go
  go/cmd/dolt/commands/pull.go
  go/libraries/doltcore/doltdb/doltdb.go
  go/libraries/doltcore/env/remotes.go
  go/libraries/doltcore/merge/action.go
  go/libraries/doltcore/sqle/dprocedures/dolt_merge.go
  go/libraries/doltcore/sqle/dprocedures/dolt_pull.go
  go/libraries/doltcore/sqle/dsess/dolt_session_test.go
  go/libraries/doltcore/sqle/dsess/session.go
  go/libraries/doltcore/sqle/enginetest/dolt_server_test.go
  go/libraries/doltcore/sqle/system_variables.go
  integration-tests/bats/remotes.bats
  integration-tests/bats/replication.bats
  integration-tests/bats/sql-pull.bats
Labels: minor version bump

#6655 [auto-bump] [no-release-notes] dependency by JCOR11599
  go/go.mod
  go/go.sum
Labels: gms-bump, keep-alive

#6668 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump

#6672 [auto-bump] [no-release-notes] dependency by macneale4
  go/go.mod
  go/go.sum
Labels: gms-bump

#6674 [auto-bump] [no-release-notes] dependency by Hydrocharged
  go/go.mod
  go/go.sum
Labels: gms-bump

#6677 [auto-bump] [no-release-notes] dependency by nicktobey
  go/go.mod
  go/go.sum
Labels: gms-bump

#6680 [auto-bump] [no-release-notes] dependency by max-hoffman
  go/go.mod
  go/go.sum
  go/libraries/doltcore/mvdata/engine_table_writer.go
Labels: gms-bump

#6686 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump

#6698 [auto-bump] [no-release-notes] dependency by macneale4
  go/go.mod
  go/go.sum
Labels: gms-bump, keep-alive

#6708 [auto-bump] [no-release-notes] dependency by max-hoffman
  go/go.mod
  go/go.sum
Labels: gms-bump

#6715 [auto-bump] [no-release-notes] dependency by nicktobey
  go/go.mod
  go/go.sum
Labels: gms-bump

#6726 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump, keep-alive

#6702 reduce release sizes and speed up release time
  .github/workflows/cd-release.yaml
  go/utils/publishrelease/buildbinaries.sh
Labels: contribution

#6739 [auto-bump] [no-release-notes] dependency by jennifersp
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/enginetest/dolt_queries.go
  integration-tests/bats/blame.bats
  integration-tests/bats/create-views.bats
Labels: gms-bump

#6749 [auto-bump] [no-release-notes] dependency by nicktobey
  go/go.mod
  go/go.sum
Labels: gms-bump

#6753 adds message column to dolt_push output
  go/libraries/doltcore/sqle/dprocedures/dolt_push.go
  go/libraries/doltcore/sqle/dprocedures/init.go
  integration-tests/bats/sql-push.bats
Labels: minor version bump

#6757 [auto-bump] [no-release-notes] dependency by nicktobey
  go/go.mod
  go/go.sum
Labels: gms-bump
