Repository dolthub/dolt, pull requests merged in 2023-05, with the labels that each got.

#5851 [auto-bump] [no-release-notes] dependency by JCOR11599
  go/go.mod
  go/go.sum
Labels: gms-bump

#5854 [auto-bump] [no-release-notes] dependency by jennifersp
  go/go.mod
  go/go.sum
Labels: gms-bump

#5859 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump, keep-alive

#5869 [auto-bump] [no-release-notes] dependency by Hydrocharged
  go/go.mod
  go/go.sum
Labels: gms-bump

#5879 [auto-bump] [no-release-notes] dependency by max-hoffman
  go/go.mod
  go/go.sum
Labels: gms-bump

#5883 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump

#5891 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump

#5893 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump

#5905 [auto-bump] [no-release-notes] dependency by JCOR11599
  go/go.mod
  go/go.sum
Labels: gms-bump, keep-alive

#5908 [auto-bump] [no-release-notes] dependency by JCOR11599
  go/go.mod
  go/go.sum
Labels: gms-bump

#5844 Mention official Arch Linux packaging in README
  README.md
Labels: contribution

#5935 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump

#5947 [auto-bump] [no-release-notes] dependency by Hydrocharged
  go/go.mod
  go/go.sum
Labels: gms-bump

#5955 [auto-bump] [no-release-notes] dependency by Hydrocharged
  go/Godeps/LICENSES
  go/go.mod
  go/go.sum
Labels: gms-bump

#5971 [auto-bump] [no-release-notes] dependency by JCOR11599
  go/go.mod
  go/go.sum
Labels: gms-bump

#5989 [auto-bump] [no-release-notes] dependency by JCOR11599
  go/go.mod
  go/go.sum
  integration-tests/bats/sql-spatial-types.bats
  integration-tests/data-dump-loading-tests/import-mysqldump.bats
Labels: gms-bump, keep-alive

#6031 [auto-bump] [no-release-notes] dependency by JCOR11599
  go/go.mod
  go/go.sum
Labels: gms-bump

#6032 [auto-bump] [no-release-notes] dependency by JCOR11599
  go/go.mod
  go/go.sum
  integration-tests/bats/import-append-tables.bats
Labels: gms-bump

#6034 [auto-bump] [no-release-notes] dependency by zachmu
  go/go.mod
  go/go.sum
Labels: gms-bump

#6066 [auto-bump] [no-release-notes] dependency by JCOR11599
  go/go.mod
  go/go.sum
Labels: gms-bump
