Repository dolthub/dolt, pull requests merged in 2023-07, with the labels that each got.

#6301 [auto-bump] [no-release-notes] dependency by JCOR11599
  go/go.mod
  go/go.sum
Labels: gms-bump

#6312 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump

#6316 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump

#6346 Allow empty databases in the shell prompt
  go/cmd/dolt/commands/sql.go
  integration-tests/bats/sql-shell-empty-prompt.expect
  integration-tests/bats/sql-shell.bats
  integration-tests/bats/sql-works-after-failing-query.expect
Labels: cli, panic

#6359 [auto-bump] [no-release-notes] dependency by JCOR11599
  go/go.mod
  go/go.sum
Labels: gms-bump

#6366 [auto-bump] [no-release-notes] dependency by JCOR11599
  go/go.mod
  go/go.sum
Labels: gms-bump

#6376 [auto-bump] [no-release-notes] dependency by JCOR11599
  go/go.mod
  go/go.sum
Labels: gms-bump

#6377 [auto-bump] [no-release-notes] dependency by JCOR11599
  go/go.mod
  go/go.sum
Labels: gms-bump

#6380 [auto-bump] [no-release-notes] dependency by tbantle22
  go/go.mod
  go/go.sum
Labels: gms-bump

#6388 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump

#6418 [auto-bump] [no-release-notes] dependency by reltuk
  go/cmd/dolt/commands/sqlserver/server.go
  go/cmd/dolt/commands/utils.go
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/binlogreplication/binlog_metadata_persistence.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_replica_controller.go
Labels: gms-bump, keep-alive
