Repository dolthub/dolt, pull requests merged in 2024-07, with the labels that each got.

#8091 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8087 Bug fix: Use correct log position in Dolt to MySQL replication heartbeats
  go/libraries/doltcore/sqle/binlogreplication/binlog_primary_streamer.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_primary_test.go
Labels: correctness_approved

#8093 go/libraries/doltcore/remotestorage: internal/reliable: Recv: Fix a race where a completed state machine run and a canceled parent context could return a nil response message with a nil error.
  go/libraries/doltcore/remotestorage/internal/reliable/grpc.go
  go/libraries/doltcore/remotestorage/internal/reliable/grpc_test.go
Labels: correctness_approved

#8090 dolt sql shell slash redux
  go/cmd/dolt/cli/cli_context.go
  go/cmd/dolt/commands/add.go
  go/cmd/dolt/commands/branch.go
  go/cmd/dolt/commands/checkout.go
  go/cmd/dolt/commands/commit.go
  go/cmd/dolt/commands/diff.go
  go/cmd/dolt/commands/log.go
  go/cmd/dolt/commands/merge.go
  go/cmd/dolt/commands/reset.go
  go/cmd/dolt/commands/sql.go
  go/cmd/dolt/commands/sql_slash.go
  go/cmd/dolt/commands/status.go
  go/cmd/dolt/commands/utils.go
  go/go.mod
  go/go.sum
  go/store/util/outputpager/page_output.go
  integration-tests/bats/sql-shell-slash-cmds.expect
  integration-tests/bats/sql-shell.bats
Labels: correctness_approved

#8094 [no-release-notes] Add test for nil bound value panic
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
  go/libraries/doltcore/sqle/enginetest/dolt_engine_tests.go
  go/libraries/doltcore/sqle/enginetest/stats_queries.go
  go/libraries/doltcore/sqle/statsnoms/write.go
Labels: correctness_approved

#8086 define schema for dolt_schemas table
  go/libraries/doltcore/sqle/database.go
  go/libraries/doltcore/sqle/schema_table.go
Labels: correctness_approved

#8098 [no-release-notes] Bug fix bump, small stats bug
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/statsnoms/load.go
  go/libraries/doltcore/sqle/statspro/dolt_stats.go
  go/libraries/doltcore/sqle/statspro/update_test.go
Labels: correctness_approved

#8101 go.mod: Migrate from gopkg.in/square/go-jose.v2 to gopkg.in/go-jose/go-jose.v2. Bump version. Picks up fix for CVE-2024-28180.
  go/Godeps/LICENSES
  go/go.mod
  go/go.sum
  go/libraries/doltcore/creds/creds.go
  go/libraries/doltcore/sqle/cluster/interceptors.go
  go/libraries/doltcore/sqle/cluster/interceptors_test.go
  go/libraries/doltcore/sqle/cluster/jwks.go
  go/libraries/utils/jwtauth/claims.go
  go/libraries/utils/jwtauth/jwks.go
  go/libraries/utils/jwtauth/validate.go
  go/libraries/utils/jwtauth/validator.go
Labels: correctness_approved

#8102 Bug fix: binlog heartbeat `nextLogPosition` field
  go/libraries/doltcore/sqle/binlogreplication/binlog_primary_streamer.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_primary_test.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_replication_test.go
Labels: correctness_approved

#8104 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
  go/libraries/doltcore/merge/merge_prolly_rows.go
  go/store/prolly/tree/json_indexed_document.go
Labels: gms-bump, correctness_approved

#8103 Optimize JSON_REMOVE on `IndexedJsonDocument`
  go/store/prolly/tree/json_chunker.go
  go/store/prolly/tree/json_cursor.go
  go/store/prolly/tree/json_indexed_document.go
  go/store/prolly/tree/json_indexed_document_test.go
  go/store/prolly/tree/json_location.go
Labels: correctness_approved

#8108 [auto-bump] [no-release-notes] dependency by tbantle22
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8112 [auto-bump] [no-release-notes] dependency by tbantle22
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8113 [auto-bump] [no-release-notes] dependency by tbantle22
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8115 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump, keep-alive, correctness_approved

#8107 Optimize JSON_SET and JSON_REPLACE on `IndexedJsonDocument`
  go/store/prolly/tree/json_chunker.go
  go/store/prolly/tree/json_indexed_document.go
  go/store/prolly/tree/json_indexed_document_test.go
Labels: correctness_approved

#8119 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8122 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8116 Return empty dolt_procedures and dolt_schemas tables
  go/cmd/dolt/commands/diff.go
  go/libraries/doltcore/doltdb/system_table.go
  go/libraries/doltcore/sqle/database.go
  go/libraries/doltcore/sqle/procedures_table.go
  go/libraries/doltcore/sqle/procedures_table_test.go
  go/libraries/doltcore/sqle/schema_table.go
  go/libraries/doltcore/sqle/schema_table_test.go
  go/libraries/doltcore/sqle/sqlddl_test.go
  go/libraries/doltcore/sqle/sqldelete_test.go
  go/libraries/doltcore/sqle/sqlinsert_test.go
  go/libraries/doltcore/sqle/sqlreplace_test.go
  go/libraries/doltcore/sqle/sqlselect_test.go
  go/libraries/doltcore/sqle/sqlupdate_test.go
  go/libraries/doltcore/sqle/tables.go
  integration-tests/bats/helper/old_dolt_schemas/config.json
  integration-tests/bats/helper/old_dolt_schemas/noms/4bujnjuatdli0klda7ucot0tl836jujt
  integration-tests/bats/helper/old_dolt_schemas/noms/5fms6l3ffldbk6t8qjumnjstmurvppk8
  integration-tests/bats/helper/old_dolt_schemas/noms/63c0dojobm5j7arp99hiq78hj1rtp7m5
  integration-tests/bats/helper/old_dolt_schemas/noms/aum9p7826iqaeq0pjtqlcn56hoj5nhht
  integration-tests/bats/helper/old_dolt_schemas/noms/chghnlvugtiui6khfo29cpfnfr3166qc
  integration-tests/bats/helper/old_dolt_schemas/noms/d0b8ibrrjvvv3f0mtd7hathtjq2vhig9
  integration-tests/bats/helper/old_dolt_schemas/noms/erturgf7to0f6r8prlbllflbshg5li4n
  integration-tests/bats/helper/old_dolt_schemas/noms/manifest
  integration-tests/bats/helper/old_dolt_schemas/noms/oik6v50p7q6as4t7qg7f1i06iomt9vn9
  integration-tests/bats/helper/old_dolt_schemas/noms/oktjimrpqi8m9dbpt3c7ikoaolhgtr2n
  integration-tests/bats/helper/old_dolt_schemas/noms/oldgen/6vvlbeph7glt2sskq43npe56la8p9akc
  integration-tests/bats/helper/old_dolt_schemas/noms/oldgen/LOCK
  integration-tests/bats/helper/old_dolt_schemas/noms/oldgen/manifest
  integration-tests/bats/helper/old_dolt_schemas/noms/qe0mct6rf8puhdnqecm185p63dacaqrt
  integration-tests/bats/helper/old_dolt_schemas/noms/ro000svvgga0k7hatg7fta9j8ismtc3b
  integration-tests/bats/helper/old_dolt_schemas/noms/u9c6ttq6ddrgqdfbod9pg2vv79ab6crt
  integration-tests/bats/helper/old_dolt_schemas/repo_state.json
  integration-tests/bats/triggers.bats
  integration-tests/mysql-client-tests/node/workbenchTests/views.js
Labels: minor version bump, correctness_approved

#8128 Bug fix: `dolt_reset()` should commit the active transaction
  go/libraries/doltcore/sqle/dprocedures/dolt_reset.go
  go/libraries/doltcore/sqle/enginetest/dolt_engine_tests.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries.go
Labels: correctness_approved

#8127 cache table list
  go/go.mod
  go/libraries/doltcore/doltdb/root_val.go
  go/libraries/doltcore/sqle/database.go
  go/libraries/doltcore/sqle/dsess/session_cache.go
Labels: correctness_approved

#8130 [auto-bump] [no-release-notes] dependency by tbantle22
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8132 Detect reading from non-indexed JSON documents and store it in a LazyJSONDocument instead of an IndexedJSONDocument.
  go/store/prolly/tree/blob_builder.go
  integration-tests/bats/json-oldformat-repo/.dolt/config.json
  integration-tests/bats/json-oldformat-repo/.dolt/noms/LOCK
  integration-tests/bats/json-oldformat-repo/.dolt/noms/journal.idx
  integration-tests/bats/json-oldformat-repo/.dolt/noms/manifest
  integration-tests/bats/json-oldformat-repo/.dolt/noms/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
  integration-tests/bats/json-oldformat-repo/.dolt/repo_state.json
  integration-tests/bats/json-oldformat-repo/.dolt/stats/.dolt/config.json
  integration-tests/bats/json-oldformat-repo/.dolt/stats/.dolt/noms/LOCK
  integration-tests/bats/json-oldformat-repo/.dolt/stats/.dolt/noms/journal.idx
  integration-tests/bats/json-oldformat-repo/.dolt/stats/.dolt/noms/manifest
  integration-tests/bats/json-oldformat-repo/.dolt/stats/.dolt/noms/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
  integration-tests/bats/json-oldformat-repo/.dolt/stats/.dolt/repo_state.json
  integration-tests/bats/json-oldformat.bats
Labels: correctness_approved

#8084 enable key range iter
  go/store/prolly/tuple_map.go
Labels: correctness_approved

#8072 [rowexec] dolt-side lookup execution operator
  go/cmd/dolt/commands/engine/sqlengine.go
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/enginetest/dolt_harness.go
  go/libraries/doltcore/sqle/index/index_reader.go
  go/libraries/doltcore/sqle/index/keyless_iter.go
  go/libraries/doltcore/sqle/index/prolly_index_iter.go
  go/libraries/doltcore/sqle/index/prolly_row_iter.go
  go/libraries/doltcore/sqle/index/secondary_iter.go
  go/libraries/doltcore/sqle/indexed_dolt_table.go
  go/libraries/doltcore/sqle/rowexec/builder.go
  go/libraries/doltcore/sqle/rowexec/lookup_join.go
  go/libraries/doltcore/sqle/rowexec/lookup_join_test.go
  go/store/prolly/tuple_range.go
Labels: correctness_approved

#8138 [auto-bump] [no-release-notes] dependency by max-hoffman
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8140 Continue to support writes when archives are in play
  go/store/nbs/archive_chunk_source.go
  integration-tests/bats/archive.bats
Labels: correctness_approved

#8141 support `STAGED` as commit hash
  go/libraries/doltcore/sqle/database.go
  go/libraries/doltcore/sqle/dtables/commit_diff_table.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_diff.go
  go/libraries/doltcore/sqle/history_table.go
  go/libraries/doltcore/sqle/index/dolt_index.go
Labels: correctness_approved

#8143 Add support for visualizing prolly tree and blob messages in `dolt show`
  go/store/prolly/tree/node.go
  go/store/types/serial_message.go
  integration-tests/bats/show.bats
Labels: correctness_approved

#8144 Don't panic when performing a GC on a shallow clone
  go/store/types/value.go
  go/store/types/value_store.go
  integration-tests/bats/shallow-clone.bats
Labels: correctness_approved

#8151 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8142 [no-release-notes] Fix issue where `dolt diff` fails to display changes to database schema if database name begins or ends with A, B, D, E, S, T, or _ (case sensitive)
  go/cmd/dolt/commands/diff.go
  integration-tests/bats/diff.bats
Labels: correctness_approved

#8152 Revive ability to read really old dolt_schema tables
  go/libraries/doltcore/sqle/database.go
  go/libraries/doltcore/sqle/schema_table.go
  go/libraries/doltcore/sqle/schema_table_test.go
  integration-tests/bats/helper/old_old_dolt_schemas/noms/4bujnjuatdli0klda7ucot0tl836jujt
  integration-tests/bats/helper/old_old_dolt_schemas/noms/63c0dojobm5j7arp99hiq78hj1rtp7m5
  integration-tests/bats/helper/old_old_dolt_schemas/noms/LOCK
  integration-tests/bats/helper/old_old_dolt_schemas/noms/aum9p7826iqaeq0pjtqlcn56hoj5nhht
  integration-tests/bats/helper/old_old_dolt_schemas/noms/chghnlvugtiui6khfo29cpfnfr3166qc
  integration-tests/bats/helper/old_old_dolt_schemas/noms/d0b8ibrrjvvv3f0mtd7hathtjq2vhig9
  integration-tests/bats/helper/old_old_dolt_schemas/noms/erturgf7to0f6r8prlbllflbshg5li4n
  integration-tests/bats/helper/old_old_dolt_schemas/noms/manifest
  integration-tests/bats/helper/old_old_dolt_schemas/noms/oik6v50p7q6as4t7qg7f1i06iomt9vn9
  integration-tests/bats/helper/old_old_dolt_schemas/noms/oktjimrpqi8m9dbpt3c7ikoaolhgtr2n
  integration-tests/bats/helper/old_old_dolt_schemas/noms/qe0mct6rf8puhdnqecm185p63dacaqrt
  integration-tests/bats/helper/old_old_dolt_schemas/noms/ro000svvgga0k7hatg7fta9j8ismtc3b
  integration-tests/bats/helper/old_old_dolt_schemas/noms/u9c6ttq6ddrgqdfbod9pg2vv79ab6crt
  integration-tests/bats/helper/old_old_dolt_schemas/repo_state.json
  integration-tests/bats/triggers.bats
Labels: correctness_approved

#8153 make tags case insensitive
  go/cmd/dolt/commands/sql.go
  go/libraries/doltcore/doltdb/doltdb.go
  go/libraries/doltcore/sqle/database_provider.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries.go
Labels: correctness_approved

#8155 Bug fix: loading persisted `@@server_id` from config.json
  go/libraries/doltcore/sqle/binlogreplication/binlog_replica_applier.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_replication_alltypes_test.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_replication_filters_test.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_replication_multidb_test.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_replication_reconnect_test.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_replication_restart_test.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_replication_test.go
Labels: correctness_approved

#8158 fix no-op merge msg in cli
  go/cmd/dolt/commands/merge.go
  go/libraries/doltcore/doltdb/errors.go
  integration-tests/bats/shallow-clone.bats
Labels: correctness_approved

#8150 fix warnings in dolt sql shell
  go/cmd/dolt/commands/sql.go
  integration-tests/bats/sql-shell-warnings.expect
  integration-tests/bats/sql-shell.bats
Labels: correctness_approved

#8160 [auto-bump] [no-release-notes] dependency by max-hoffman
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8154 When removing from a secondary index during merging, use the pre-merge ordinal mapping, not the merged mapping, to identify the secondary key to be removed.
  go/libraries/doltcore/merge/merge_prolly_rows.go
  go/libraries/doltcore/merge/mutable_secondary_index.go
  go/libraries/doltcore/merge/schema_merge_test.go
  go/libraries/doltcore/sqle/dprocedures/dolt_conflicts_resolve.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_merge.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_schema_merge.go
Labels: correctness_approved

#8162 Better error message when attempting to push from a shallow clone
  go/libraries/doltcore/env/actions/remotes.go
  go/store/nbs/generational_chunk_store.go
  integration-tests/bats/shallow-clone.bats
Labels: correctness_approved

#8124 [stats] limit stats boostrap to server start
  go/cmd/dolt/commands/sqlserver/server.go
  go/libraries/doltcore/sqle/system_variables.go
  integration-tests/bats/stats.bats
Labels: correctness_approved

#8166 [kvexec] Fix panic in non-covering strict lookup
  go/cmd/dolt/commands/engine/sqlengine.go
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/enginetest/dolt_harness.go
  go/libraries/doltcore/sqle/index/index_reader.go
  go/libraries/doltcore/sqle/index/secondary_iter.go
  go/libraries/doltcore/sqle/kvexec/builder.go
  go/libraries/doltcore/sqle/kvexec/lookup_join.go
  go/libraries/doltcore/sqle/kvexec/lookup_join_test.go
Labels: correctness_approved

#8139 Feature: Log binlog events to disk
  go/cmd/dolt/commands/engine/sqlengine.go
  go/cmd/dolt/commands/sqlserver/server.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_file_utils.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_position_store.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_primary_controller.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_primary_log_manager.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_primary_streamer.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_primary_test.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_producer.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_replica_applier.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_replication_alltypes_test.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_replication_filters_test.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_replication_multidb_test.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_replication_reconnect_test.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_replication_restart_test.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_replication_test.go
Labels: correctness_approved

#8171 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8164 archive guard rails
  go/cmd/dolt/commands/admin/archive.go
  go/cmd/dolt/commands/backup.go
  go/libraries/doltcore/env/environment.go
  go/libraries/doltcore/env/multi_repo_env.go
  go/libraries/doltcore/remotesrv/server.go
  go/libraries/doltcore/sqle/remotesrv.go
  go/store/nbs/archive_build.go
  go/store/nbs/archive_chunk_source.go
  go/store/nbs/archive_reader.go
  go/store/nbs/metadata.go
  integration-tests/bats/archive.bats
  integration-tests/bats/helper/local-remote.bash
Labels: correctness_approved

#8172 Reveal dolt archive command
  go/cmd/dolt/commands/admin/admin.go
  go/cmd/dolt/commands/archive.go
  go/cmd/dolt/dolt.go
  go/store/nbs/archive_build.go
  integration-tests/bats/archive.bats
Labels: correctness_approved

#8174 check for `pg_catalog` table when resolving a table
  go/libraries/doltcore/sqle/database.go
Labels: correctness_approved

#8175 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
  integration-tests/bats/types.bats
Labels: gms-bump, keep-alive, correctness_approved

#8137 Dolt index searchable, lookup caching
  go/go.mod
  go/go.sum
  go/libraries/doltcore/doltdb/root_val.go
  go/libraries/doltcore/sqle/dsess/session_cache.go
  go/libraries/doltcore/sqle/index/dolt_index.go
  go/libraries/doltcore/sqle/tables.go
  go/libraries/doltcore/sqle/writer/schema_cache.go
Labels: correctness_approved

#8180 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8181 Bug fix: resolving case-sensitive table name for TableEditor
  go/libraries/doltcore/sqle/binlogreplication/binlog_replica_applier.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_replication_test.go
Labels: correctness_approved
