Repository dolthub/dolt, pull requests merged in 2024-09, with the labels that each got.

#8309 Minor doc updates
  go/cmd/dolt/commands/cherry-pick.go
  go/cmd/dolt/commands/rebase.go
Labels: correctness_approved

#8313 Fixed table resolution for reset
  go/libraries/doltcore/env/actions/checkout.go
  go/libraries/doltcore/env/actions/reset.go
Labels: correctness_approved

#8319 reset auto increment counter on `dolt_reset('--hard')`
  go/libraries/doltcore/sqle/dprocedures/dolt_reset.go
  go/libraries/doltcore/sqle/dsess/autoincrement_tracker.go
  go/libraries/doltcore/sqle/dsess/session.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries.go
  go/libraries/doltcore/sqle/globalstate/auto_increment_tracker.go
Labels: correctness_approved

#8306 Export DoltSystemVariables var so that it can be used by doltgres
  go/libraries/doltcore/sqle/system_variables.go
Labels: correctness_approved

#8321 Optional String Argument
  go/libraries/utils/argparser/parser.go
  go/libraries/utils/argparser/parser_test.go
Labels: correctness_approved

#8329 [auto-bump] [no-release-notes] dependency by tbantle22
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8334 Fix issue where stats db created in wrong location
  go/libraries/doltcore/sqle/dprocedures/stats_funcs.go
  go/libraries/doltcore/sqle/statsnoms/database.go
  integration-tests/bats/stats.bats
Labels: correctness_approved

#8335 [statspro] Avoid stopping the world during stats updates
  go/libraries/doltcore/sqle/statsnoms/database.go
  go/libraries/doltcore/sqle/statspro/analyze.go
  go/libraries/doltcore/sqle/statspro/auto_refresh.go
  go/libraries/doltcore/sqle/statspro/stats_provider.go
Labels: correctness_approved

#8336 dolt add --patch
  go/cmd/dolt/cli/flags.go
  go/cmd/dolt/commands/add.go
  go/cmd/dolt/commands/stashcmds/stash.go
  go/cmd/dolt/commands/utils.go
  go/libraries/doltcore/sqle/dtables/workspace.go
Labels: correctness_approved

#8337 Fixup for dolt add --patch
  go/cmd/dolt/commands/add.go
Labels: correctness_approved

#8340 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8341 Fix more stats collection races
  go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
  go/libraries/doltcore/sqle/statsnoms/database.go
  go/libraries/doltcore/sqle/statspro/analyze.go
  go/libraries/doltcore/sqle/statspro/dolt_stats.go
Labels: correctness_approved

#8343 support for schemas in various version control operations
  go/cmd/dolt/commands/cvcmds/verify_constraints.go
  go/libraries/doltcore/diff/database_schema_deltas.go
  go/libraries/doltcore/doltdb/foreign_key_coll.go
  go/libraries/doltcore/doltdb/root_val.go
  go/libraries/doltcore/doltdb/table.go
  go/libraries/doltcore/doltdb/workingset.go
  go/libraries/doltcore/env/actions/commit.go
  go/libraries/doltcore/env/actions/reset.go
  go/libraries/doltcore/env/actions/staged.go
  go/libraries/doltcore/env/actions/table.go
  go/libraries/doltcore/merge/conflict_reader.go
  go/libraries/doltcore/merge/merge.go
  go/libraries/doltcore/merge/merge_noms_rows.go
  go/libraries/doltcore/merge/merge_prolly_indexes.go
  go/libraries/doltcore/merge/merge_prolly_rows.go
  go/libraries/doltcore/merge/merge_rows.go
  go/libraries/doltcore/merge/merge_schema.go
  go/libraries/doltcore/merge/merge_test.go
  go/libraries/doltcore/merge/schema_integration_test.go
  go/libraries/doltcore/merge/violations_fk.go
  go/libraries/doltcore/merge/violations_unique_prolly.go
  go/libraries/doltcore/sqle/alterschema_test.go
  go/libraries/doltcore/sqle/database_provider.go
  go/libraries/doltcore/sqle/dprocedures/dolt_conflicts_resolve.go
  go/libraries/doltcore/sqle/dprocedures/dolt_merge.go
  go/libraries/doltcore/sqle/dprocedures/dolt_verify_constraints.go
  go/libraries/doltcore/sqle/dsess/session.go
  go/libraries/doltcore/sqle/dtables/conflicts_tables.go
  go/libraries/doltcore/sqle/dtables/conflicts_tables_prolly.go
  go/libraries/doltcore/sqle/dtables/schema_conflicts_table.go
  go/libraries/doltcore/sqle/dtables/status_table.go
  go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
  go/libraries/doltcore/sqle/enginetest/dolt_engine_tests.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_create_database.go
  go/libraries/doltcore/sqle/sqlfmt/schema_fmt.go
  go/libraries/doltcore/table/editor/creation/external_build_index.go
  go/libraries/doltcore/table/editor/creation/index.go
  go/libraries/doltcore/table/untyped/sqlexport/batch_sqlwriter.go
  go/libraries/doltcore/table/untyped/sqlexport/sqlwriter.go
Labels: correctness_approved

#8349 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8352 Fix dolt_merge_base string validation for doltgres
  go/libraries/doltcore/sqle/dfunctions/dolt_merge_base.go
Labels: correctness_approved

#8348 Testing for dolt add --patch
  go/cmd/dolt/commands/add.go
  integration-tests/bats/add-patch-expect/all_none.expect
  integration-tests/bats/add-patch-expect/help_quit.expect
  integration-tests/bats/add-patch-expect/keyless.expect
  integration-tests/bats/add-patch-expect/no_then_a.expect
  integration-tests/bats/add-patch-expect/restart_multiple_times.expect
  integration-tests/bats/add-patch-expect/summary_updates.expect
  integration-tests/bats/add-patch-expect/yes_then_d.expect
  integration-tests/bats/add-patch.bats
  integration-tests/bats/helper/common_expect_functions.tcl
  integration-tests/bats/sql-shell-slash-cmds.expect
Labels: correctness_approved

#8355 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8350 [statspro] Restart drop db
  go/libraries/doltcore/sqle/statspro/configure.go
  go/libraries/doltcore/sqle/statspro/initdbhook.go
  go/libraries/doltcore/sqle/statspro/stats_provider.go
  integration-tests/bats/stats.bats
Labels: correctness_approved

#8359 More flexible `diff` printing when schema changes type of column
  go/cmd/dolt/commands/diff.go
  go/libraries/doltcore/diff/diffsplitter.go
  go/libraries/utils/argparser/parser.go
  integration-tests/bats/diff.bats
Labels: correctness_approved

#8305 Bh/signed commits
  go/cmd/dolt/cli/arg_parser_helpers.go
  go/cmd/dolt/cli/flags.go
  go/cmd/dolt/cli/stdio.go
  go/cmd/dolt/commands/cherry-pick.go
  go/cmd/dolt/commands/commit.go
  go/cmd/dolt/commands/log.go
  go/cmd/dolt/commands/merge.go
  go/cmd/dolt/commands/pull.go
  go/cmd/dolt/commands/revert.go
  go/cmd/dolt/commands/show.go
  go/cmd/dolt/commands/signed_commits_test.go
  go/cmd/dolt/commands/testdata/signed_commits/db/.dolt/config.json
  go/cmd/dolt/commands/testdata/signed_commits/db/.dolt/noms/LOCK
  go/cmd/dolt/commands/testdata/signed_commits/db/.dolt/noms/journal.idx
  go/cmd/dolt/commands/testdata/signed_commits/db/.dolt/noms/manifest
  go/cmd/dolt/commands/testdata/signed_commits/db/.dolt/noms/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
  go/cmd/dolt/commands/testdata/signed_commits/db/.dolt/repo_state.json
  go/cmd/dolt/commands/testdata/signed_commits/db/.dolt/stats/.dolt/config.json
  go/cmd/dolt/commands/testdata/signed_commits/db/.dolt/stats/.dolt/noms/LOCK
  go/cmd/dolt/commands/testdata/signed_commits/db/.dolt/stats/.dolt/noms/journal.idx
  go/cmd/dolt/commands/testdata/signed_commits/db/.dolt/stats/.dolt/noms/manifest
  go/cmd/dolt/commands/testdata/signed_commits/db/.dolt/stats/.dolt/noms/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
  go/cmd/dolt/commands/testdata/signed_commits/db/.dolt/stats/.dolt/repo_state.json
  go/cmd/dolt/commands/testdata/signed_commits/private.pgp
  go/cmd/dolt/commands/utils.go
  go/gen/fb/serial/commit.go
  go/go.mod
  go/go.sum
  go/go.work
  go/go.work.sum
  go/libraries/doltcore/env/config.go
  go/libraries/doltcore/sqle/dolt_log_table_function.go
  go/libraries/doltcore/sqle/dprocedures/dolt_commit.go
  go/libraries/doltcore/sqle/dsess/dolt_session_test.go
  go/libraries/doltcore/sqle/dsess/session.go
  go/libraries/doltcore/sqle/system_variables.go
  go/libraries/utils/config/keys.go
  go/libraries/utils/filesys/fs.go
  go/libraries/utils/gpg/sign.go
  go/libraries/utils/gpg/sign_test.go
  go/libraries/utils/gpg/testdata/private.pgp
  go/serial/commit.fbs
  go/store/datas/commit.go
  go/store/datas/commit_meta.go
  integration-tests/bats/private.pgp
  integration-tests/bats/signed.bats
  integration-tests/go-sql-server-driver/go.mod
  integration-tests/go-sql-server-driver/go.sum
Labels: correctness_approved

#8363 \edit support in `dolt sql` shell
  .github/workflows/ci-check-repo.yaml
  go/cmd/dolt/commands/commit.go
  go/cmd/dolt/commands/rebase.go
  go/cmd/dolt/commands/sql.go
  go/cmd/dolt/commands/sql_slash.go
  go/cmd/dolt/commands/utils.go
  go/libraries/utils/editor/edit.go
  go/libraries/utils/editor/edit_test.go
Labels: correctness_approved

#8361 [no-release-notes] more stats tests
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/enginetest/stats_queries.go
  go/libraries/doltcore/sqle/statsnoms/load.go
  go/libraries/doltcore/sqle/statsnoms/write.go
  go/libraries/doltcore/sqle/statspro/configure.go
Labels: correctness_approved

#8367 mark unscoped commit index as not unique
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/dtables/unscoped_diff_table.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_diff.go
  integration-tests/bats/diff.bats
Labels: correctness_approved

#8347 Bug fixes for schema names in reset operation
  go/libraries/doltcore/env/actions/reset.go
  go/libraries/doltcore/sqle/dprocedures/dolt_reset.go
Labels: correctness_approved

#8356 Compare strings with `strings.EqualFold`
  go/cmd/dolt/cli/command.go
  go/cmd/dolt/commands/assist.go
  go/cmd/dolt/commands/engine/sqlengine.go
  go/cmd/dolt/commands/show.go
  go/cmd/dolt/commands/utils.go
  go/libraries/doltcore/doltdb/commit_spec.go
  go/libraries/doltcore/doltdb/doltdb.go
  go/libraries/doltcore/doltdb/durable/index.go
  go/libraries/doltcore/doltdb/foreign_key_coll.go
  go/libraries/doltcore/doltdb/ignore.go
  go/libraries/doltcore/doltdb/root_val.go
  go/libraries/doltcore/doltdb/system_table.go
  go/libraries/doltcore/ref/ref.go
  go/libraries/doltcore/schema/check_coll.go
  go/libraries/doltcore/schema/col_coll.go
  go/libraries/doltcore/schema/index_coll.go
  go/libraries/doltcore/schema/schema.go
  go/libraries/doltcore/schema/schema_impl.go
  go/libraries/doltcore/sqle/alterschema.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_replica_applier.go
  go/libraries/doltcore/sqle/database.go
  go/libraries/doltcore/sqle/dfunctions/hashof.go
  go/libraries/doltcore/sqle/dolt_diff_table_function.go
  go/libraries/doltcore/sqle/dprocedures/dolt_branch.go
  go/libraries/doltcore/sqle/dropped_databases.go
  go/libraries/doltcore/sqle/dsess/session.go
  go/libraries/doltcore/sqle/dsess/transactions.go
  go/libraries/doltcore/sqle/enginetest/dolt_harness.go
  go/libraries/doltcore/sqle/reflog_table_function.go
  go/libraries/doltcore/sqle/schema_table.go
  go/libraries/doltcore/sqle/tables.go
  go/store/datas/pull/puller.go
Labels: contribution

#8315 update bind variable type
  go/cmd/dolt/cli/command.go
  go/cmd/dolt/commands/engine/sqlengine.go
  go/cmd/dolt/commands/sqlserver/queryist_utils.go
  go/go.mod
  go/go.sum
  go/go.work.sum
  go/libraries/doltcore/sqle/enginetest/dolt_queries.go
  go/libraries/doltcore/sqle/enginetest/prepared_queries.go
Labels: correctness_approved

#8370 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8372 Passing through schema name to fix index creation bug in Doltgres
  go/cmd/dolt/commands/schcmds/import.go
  go/libraries/doltcore/doltdb/root_val.go
  go/libraries/doltcore/mvdata/data_mover.go
  go/libraries/doltcore/mvdata/engine_table_reader.go
  go/libraries/doltcore/sqle/database.go
  go/libraries/doltcore/sqle/schema_override.go
  go/libraries/doltcore/sqle/sqlutil/convert.go
  go/libraries/doltcore/sqle/sqlutil/schema.go
  go/libraries/doltcore/sqle/tables.go
  go/libraries/doltcore/sqle/temp_table.go
Labels: correctness_approved

#8375 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8378 go: doltcore/remotestorage: reliable: Fix leaked goroutines when the context is canceled while reading the HTTP response.
  go/libraries/doltcore/remotestorage/internal/reliable/http.go
Labels: correctness_approved

#8376 Bug fixes for dolt_reset('table') in doltgres, plus dolt_constaint_vi…
  go/libraries/doltcore/env/actions/reset.go
  go/libraries/doltcore/sqle/dprocedures/dolt_reset.go
  go/libraries/doltcore/sqle/dtables/constraint_violations_prolly.go
Labels: correctness_approved

#8380 Fix `dolt_clean` and `dolt_checkout` for doltgres
  go/libraries/doltcore/env/actions/checkout.go
  go/libraries/doltcore/env/actions/reset.go
  go/libraries/doltcore/sqle/dprocedures/dolt_checkout.go
Labels: correctness_approved

#8379 Stats safer encode
  go/libraries/doltcore/sqle/enginetest/stats_queries.go
  go/libraries/doltcore/sqle/statsnoms/load.go
  go/libraries/doltcore/sqle/statsnoms/write.go
  go/libraries/doltcore/sqle/statspro/dolt_stats.go
  go/libraries/doltcore/sqle/statspro/update.go
  integration-tests/bats/stats.bats
Labels: correctness_approved

#8381 Fix diff related table functions for doltgres
  go/libraries/doltcore/sqle/dolt_diff_stat_table_function.go
  go/libraries/doltcore/sqle/dolt_patch_table_function.go
  go/libraries/doltcore/sqle/dolt_schema_diff_table_function.go
  go/libraries/doltcore/sqle/dtables/commit_diff_table.go
Labels: correctness_approved

#8382 Improve Error Handling for Tags
  go/libraries/doltcore/env/actions/branch.go
  go/libraries/doltcore/env/actions/clone.go
  go/libraries/doltcore/env/actions/workspace.go
  go/libraries/doltcore/sqle/dprocedures/dolt_checkout.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries.go
  integration-tests/bats/commit_tags.bats
Labels: correctness_approved

#8390 doltgres fixes for constraint violation tables
  go/libraries/doltcore/doltdb/root_val.go
  go/libraries/doltcore/env/actions/commit.go
  go/libraries/doltcore/merge/merge.go
  go/libraries/doltcore/sqle/dsess/transactions.go
  go/libraries/doltcore/sqle/dtables/constraint_violations_prolly.go
  go/libraries/doltcore/sqle/dtables/merge_status_table.go
  go/libraries/doltcore/sqle/dtables/status_table.go
  go/libraries/doltcore/sqle/dtables/table_of_tables_with_violations.go
Labels: correctness_approved

#8391 Return information_schema schema for doltgres
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/database.go
  go/libraries/doltcore/sqle/index/dolt_index.go
  go/libraries/doltcore/sqle/information_schema_database_schema.go
Labels: correctness_approved

#8398 Add pointer for dolt_docs schema so it can be replaced by doltgres
  go/libraries/doltcore/doltdb/system_table.go
  go/libraries/doltcore/sqle/dtables/docs_table.go
  integration-tests/mysql-client-tests/node/workbenchTests/docs.js
Labels: correctness_approved

#8399 Use the a type comparator for merge, not the generic comparator
  go/libraries/doltcore/merge/merge_prolly_rows.go
  go/libraries/doltcore/merge/schema_merge_test.go
  go/libraries/doltcore/sqle/dtables/conflicts_tables_prolly.go
  go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
  go/libraries/doltcore/sqle/enginetest/dolt_engine_tests.go
  go/store/prolly/tree/node.go
Labels: correctness_approved

#8401 Fix dolt_schemas for doltgres
  go/libraries/doltcore/sqle/database.go
Labels: correctness_approved

#8400 perf test for proj refactor
  .github/scripts/performance-benchmarking/validate-commentor.sh
  go/go.mod
  go/go.sum
Labels: correctness_approved

#8403 Fix dolt_docs for doltgres
  go/libraries/doltcore/sqle/database.go
Labels: correctness_approved

#8402 More TableName fixes for system tables / related methods
  go/cmd/dolt/commands/reset.go
  go/libraries/doltcore/doltdb/root_val.go
  go/libraries/doltcore/doltdb/system_table.go
  go/libraries/doltcore/env/actions/commit.go
  go/libraries/doltcore/env/actions/errors.go
  go/libraries/doltcore/env/actions/staged.go
  go/libraries/doltcore/env/actions/table.go
  go/libraries/doltcore/merge/merge.go
  go/libraries/doltcore/sqle/dprocedures/dolt_add.go
  go/libraries/doltcore/sqle/dprocedures/dolt_rebase.go
  go/libraries/doltcore/sqle/dtables/merge_status_table.go
  go/libraries/doltcore/sqle/dtables/status_table.go
  go/libraries/doltcore/sqle/dtables/table_of_tables_in_conflict.go
Labels: correctness_approved
