Repository dolthub/dolt, pull requests merged in 2024-12, with the labels that each got.

#8620 [auto-bump] [no-release-notes] dependency by jennifersp
  go/go.mod
  go/go.sum
  integration-tests/bats/import-update-tables.bats
Labels: gms-bump, correctness_approved

#8626 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8627 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8634 Add pointers for schemas for `dolt_workspace_*` and `dolt_diff` system tables for doltgres
  go/libraries/doltcore/sqle/dtables/unscoped_diff_table.go
  go/libraries/doltcore/sqle/dtables/workspace_table.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_workspace.go
Labels: correctness_approved

#8632 fix error message for duplicate unique key violation on out of band types
  go/libraries/doltcore/sqle/enginetest/dolt_queries.go
  go/libraries/doltcore/sqle/writer/prolly_index_writer.go
  go/libraries/doltcore/sqle/writer/prolly_index_writer_keyless.go
  go/store/val/tuple_descriptor.go
Labels: correctness_approved

#8630 Fixed issues with branch control
  go/libraries/doltcore/branch_control/access.go
  go/libraries/doltcore/branch_control/namespace.go
  go/libraries/doltcore/sqle/dtables/branch_control_table.go
  integration-tests/bats/branch-control.bats
  integration-tests/bats/helper/query-server-common.bash
Labels: correctness_approved

#8624 Update sql status to not report changes for unstaged tables that have changed but not visibly.
  go/libraries/doltcore/diff/table_deltas.go
  go/libraries/doltcore/sqle/dtables/status_table.go
  integration-tests/bats/sql-status.bats
  integration-tests/bats/status.bats
Labels: correctness_approved

#8638 go: doltcore: diff: table_deltas.go: Fix perf regression in dolt_add, dolt_commit.
  go/libraries/doltcore/diff/table_deltas.go
Labels: correctness_approved

#8636 Schema fixes for `dolt_status`, `dolt_merge_status`, and `dolt_constraint_violations_*` tables for doltgres
  go/libraries/doltcore/doltdb/table.go
  go/libraries/doltcore/merge/violations_prolly.go
  go/libraries/doltcore/sqle/dtables/constraint_violations.go
  go/libraries/doltcore/sqle/dtables/constraint_violations_prolly.go
  go/libraries/doltcore/sqle/dtables/merge_status_table.go
  go/libraries/doltcore/sqle/dtables/status_table.go
  go/libraries/doltcore/sqle/dtables/workspace_table.go
Labels: correctness_approved

#8641 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8639 Fix for updated issue 8623
  go/libraries/doltcore/branch_control/branch_control.go
  integration-tests/bats/branch-control.bats
Labels: correctness_approved

#8646 Allow importing parquet files with arbitrary root column names.
  go/libraries/doltcore/table/typed/parquet/reader.go
  integration-tests/bats/helper/parquet/strings.parquet
  integration-tests/bats/helper/parquet/strings.sql
  integration-tests/bats/import-create-tables.bats
Labels: correctness_approved

#8628 [no-release-notes] /{.github,go,integration-tests}: bump go
  .github/workflows/cd-release-pgo.yaml
  go/go.mod
  go/go.work
  go/performance/continuous_integration/SysbenchDockerfile
  integration-tests/DataDumpLoadDockerfile
  integration-tests/MySQLDockerfile
  integration-tests/ORMDockerfile
  integration-tests/go-sql-server-driver/go.mod
Labels: correctness_approved

#8648 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/enginetest/dolt_queries.go
  integration-tests/bats/helper/index-on-writes-common.bash
  integration-tests/bats/sql-server.bats
Labels: gms-bump, keep-alive, correctness_approved

#8645 Removed persitence behavior from config
  go/cmd/dolt/commands/sqlserver/command_line_config.go
  go/cmd/dolt/commands/sqlserver/server.go
  go/cmd/dolt/commands/sqlserver/sqlserver.go
  go/libraries/doltcore/servercfg/serverconfig.go
  go/libraries/doltcore/servercfg/testdata/minver_validation.txt
  go/libraries/doltcore/servercfg/yaml_config.go
  go/libraries/doltcore/servercfg/yaml_config_test.go
  integration-tests/go-sql-server-driver/tests/sql-server-config.yaml
Labels: correctness_approved

#8643 Support for schema names in table renames
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/alterschema.go
  go/libraries/doltcore/sqle/alterschema_test.go
  go/libraries/doltcore/sqle/database.go
  go/libraries/doltcore/sqle/enginetest/dolt_engine_tests.go
  go/libraries/doltcore/sqle/enginetest/dolt_harness.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_merge.go
Labels: correctness_approved

#8653 Bug fix: replication fails when a branch is deleted and tag with same name is created
  go/libraries/doltcore/sqle/read_replica_database.go
  integration-tests/bats/replication.bats
Labels: correctness_approved

#8654 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8655 Removed the `performance` server config block
  go/cmd/dolt/commands/sqlserver/command_line_config.go
  go/libraries/doltcore/servercfg/serverconfig.go
  go/libraries/doltcore/servercfg/testdata/minver_validation.txt
  go/libraries/doltcore/servercfg/yaml_config.go
Labels: correctness_approved

#8651 [no-release-notes] skip more wire allocs
  go/cmd/dolt/commands/query_diff.go
  go/go.mod
  go/go.sum
Labels: correctness_approved

#8664 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8650 Enable larger statements for dolt_procedures
  go/libraries/doltcore/sqle/enginetest/dolt_procedure_queries.go
  go/libraries/doltcore/sqle/procedures_table.go
Labels: correctness_approved

#8675 chore: use errors.New to replace fmt.Errorf with no parameters
  go/cmd/dolt/dolt.go
Labels: contribution

#8673 fix panic for virtual columns in `dolt_diff_<tbl>`
  go/libraries/doltcore/schema/schema.go
  go/libraries/doltcore/schema/schema_test.go
  go/libraries/doltcore/sqle/dtables/prolly_row_conv.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_diff.go
Labels: correctness_approved

#8676 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8674 [stats] persist schema hashes for purging
  go/gen/fb/serial/fileidentifiers.go
  go/gen/fb/serial/tuple.go
  go/libraries/doltcore/doltdb/doltdb.go
  go/libraries/doltcore/doltdb/errors.go
  go/libraries/doltcore/doltdb/hooksdatabase.go
  go/libraries/doltcore/ref/ref.go
  go/libraries/doltcore/ref/tuple_ref.go
  go/libraries/doltcore/sqle/statsnoms/database.go
  go/libraries/doltcore/sqle/statspro/analyze.go
  go/libraries/doltcore/sqle/statspro/auto_refresh.go
  go/libraries/doltcore/sqle/statspro/configure.go
  go/libraries/doltcore/sqle/statspro/initdbhook.go
  go/libraries/doltcore/sqle/statspro/interface.go
  go/serial/fileidentifiers.go
  go/serial/generate.sh
  go/serial/tuple.fbs
  go/store/datas/database.go
  go/store/datas/database_common.go
  go/store/datas/dataset.go
  go/store/datas/tuple.go
  integration-tests/bats/stats.bats
Labels: correctness_approved

#8679 [auto-bump] [no-release-notes] dependency by max-hoffman
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8677 parse user vars as `interface{}` instead of always `string`
  go/cmd/dolt/commands/sqlserver/server.go
  go/libraries/doltcore/servercfg/testdata/minver_validation.txt
  go/libraries/doltcore/servercfg/yaml_config.go
  go/libraries/doltcore/servercfg/yaml_config_test.go
  integration-tests/bats/sql-server.bats
Labels: correctness_approved

#8680 fix: panic on null metrics port
  go/libraries/doltcore/servercfg/yaml_config.go
  go/libraries/doltcore/servercfg/yaml_config_test.go
Labels: correctness_approved

#8681 Bump for go-icu-regex
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8685 update TableFunction
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/database_provider.go
  go/libraries/doltcore/sqle/dtablefunctions/dolt_log_table_function.go
Labels: correctness_approved

#8631 Give a little more information in dolt_diff_* when there is a pk change
  go/libraries/doltcore/sqle/dtables/commit_diff_table.go
  go/libraries/doltcore/sqle/dtables/diff_table.go
  go/libraries/doltcore/sqle/dtables/prolly_row_conv.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_diff.go
  integration-tests/bats/sql-diff.bats
Labels: minor version bump, correctness_approved

#8605 [no-release-notes] Refactor NewEmptyIndex to avoid adding parameters for keyless and vector indexes
  go/cmd/dolt/commands/schcmds/import.go
  go/libraries/doltcore/doltdb/commit_hooks_test.go
  go/libraries/doltcore/doltdb/doltdb_test.go
  go/libraries/doltcore/doltdb/durable/index.go
  go/libraries/doltcore/doltdb/root_val.go
  go/libraries/doltcore/doltdb/table.go
  go/libraries/doltcore/dtestutils/testcommands/multienv.go
  go/libraries/doltcore/merge/fulltext_rebuild.go
  go/libraries/doltcore/merge/violations_fk.go
  go/libraries/doltcore/sqle/alterschema_test.go
  go/libraries/doltcore/sqle/common_test.go
  go/libraries/doltcore/sqle/dtables/conflicts_tables_prolly.go
  go/libraries/doltcore/sqle/dtables/diff_table.go
  go/libraries/doltcore/sqle/tables.go
  go/libraries/doltcore/sqle/temp_table.go
  go/libraries/doltcore/sqle/testutil.go
  go/libraries/doltcore/table/editor/creation/external_build_index.go
  go/libraries/doltcore/table/editor/creation/index.go
  go/libraries/doltcore/table/untyped/sqlexport/sqlwriter_test.go
Labels: correctness_approved

#8692 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8694 [auto-bump] [no-release-notes] dependency by max-hoffman
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8693 [no-release-notes] write buf reuse bump
  go/go.mod
  go/go.sum
  go/performance/microsysbench/sysbench_test.go
  go/store/val/tuple.go
Labels: correctness_approved

#8684 [stats] stats table name sensitivity tests
  go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
  go/libraries/doltcore/sqle/enginetest/dolt_engine_tests.go
  go/libraries/doltcore/sqle/enginetest/stats_queries.go
  go/libraries/doltcore/sqle/statsnoms/database.go
  go/libraries/doltcore/sqle/statsnoms/load.go
  go/libraries/doltcore/sqle/statspro/analyze.go
  go/libraries/doltcore/sqle/statspro/auto_refresh.go
  go/libraries/doltcore/sqle/statspro/initdbhook.go
  go/libraries/doltcore/sqle/statspro/interface.go
  go/libraries/doltcore/sqle/statspro/stats_provider.go
  go/libraries/doltcore/sqle/system_variables.go
  go/store/val/tuple.go
Labels: correctness_approved

#8699 [sqle] Fix diff table merge join bugs
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/enginetest/dolt_engine_tests.go
  go/libraries/doltcore/sqle/enginetest/dolt_harness.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_diff.go
  go/libraries/doltcore/sqle/index/dolt_index.go
  go/libraries/doltcore/sqle/kvexec/builder.go
Labels: correctness_approved

#8698 Replace `cespare/xxhash` with `cespare/xxhash/v2`
  go/go.mod
  go/go.sum
  go/performance/import_benchmarker/testdef.go
Labels: contribution

#8702 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, keep-alive, correctness_approved

#8704 [auto-bump] [no-release-notes] dependency by tbantle22
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8707 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved
