Repository dolthub/dolt, pull requests merged in 2024-05, with the labels that each got.

#7785 Use `LazyJSONDocument` when reading from a JSON column.
  go/go.mod
  go/go.sum
  go/libraries/doltcore/merge/merge_prolly_rows.go
  go/libraries/doltcore/merge/violations_fk_prolly.go
  go/libraries/doltcore/merge/violations_unique_prolly.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_replication_alltypes_test.go
  go/libraries/doltcore/sqle/json/noms_json_value.go
  go/libraries/doltcore/sqle/schema_table.go
  go/libraries/doltcore/sqle/schema_table_test.go
  go/libraries/doltcore/sqle/statspro/dolt_stats.go
  go/libraries/doltcore/table/typed/json/writer.go
  go/store/prolly/tree/blob_builder.go
  go/store/prolly/tree/prolly_fields.go
  go/store/prolly/tree/prolly_fields_test.go
  go/store/types/json.go
  go/store/types/json_test.go
  integration-tests/bats/constraint-violations.bats
  integration-tests/bats/json-new-fmt.bats
  integration-tests/bats/json.bats
Labels: correctness_approved

#7794 [no-release-notes] fix bats test error
  go/go.mod
  go/go.sum
  integration-tests/bats/primary-key-changes.bats
Labels: correctness_approved

#7795 Serialization code for binlog events
  go/libraries/doltcore/sqle/binlogreplication/binlog_json_serialization.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_json_serialization_test.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_row_serialization.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_type_serialization.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_type_serialization_test.go
Labels: correctness_approved

#7805 Fix: allow `jsonSerializer` to load JSON from `LazyJSONDocument`
  go/libraries/doltcore/sqle/binlogreplication/binlog_type_serialization.go
Labels: correctness_approved

#7807 [auto-bump] [no-release-notes] dependency by nicktobey
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#7809 go/libraries/doltcore/sqle/dprocedures: dolt_pull.go: Improve CPU utilization of call dolt_pull.
  go/libraries/doltcore/sqle/dprocedures/dolt_pull.go
Labels: correctness_approved

#7754 Index rebuilds with external key sorting
  go/libraries/doltcore/schema/collation_comparator.go
  go/libraries/doltcore/table/editor/creation/external_build_index.go
  go/libraries/doltcore/table/editor/creation/index.go
  go/store/prolly/sort/external.go
  go/store/prolly/sort/external_test.go
Labels: correctness_approved

#7818 Apply a factor to better estimate `information_schema.TABLES.DATA_LENGTH`
  go/libraries/doltcore/sqle/dtables/statistics_table.go
Labels: correctness_approved

#7806 [no-release-notes] redo how to set tpc-c testing statistics
  go/performance/utils/benchmark_runner/dolt_tpcc.go
  go/performance/utils/benchmark_runner/tpcc.go
Labels: correctness_approved

#7816 allow database alters and case insensitive check for info schema
  go/cmd/dolt/commands/sql.go
  go/libraries/doltcore/sqle/database_provider.go
  integration-tests/bats/sql-create-database.bats
Labels: correctness_approved

#7825 Bug fix: Decimal type binlog serialization
  go/libraries/doltcore/sqle/binlogreplication/binlog_type_serialization.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_type_serialization_test.go
Labels: correctness_approved

#7827 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#7828 Bug fix: Allow `dolt init` to use `--data-dir` param
  go/cmd/dolt/commands/config.go
  go/cmd/dolt/commands/config_test.go
  go/libraries/doltcore/env/config.go
  go/libraries/doltcore/env/environment.go
  go/libraries/doltcore/env/environment_test.go
  integration-tests/bats/init.bats
Labels: correctness_approved

#7824 go/libraries/doltcore/remotestorage,go/store/datas/pull: Implement a pipelined chunk fetcher.
  go/Godeps/LICENSES
  go/go.mod
  go/go.sum
  go/libraries/doltcore/remotestorage/chunk_fetcher.go
  go/libraries/doltcore/remotestorage/chunk_fetcher_test.go
  go/libraries/doltcore/remotestorage/chunk_store.go
  go/libraries/doltcore/remotestorage/concurrency.go
  go/libraries/doltcore/remotestorage/concurrency_test.go
  go/libraries/doltcore/remotestorage/hedge.go
  go/libraries/doltcore/remotestorage/hedge_test.go
  go/libraries/doltcore/remotestorage/internal/circular/buff.go
  go/libraries/doltcore/remotestorage/internal/circular/buff_test.go
  go/libraries/doltcore/remotestorage/internal/pool/pool.go
  go/libraries/doltcore/remotestorage/internal/pool/pool_test.go
  go/libraries/doltcore/remotestorage/internal/ranges/ranges.go
  go/libraries/doltcore/remotestorage/internal/ranges/ranges_test.go
  go/libraries/doltcore/remotestorage/internal/reliable/chan.go
  go/libraries/doltcore/remotestorage/internal/reliable/chan_test.go
  go/libraries/doltcore/remotestorage/internal/reliable/grpc.go
  go/libraries/doltcore/remotestorage/internal/reliable/grpc_state_machine_struct.go
  go/libraries/doltcore/remotestorage/internal/reliable/grpc_test.go
  go/libraries/doltcore/remotestorage/internal/reliable/http.go
  go/libraries/doltcore/remotestorage/internal/reliable/http_test.go
  go/libraries/doltcore/remotestorage/internal/reliable/timeout_controller.go
  go/libraries/doltcore/remotestorage/internal/reliable/timeout_controller_test.go
  go/libraries/doltcore/remotestorage/stats.go
  go/store/datas/pull/pull_chunk_fetcher.go
  go/store/datas/pull/pull_chunk_tracker.go
  go/store/datas/pull/pull_table_file_writer.go
  go/store/datas/pull/puller.go
  go/store/nbs/chunk_fetcher.go
Labels: correctness_approved

#7833 Bug fix: Apply replication settings for newly cloned databases
  go/libraries/doltcore/sqle/database_provider.go
  go/libraries/doltcore/sqle/read_replica_database.go
  go/libraries/doltcore/sqle/replication.go
  integration-tests/bats/replication-multidb.bats
Labels: correctness_approved

#7780 Reformat journal index
  go/store/nbs/journal_index_record.go
  go/store/nbs/journal_index_record_test.go
  go/store/nbs/journal_record.go
  go/store/nbs/journal_writer.go
  go/store/nbs/journal_writer_test.go
Labels: correctness_approved

#7834 minver refactor to be used by doltgres
  go/cmd/dolt/commands/sqlserver/minver_test.go
  go/libraries/utils/minver/minver.go
  go/libraries/utils/minver/minver_test.go
  go/libraries/utils/minver/minvertesting.go
  go/utils/genminver_validation/main.go
Labels: correctness_approved

#7821 Prevent panic when dropping columns in schema merge
  go/libraries/doltcore/merge/merge_prolly_rows.go
  go/libraries/doltcore/merge/merge_schema.go
  go/libraries/doltcore/merge/schema_merge_test.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_schema_merge.go
  go/store/prolly/tree/node.go
Labels: correctness_approved

#7819 use parser interface in engine
  go/cmd/dolt/commands/dump.go
  go/go.mod
  go/go.sum
  go/libraries/doltcore/mvdata/engine_table_reader.go
  go/libraries/doltcore/mvdata/engine_table_writer.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_replica_applier.go
  go/libraries/doltcore/sqle/database.go
  go/libraries/doltcore/sqle/enginetest/dolt_branch_queries.go
  go/libraries/doltcore/sqle/enginetest/testgen_test.go
  go/libraries/doltcore/sqle/index/key_builder.go
  go/libraries/doltcore/sqle/index/mergeable_indexes_test.go
  go/libraries/doltcore/sqle/sqlutil/schema.go
  go/libraries/doltcore/sqle/statsnoms/iter.go
Labels: correctness_approved

#7803 Avoid escaping HTML characters when displaying them to the user.
  go/libraries/doltcore/table/typed/json/writer.go
  integration-tests/bats/json.bats
  integration-tests/bats/sql-shell.bats
Labels: correctness_approved

#7823 handle database charset/collation changes
  go/cmd/dolt/cli/arg_parser_helpers.go
  go/cmd/dolt/commands/diff.go
  go/cmd/dolt/commands/merge.go
  go/libraries/doltcore/diff/table_deltas.go
  go/libraries/doltcore/env/actions/staged.go
  go/libraries/doltcore/merge/merge.go
  go/libraries/doltcore/sqle/database.go
  go/libraries/doltcore/sqle/dolt_diff_summary_table_function.go
  go/libraries/doltcore/sqle/dolt_patch_table_function.go
  go/libraries/doltcore/sqle/dolt_schema_diff_table_function.go
  go/libraries/doltcore/sqle/dprocedures/dolt_add.go
  go/libraries/doltcore/sqle/dprocedures/dolt_commit.go
  go/libraries/doltcore/sqle/dsess/session.go
  go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_diff.go
  go/libraries/doltcore/sqle/sqlfmt/schema_fmt.go
  integration-tests/bats/diff.bats
  integration-tests/bats/merge.bats
  integration-tests/bats/status.bats
Labels: minor version bump, correctness_approved

#7844 [auto-bump] [no-release-notes] dependency by max-hoffman
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#7852 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
  integration-tests/bats/helper/query-server-common.bash
  integration-tests/bats/sql-privs.bats
  integration-tests/bats/sql-server.bats
  integration-tests/go-sql-server-driver/tests/sql-server-cluster-users-and-grants.yaml
Labels: gms-bump, keep-alive, correctness_approved

#7848 Added additional function to RootValue
  go/libraries/doltcore/doltdb/root_val.go
  go/libraries/doltcore/merge/merge.go
Labels: correctness_approved

#7861 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#7846 [dsess] session trigger cache
  go/libraries/doltcore/sqle/database.go
  go/libraries/doltcore/sqle/dsess/session_cache.go
Labels: correctness_approved

#7858 [nbs] safer peek root hash record
  go/store/nbs/journal_record.go
Labels: correctness_approved

#7862 Bug fix: `sql-server` should initialize persisted global vars
  go/cmd/dolt/commands/sqlserver/server.go
  go/cmd/dolt/commands/sqlserver/sqlserver.go
  integration-tests/bats/sql-server.bats
Labels: correctness_approved

#7860 Bug fix: load local config when using `--data-dir`
  go/cmd/dolt/dolt.go
  integration-tests/bats/global-args.bats
Labels: correctness_approved

#7864 move config
  go/cmd/dolt/commands/engine/jwtplugin.go
  go/cmd/dolt/commands/engine/jwtplugin_test.go
  go/cmd/dolt/commands/engine/sqlengine.go
  go/cmd/dolt/commands/sqlserver/command_line_config.go
  go/cmd/dolt/commands/sqlserver/queryist_utils.go
  go/cmd/dolt/commands/sqlserver/server.go
  go/cmd/dolt/commands/sqlserver/server_test.go
  go/cmd/dolt/commands/sqlserver/sqlserver.go
  go/libraries/doltcore/servercfg/minver_test.go
  go/libraries/doltcore/servercfg/serverconfig.go
  go/libraries/doltcore/servercfg/testdata/chain_cert.pem
  go/libraries/doltcore/servercfg/testdata/chain_key.pem
  go/libraries/doltcore/servercfg/testdata/minver_validation.txt
  go/libraries/doltcore/servercfg/testdata/selfsigned_cert.pem
  go/libraries/doltcore/servercfg/testdata/selfsigned_key.pem
  go/libraries/doltcore/servercfg/yaml_config.go
  go/libraries/doltcore/servercfg/yaml_config_test.go
  go/libraries/doltcore/sqle/cluster/config.go
  go/libraries/doltcore/sqle/cluster/controller.go
  go/libraries/doltcore/sqle/enginetest/dolt_server_test.go
  go/libraries/utils/minver/minvertesting.go
  go/performance/replicationbench/async_replica_test.go
  go/performance/replicationbench/replica_test.go
  go/performance/serverbench/bench_test.go
  go/utils/genminver_validation/main.go
  integration-tests/bats/helper/query-server-common.bash
Labels: correctness_approved

#7865 [no-release-notes] fix unit test
  go/go.mod
  go/go.sum
  go/libraries/doltcore/schema/typeinfo/decimal_test.go
Labels: correctness_approved

#7869 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#7871 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#7876 Improve error messages for CLI commands when a sql-server is running
  go/cmd/dolt/cli/command.go
  go/cmd/dolt/commands/init.go
  go/libraries/doltcore/env/environment.go
  integration-tests/bats/sql-server.bats
Labels: correctness_approved

#7877 keep `sql.Schema` for conflicts table schema
  go/cmd/dolt/commands/cnfcmds/cat.go
  integration-tests/bats/conflict-cat.bats
  integration-tests/bats/performance-repo/.dolt/noms/journal.idx
Labels: correctness_approved

#7879 avoid `NewEmptyIndex` when table does not exist
  go/libraries/doltcore/diff/diff_stat.go
  go/libraries/doltcore/diff/table_deltas.go
Labels: correctness_approved

#7880 Migrate `dolt remote` to SQL
  go/cmd/dolt/commands/remote.go
  go/cmd/dolt/dolt.go
  integration-tests/bats/remote-cmd.bats
  integration-tests/bats/remotes-file-system.bats
Labels: correctness_approved

#7881 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#7870 go/utils/publishrelease: Bump MUSL toolchains used for cutting releases.
  go/Godeps/LICENSES
  go/utils/3pdeps/MIMALLOC_LICENSE
  go/utils/3pdeps/main.go
  go/utils/publishrelease/buildpgobinaries.sh
Labels: correctness_approved

#7883 [auto-bump] [no-release-notes] dependency by Hydrocharged
  go/go.mod
  go/go.sum
Labels: gms-bump

#7882 Bug fix: no-op `dolt_pull()` was leaving working set dirty
  go/libraries/doltcore/sqle/dprocedures/dolt_pull.go
  integration-tests/bats/sql-pull.bats
Labels: correctness_approved

#7859 Cache table and schema indexes on schema address
  go/cmd/dolt/commands/engine/sqlengine.go
  go/cmd/dolt/commands/filter-branch.go
  go/libraries/doltcore/doltdb/durable/index.go
  go/libraries/doltcore/doltdb/root_val.go
  go/libraries/doltcore/doltdb/table.go
  go/libraries/doltcore/merge/merge_prolly_indexes.go
  go/libraries/doltcore/merge/merge_prolly_rows.go
  go/libraries/doltcore/merge/mutable_secondary_index.go
  go/libraries/doltcore/merge/schema_merge_test.go
  go/libraries/doltcore/migrate/transform.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_replica_applier.go
  go/libraries/doltcore/sqle/database.go
  go/libraries/doltcore/sqle/dsess/autoincrement_tracker.go
  go/libraries/doltcore/sqle/dsess/database_session_state.go
  go/libraries/doltcore/sqle/dsess/dolt_session_test.go
  go/libraries/doltcore/sqle/dsess/session.go
  go/libraries/doltcore/sqle/dsess/session_cache.go
  go/libraries/doltcore/sqle/dsess/table_writer.go
  go/libraries/doltcore/sqle/dtables/docs_table.go
  go/libraries/doltcore/sqle/dtables/ignore_table.go
  go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
  go/libraries/doltcore/sqle/enginetest/dolt_harness.go
  go/libraries/doltcore/sqle/enginetest/validation.go
  go/libraries/doltcore/sqle/enginetest/versioned_queries.go
  go/libraries/doltcore/sqle/show_create_table.go
  go/libraries/doltcore/sqle/sqlddl_test.go
  go/libraries/doltcore/sqle/tables.go
  go/libraries/doltcore/sqle/temp_table.go
  go/libraries/doltcore/sqle/testutil.go
  go/libraries/doltcore/sqle/writer/noms_table_writer.go
  go/libraries/doltcore/sqle/writer/noms_table_writer_test.go
  go/libraries/doltcore/sqle/writer/noms_write_session.go
  go/libraries/doltcore/sqle/writer/prolly_index_writer.go
  go/libraries/doltcore/sqle/writer/prolly_table_writer.go
  go/libraries/doltcore/sqle/writer/prolly_write_session.go
  go/libraries/doltcore/sqle/writer/schema_cache.go
Labels: correctness_approved

#7884 [tree] return blob builders to pool after use
  go/libraries/doltcore/migrate/tuples.go
  go/store/prolly/tree/blob_builder.go
  go/store/prolly/tree/node_store.go
  go/store/prolly/tree/prolly_fields.go
  go/store/prolly/tree/testutils.go
Labels: correctness_approved

#7872 Various test utils and small fixes
  go/go.mod
  go/libraries/doltcore/sqle/binlogreplication/binlog_replica_controller.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_replication_reconnect_test.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_replication_restart_test.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_replication_test.go
  go/libraries/doltcore/sqle/dolt_patch_table_function.go
  go/libraries/doltcore/sqle/dsess/session.go
  go/store/val/tuple_descriptor.go
  integration-tests/go-sql-server-driver/go.mod
Labels: correctness_approved

#7878 Move sql patch statement generation APIs to the `sqlfmt` package
  .github/workflows/ci-bats-unix.yaml
  go/libraries/doltcore/diff/async_differ_test.go
  go/libraries/doltcore/diff/table_deltas.go
  go/libraries/doltcore/merge/merge_prolly_rows.go
  go/libraries/doltcore/sqle/dolt_patch_table_function.go
  go/libraries/doltcore/sqle/expranalysis/expranalysis.go
  go/libraries/doltcore/sqle/index/key_builder.go
  go/libraries/doltcore/sqle/sqlfmt/schema_fmt.go
  go/libraries/doltcore/table/untyped/sqlexport/sql_diff_writer.go
Labels: correctness_approved

#7893 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/enginetest/dolt_server_test.go
Labels: gms-bump, keep-alive, correctness_approved

#7896 [auto-bump] [no-release-notes] dependency by max-hoffman
  go/go.mod
  go/go.sum
Labels: gms-bump

#7895 prevent `filter-branch` when there are local changes
  go/cmd/dolt/commands/filter-branch.go
  go/cmd/dolt/commands/utils.go
  integration-tests/bats/filter-branch.bats
Labels: correctness_approved

#7888 [sort] index build streams sorted edits
  go/libraries/doltcore/table/editor/creation/external_build_index.go
  go/store/prolly/sort/external.go
Labels: correctness_approved

#7903 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#7900 prevent dolt filter branch when it would overwrite unchecked branch's working set
  go/cmd/dolt/commands/filter-branch.go
  go/cmd/dolt/commands/utils.go
  go/libraries/doltcore/rebase/filter_branch.go
  integration-tests/bats/filter-branch.bats
Labels: correctness_approved

#7922 [writer] skip more deserialization steps in getTableWriter
  go/libraries/doltcore/doltdb/durable/table.go
  go/libraries/doltcore/doltdb/table.go
  go/libraries/doltcore/sqle/dsess/table_writer.go
  go/libraries/doltcore/sqle/writer/prolly_index_writer.go
  go/libraries/doltcore/sqle/writer/prolly_table_writer.go
  go/libraries/doltcore/sqle/writer/schema_cache.go
  go/store/prolly/shim/shim.go
Labels: correctness_approved

#7923 [dsess] Cache checks lookup for TPC-C update
  go/libraries/doltcore/sqle/dsess/session_cache.go
  go/libraries/doltcore/sqle/tables.go
Labels: correctness_approved

#7926 [auto-bump] [no-release-notes] dependency by max-hoffman
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#7929 dolt fetch default spec from empty repo should return silently
  go/libraries/doltcore/env/actions/clone.go
  go/libraries/doltcore/env/actions/remotes.go
  go/libraries/doltcore/env/remotes.go
  go/libraries/doltcore/sqle/dprocedures/dolt_fetch.go
  go/libraries/doltcore/sqle/dprocedures/dolt_pull.go
  integration-tests/bats/fetch.bats
Labels: correctness_approved

#7925 apply `filter-branch` changes to working/staged changes
  go/cmd/dolt/commands/filter-branch.go
  go/libraries/doltcore/doltdb/doltdb.go
  go/libraries/doltcore/rebase/filter_branch.go
  integration-tests/bats/filter-branch.bats
Labels: correctness_approved

#7934 [auto-bump] [no-release-notes] dependency by max-hoffman
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved
