Repository dolthub/dolt, pull requests merged in 2024-02, with the labels that each got.

#7443 add disable version check warning
  go/cmd/dolt/commands/version.go
  go/libraries/utils/config/keys.go
  integration-tests/bats/no-repo.bats
Labels: correctness_approved

#7446 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#7441 Persist table comment from `create table`
  go/gen/fb/serial/schema.go
  go/go.mod
  go/go.sum
  go/libraries/doltcore/mvdata/engine_table_writer.go
  go/libraries/doltcore/schema/encoding/serialization.go
  go/libraries/doltcore/schema/schema.go
  go/libraries/doltcore/schema/schema_impl.go
  go/libraries/doltcore/sqle/database.go
  go/libraries/doltcore/sqle/enginetest/dolt_harness.go
  go/libraries/doltcore/sqle/indexed_dolt_table.go
  go/libraries/doltcore/sqle/procedures_table_test.go
  go/libraries/doltcore/sqle/schema_table_test.go
  go/libraries/doltcore/sqle/sqlfmt/schema_fmt.go
  go/libraries/doltcore/sqle/tables.go
  go/serial/schema.fbs
Labels: correctness_approved

#7450 push should ignore tracking branch
  go/libraries/doltcore/env/actions/remotes.go
  integration-tests/bats/remotes-push-pull.bats
  integration-tests/bats/remotes.bats
Labels: correctness_approved

#7449 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#7452 [auto-bump] [no-release-notes] dependency by jycor
  .github/scripts/sql-correctness/current_correctness.txt
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#7459 [auto-bump] [no-release-notes] dependency by jycor
  .github/scripts/sql-correctness/current_correctness.txt
  go/go.mod
  go/go.sum
Labels: gms-bump, keep-alive, correctness_approved

#7461 [auto-bump] [no-release-notes] dependency by max-hoffman
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#7465 [no-release-notes] /go/cmd/dolt/dolt.go: add prof-path flag for setting profile path dir
  go/cmd/dolt/dolt.go
Labels: correctness_approved

#7464 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump, keep-alive, correctness_approved

#7462 Update validation for dropping an `auto_increment` primary key column
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/enginetest/dolt_queries.go
  go/libraries/doltcore/sqle/tables.go
Labels: correctness_approved

#7467 [no-release-notes] update sysbench runner tool to cpu profile dolt server
  go/performance/utils/sysbench_runner/config.go
  go/performance/utils/sysbench_runner/dolt.go
  go/performance/utils/sysbench_runner/doltgres.go
  go/performance/utils/sysbench_runner/mysql.go
  go/performance/utils/sysbench_runner/postgres.go
  go/performance/utils/sysbench_runner/results.go
  go/performance/utils/tpcc_runner/dolt.go
  go/performance/utils/tpcc_runner/mysql.go
  go/performance/utils/tpcc_runner/results.go
Labels: correctness_approved

#7469 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#7468 go/libraries/events: Restructure events collection so that we can send events while the dolt process is running.
  go/cmd/dolt/cli/command.go
  go/cmd/dolt/commands/sqlserver/server.go
  go/cmd/dolt/dolt.go
  go/libraries/doltcore/dbfactory/grpc.go
  go/libraries/events/collector.go
  go/libraries/events/emitter.go
  go/libraries/events/events_test.go
Labels: correctness_approved

#7471 [no-release-notes] profile fixes
  go/performance/utils/sysbench_runner/config.go
  go/performance/utils/sysbench_runner/profile.go
  go/performance/utils/sysbench_runner/run.go
Labels: correctness_approved

#7424 Stats auto refresh
  go/cmd/dolt/commands/engine/sqlengine.go
  go/go.mod
  go/go.sum
  go/libraries/doltcore/doltdb/doltdb.go
  go/libraries/doltcore/schema/statistic.go
  go/libraries/doltcore/sqle/database_provider.go
  go/libraries/doltcore/sqle/dprocedures/init.go
  go/libraries/doltcore/sqle/dprocedures/stats_funcs.go
  go/libraries/doltcore/sqle/dsess/dolt_session_test.go
  go/libraries/doltcore/sqle/dsess/session.go
  go/libraries/doltcore/sqle/dsess/session_db_provider.go
  go/libraries/doltcore/sqle/dsess/variables.go
  go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
  go/libraries/doltcore/sqle/enginetest/dolt_harness.go
  go/libraries/doltcore/sqle/enginetest/stats_queries.go
  go/libraries/doltcore/sqle/logictest/dolt/doltharness.go
  go/libraries/doltcore/sqle/sqlddl_test.go
  go/libraries/doltcore/sqle/stats/auto_refresh.go
  go/libraries/doltcore/sqle/stats/initdbhook.go
  go/libraries/doltcore/sqle/stats/read.go
  go/libraries/doltcore/sqle/stats/stats_provider.go
  go/libraries/doltcore/sqle/stats/update.go
  go/libraries/doltcore/sqle/stats/update_test.go
  go/libraries/doltcore/sqle/stats/write.go
  go/libraries/doltcore/sqle/system_variables.go
  go/libraries/doltcore/sqle/testutil.go
  integration-tests/bats/stats.bats
Labels: correctness_approved

#7474 [no-release-notes] Fix stats race
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/dprocedures/init.go
  go/libraries/doltcore/sqle/dprocedures/stats_funcs.go
  go/libraries/doltcore/sqle/stats/stats_provider.go
Labels: correctness_approved

#7463 `SELECT ... INTO OUTFILE ...` tests
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
  integration-tests/bats/sql-export.bats
  integration-tests/go-sql-server-driver/tests/sql-server-config.yaml
Labels: correctness_approved

#7483 [auto-bump] [no-release-notes] dependency by max-hoffman
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#7480 [no-release-notes] /go/performance/utils/sysbench_runner/profile.go: fix mkdir temp
  go/performance/utils/sysbench_runner/profile.go
Labels: correctness_approved

#7490 Bug fix: `IndexedDoltTable` didn't fully implement `DoltTable`'s interface
  go/cmd/dolt/commands/engine/sqlengine.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries.go
  go/libraries/doltcore/sqle/indexed_dolt_table.go
Labels: correctness_approved

#7482 go: sqle/cluster: When in standby mode, take the epoch of the primary.
  go/libraries/doltcore/sqle/cluster/interceptors.go
  integration-tests/go-sql-server-driver/tests/sql-server-cluster.yaml
Labels: correctness_approved

#7489 [no-release-notes] Stats on for TPC-C
  .github/scripts/performance-benchmarking/get-mysql-dolt-job-json.sh
  go/performance/utils/benchmark_runner/dolt_tpcc.go
  go/performance/utils/benchmark_runner/tpcc_tests.go
Labels: correctness_approved

#7494 Fix windows file paths for dropping databases
  go/libraries/doltcore/sqle/database_provider.go
  integration-tests/bats/sql-create-database.bats
Labels: correctness_approved

#7497 [no-release-notes] /go/performance/continuous_integration: update dockerfile to install go/benchmark/comparison_config.go
  go/performance/continuous_integration/SysbenchDockerfile
  go/performance/continuous_integration/SysbenchDockerfile.dockerignore
  go/performance/continuous_integration/config.json
  go/performance/continuous_integration/mysqld.cnf
  go/performance/continuous_integration/sysbench-runner-tests-entrypoint.sh
  go/performance/continuous_integration/tpcc-config.json
  go/performance/utils/benchmark_runner/run_test.go
Labels: correctness_approved

#7499 [no-release-notes] /{go,.github}: add scripts for building pgo dolt binaries
  .github/scripts/performance-benchmarking/get-dolt-profile-job-json.sh
  .github/scripts/performance-benchmarking/run-benchmarks.sh
  .github/workflows/k8s-dolt-profile.yaml
  .github/workflows/test-build-pgo-dolt.yaml
  .github/workflows/test-performance-profile-job.yaml
  go/utils/publishrelease/buildpgobinaries.sh
Labels: correctness_approved

#7502 [no-release-notes] /go/libraries/doltcore/env/config.go: fix no config panic
  go/libraries/doltcore/env/config.go
Labels: correctness_approved

#7501 [no-release-notes] /.github/workflows/ci-benchmark-runner-tests.yaml: test benchmark runner in ci
  .github/workflows/ci-benchmark-runner-tests.yaml
  go/performance/continuous_integration/SysbenchDockerfile
  go/performance/continuous_integration/sysbench-runner-tests-entrypoint.sh
  go/performance/utils/benchmark_runner/run_test.go
  go/performance/utils/benchmark_runner/sysbench.go
Labels: correctness_approved

#7509 [no-release-notes] /go/{libraries,store}: revert removal of GetTopNTopoOrderedCommitsMatching, fix CSMetricWrapper chunkstore
  go/libraries/doltcore/env/actions/commitwalk/commitwalk.go
  go/store/chunks/cs_metrics_wrapper.go
Labels: correctness_approved

#7508 [auto-bump] [no-release-notes] dependency by jycor
  .github/scripts/sql-correctness/current_correctness.txt
  go/go.mod
  go/go.sum
Labels: gms-bump, keep-alive, correctness_approved

#7511 [auto-bump] [no-release-notes] dependency by jycor
  .github/scripts/sql-correctness/current_correctness.txt
  go/Godeps/LICENSES
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#7513 [auto-bump] [no-release-notes] dependency by jycor
  .github/scripts/sql-correctness/current_correctness.txt
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#7516 Less docker layers and more compact Docker image
  docker/Dockerfile
  docker/serverDockerfile
Labels: contribution

#7514 Bump actions/setup-go and use Go version from go.mod file
  .github/workflows/bump-dependency.yaml
  .github/workflows/cd-release-pgo.yaml
  .github/workflows/ci-bats-macos.yaml
  .github/workflows/ci-bats-unix-remote.yaml
  .github/workflows/ci-bats-unix.yaml
  .github/workflows/ci-bats-windows.yaml
  .github/workflows/ci-check-repo.yaml
  .github/workflows/ci-compatibility-tests.yaml
  .github/workflows/ci-go-race-tests.yaml
  .github/workflows/ci-go-tests.yaml
  .github/workflows/ci-lambdabats-unix.yaml
  .github/workflows/ci-sql-server-integration-tests.yaml
  .github/workflows/import-perf.yaml
  .github/workflows/merge-perf.yaml
  .github/workflows/sysbench-perf.yaml
Labels: contribution

#7525 [auto-bump] [no-release-notes] dependency by max-hoffman
  .github/scripts/sql-correctness/current_correctness.txt
  go/go.mod
  go/go.sum
  go/libraries/doltcore/schema/statistic.go
  go/libraries/doltcore/sqle/database.go
  go/libraries/doltcore/sqle/dolt_query_diff_table_function.go
  go/libraries/doltcore/sqle/dtables/blame_view.go
  go/libraries/doltcore/sqle/dtables/branches_table.go
  go/libraries/doltcore/sqle/dtables/column_diff_table.go
  go/libraries/doltcore/sqle/dtables/commit_ancestors_table.go
  go/libraries/doltcore/sqle/dtables/commit_diff_table.go
  go/libraries/doltcore/sqle/dtables/commits_table.go
  go/libraries/doltcore/sqle/dtables/diff_table.go
  go/libraries/doltcore/sqle/dtables/log_table.go
  go/libraries/doltcore/sqle/dtables/merge_status_table.go
  go/libraries/doltcore/sqle/dtables/schema_conflicts_table.go
  go/libraries/doltcore/sqle/dtables/statistics_table.go
  go/libraries/doltcore/sqle/dtables/table_of_tables_in_conflict.go
  go/libraries/doltcore/sqle/dtables/unscoped_diff_table.go
  go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
  go/libraries/doltcore/sqle/tables.go
Labels: gms-bump, correctness_approved

#7527 [no-release-notes] bump
  go/go.mod
  go/go.sum
Labels: correctness_approved

#7531 bump sqllogictest version
  .github/scripts/sql-correctness/current_correctness.txt
  go/go.mod
  go/go.sum
Labels: correctness_approved

#7532 [auto-bump] [no-release-notes] dependency by jycor
  .github/scripts/sql-correctness/current_correctness.txt
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#7534 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#7535 Allow importing tables when the columns contain characters that require escaping.
  go/libraries/doltcore/mvdata/engine_table_writer.go
  integration-tests/bats/helper/escaped-characters.csv
  integration-tests/bats/import-tables.bats
Labels: correctness_approved

#7507 [stats]: fix panic for empty table stats with one root chunk
  go/cmd/dolt/commands/engine/sqlengine.go
  go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
  go/libraries/doltcore/sqle/enginetest/dolt_harness.go
  go/libraries/doltcore/sqle/enginetest/stats_queries.go
  go/libraries/doltcore/sqle/stats/stats_provider.go
  go/libraries/doltcore/sqle/stats/update.go
  go/store/types/serial_message.go
Labels: correctness_approved

#7533 [store] row length guards for prolly serial messages
  go/go.mod
  go/go.sum
  go/libraries/doltcore/env/actions/infer_schema.go
  go/libraries/doltcore/schema/schema_impl.go
  go/libraries/doltcore/schema/typeinfo/typeinfo.go
  go/libraries/doltcore/schema/typeinfo/varstring.go
  go/libraries/doltcore/sqle/dtables/docs_table.go
  go/libraries/doltcore/sqle/enginetest/ddl_queries.go
  go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_merge.go
  go/libraries/doltcore/sqle/sqlinsert_test.go
  go/libraries/doltcore/sqle/sqlreplace_test.go
  go/libraries/doltcore/table/untyped/sqlexport/sqlwriter_test.go
  go/store/prolly/tree/prolly_fields.go
  go/store/val/tuple.go
  go/store/val/tuple_builder.go
  integration-tests/bats/blame-system-view.bats
  integration-tests/bats/import-create-tables.bats
  integration-tests/bats/schema-import.bats
Labels: correctness_approved

#7540 [auto-bump] [no-release-notes] dependency by Hydrocharged
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#7543 [auto-bump] [no-release-notes] dependency by nicktobey
  go/go.mod
  go/go.sum
  integration-tests/bats/1pk5col-ints.bats
Labels: gms-bump, keep-alive, correctness_approved

#7544 schema validator impl
  go/go.mod
  go/go.sum
  go/libraries/doltcore/schema/schema_impl.go
  go/libraries/doltcore/sqle/database.go
  integration-tests/bats/docs.bats
Labels: correctness_approved

#7537 Fixed handler bug related to ExtendedTypes
  go/store/prolly/artifact_map.go
  go/store/val/extended_comparator.go
Labels: correctness_approved

#7551 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, keep-alive, correctness_approved

#7552 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved
