Repository dolthub/dolt, pull requests merged in 2024-08, with the labels that each got.

#8184 [dtables] fix from_commit index behavior
  go/libraries/doltcore/sqle/dtables/diff_table.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries.go
  go/libraries/doltcore/sqle/index/dolt_index.go
Labels: correctness_approved

#8163 chore: init go workspace
  go/Godeps/LICENSES
  go/go.mod
  go/go.sum
  go/go.work
  go/go.work.sum
Labels: contribution

#8194 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8197 [no-release-notes] `dolt show` and splunk should show all the data in a TableSchemaFile
  go/store/types/serial_message.go
  integration-tests/bats/show.bats
Labels: correctness_approved

#8161 Liuliu/log-graph
  go/cmd/dolt/cli/arg_parser_helpers.go
  go/cmd/dolt/cli/flags.go
  go/cmd/dolt/commands/log.go
  go/cmd/dolt/commands/log_graph.go
  go/cmd/dolt/commands/log_graph_test.go
  integration-tests/bats/log.bats
Labels: correctness_approved

#8196 [no-release-notes] fix tests from insert id change
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/enginetest/dolt_procedure_queries.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_merge.go
Labels: correctness_approved

#8187 Feature: Auto-start binlog replication on server restart
  go/cmd/dolt/commands/engine/sqlengine.go
  go/cmd/dolt/commands/sqlserver/server.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_metadata_persistence.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_position_store.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_replica_applier.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_replica_controller.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_replication_test.go
Labels: correctness_approved

#8195 [no-release-notes] /go/cmd/dolt/commands/version.go: ignore errors if fetching latest release fails
  go/cmd/dolt/commands/version.go
Labels: correctness_approved

#8201 chore: update lib:eventsapi 2022-> 2024
  go/go.mod
  go/go.sum
Labels: contribution

#8182 go/libraries/doltcore/env/actions: Improve error message when a clone fails mid-download.
  go/libraries/doltcore/env/actions/clone.go
Labels: correctness_approved

#8183 [no-release-notes] query flags bump
  go/cmd/dolt/commands/dump.go
  go/cmd/dolt/commands/engine/sqlengine.go
  go/go.mod
  go/go.sum
  go/libraries/doltcore/mvdata/engine_table_reader.go
  go/libraries/doltcore/mvdata/engine_table_writer.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_replica_applier.go
  go/libraries/doltcore/sqle/database.go
  go/libraries/doltcore/sqle/enginetest/branch_control_test.go
  go/libraries/doltcore/sqle/enginetest/dolt_branch_queries.go
  go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
  go/libraries/doltcore/sqle/enginetest/dolt_engine_tests.go
  go/libraries/doltcore/sqle/enginetest/prepared_queries.go
  go/libraries/doltcore/sqle/enginetest/privilege_test.go
  go/libraries/doltcore/sqle/enginetest/stats_queries.go
  go/libraries/doltcore/sqle/enginetest/testgen_test.go
  go/libraries/doltcore/sqle/expranalysis/expranalysis.go
  go/libraries/doltcore/sqle/index/mergeable_indexes_test.go
  go/libraries/doltcore/sqle/kvexec/lookup_join_test.go
  go/libraries/doltcore/sqle/sqlutil/schema.go
Labels: correctness_approved

#8211 Bug fix: binlog replication: logging levels, use MySQL's older date serialization format
  go/libraries/doltcore/sqle/binlogreplication/binlog_primary_streamer.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_producer.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_type_serialization.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_type_serialization_test.go
Labels: correctness_approved

#8209 add constraint violations to dolt status
  go/cmd/dolt/commands/status.go
  go/libraries/doltcore/sqle/dtables/status_table.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_merge.go
  integration-tests/bats/cherry-pick.bats
  integration-tests/bats/constraint-violations.bats
Labels: correctness_approved

#8210 [no-release-notes] another max1row iter
  go/cmd/dolt/cli/command.go
  go/cmd/dolt/commands/add.go
  go/cmd/dolt/commands/assist.go
  go/cmd/dolt/commands/blame.go
  go/cmd/dolt/commands/branch.go
  go/cmd/dolt/commands/cherry-pick.go
  go/cmd/dolt/commands/cnfcmds/cat.go
  go/cmd/dolt/commands/commit.go
  go/cmd/dolt/commands/cvcmds/verify_constraints.go
  go/cmd/dolt/commands/diff.go
  go/cmd/dolt/commands/docscmds/read.go
  go/cmd/dolt/commands/docscmds/write.go
  go/cmd/dolt/commands/dump.go
  go/cmd/dolt/commands/engine/sqlengine.go
  go/cmd/dolt/commands/fetch.go
  go/cmd/dolt/commands/filter-branch.go
  go/cmd/dolt/commands/gc.go
  go/cmd/dolt/commands/ls.go
  go/cmd/dolt/commands/merge.go
  go/cmd/dolt/commands/pull.go
  go/cmd/dolt/commands/push.go
  go/cmd/dolt/commands/query_diff.go
  go/cmd/dolt/commands/rebase.go
  go/cmd/dolt/commands/reset.go
  go/cmd/dolt/commands/revert.go
  go/cmd/dolt/commands/sql.go
  go/cmd/dolt/commands/sqlserver/queryist_utils.go
  go/cmd/dolt/commands/utils.go
  go/go.mod
  go/go.sum
  go/libraries/doltcore/merge/integration_test.go
  go/libraries/doltcore/mvdata/engine_table_reader.go
  go/libraries/doltcore/mvdata/engine_table_writer.go
  go/libraries/doltcore/sqle/alterschema_test.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_replica_applier.go
  go/libraries/doltcore/sqle/common_test.go
  go/libraries/doltcore/sqle/dolt_query_diff_table_function.go
  go/libraries/doltcore/sqle/enginetest/branch_control_test.go
  go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
  go/libraries/doltcore/sqle/enginetest/dolt_engine_tests.go
  go/libraries/doltcore/sqle/enginetest/dolt_harness.go
  go/libraries/doltcore/sqle/index/mergeable_indexes_setup_test.go
  go/libraries/doltcore/sqle/index/mergeable_indexes_test.go
  go/libraries/doltcore/sqle/kvexec/lookup_join_test.go
  go/libraries/doltcore/sqle/logictest/dolt/doltharness.go
  go/libraries/doltcore/sqle/show_create_table.go
  go/libraries/doltcore/sqle/sqlddl_test.go
  go/libraries/doltcore/sqle/testutil.go
  go/libraries/doltcore/sqle/writer/noms_table_writer_test.go
  go/performance/microsysbench/sysbench_test.go
Labels: correctness_approved

#8219 Bug fix: events should remain enabled after sql-server restarts
  go/libraries/doltcore/sqle/database.go
  integration-tests/bats/events.bats
Labels: correctness_approved

#8223 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8224 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8230 [auto-bump] [no-release-notes] dependency by max-hoffman
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8198 [no-release-notes] Improve how non-leaf blob nodes are displayed in `dolt show`
  go/store/prolly/message/blob.go
  go/store/types/serial_message.go
  integration-tests/bats/show.bats
Labels: correctness_approved

#8232 [auto-bump] [no-release-notes] dependency by max-hoffman
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/dtables/unscoped_diff_table.go
  go/libraries/doltcore/sqle/index/index_reader.go
  go/libraries/doltcore/sqle/index/secondary_iter.go
Labels: gms-bump, correctness_approved

#8238 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8226 Liuliu/log one line graph
  go/cmd/dolt/commands/log.go
  go/cmd/dolt/commands/log_graph.go
  go/cmd/dolt/commands/log_graph_test.go
  go/cmd/dolt/commands/utils.go
  integration-tests/bats/checkout.bats
  integration-tests/bats/log.bats
Labels: correctness_approved

#8243 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8239 Rewrite the `dolt show` implementation.
  go/cmd/dolt/commands/cherry-pick.go
  go/cmd/dolt/commands/log.go
  go/cmd/dolt/commands/show.go
  go/cmd/dolt/commands/utils.go
  integration-tests/bats/show.bats
  integration-tests/bats/sql-local-remote.bats
Labels: correctness_approved

#8247 Fix displaying AddressMap non-leaf nodes in `noms show`
  go/store/cmd/noms/noms_show.go
Labels: correctness_approved

#8252 go/store/nbs: Fix table_index for table files with so many chunks that certain index slice operations overflow a uint32.
  go/store/nbs/race_off.go
  go/store/nbs/race_on.go
  go/store/nbs/table_index.go
  go/store/nbs/table_index_test.go
Labels: correctness_approved

#8249 [no-release-notes] test serialization behavior after normalizing column defaults
  go/go.mod
  go/go.sum
  go/go.work.sum
  go/libraries/doltcore/schema/typeinfo/int_test.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_merge.go
  go/libraries/doltcore/sqle/sqlddl_test.go
  go/libraries/doltcore/sqle/sqlfmt/schema_fmt.go
Labels: correctness_approved

#8248 support \checkout, \merge, \show
  go/cmd/dolt/cli/cli_context.go
  go/cmd/dolt/cli/messages.go
  go/cmd/dolt/commands/checkout.go
  go/cmd/dolt/commands/merge.go
  go/cmd/dolt/commands/sql.go
  go/cmd/dolt/commands/sql_slash.go
  integration-tests/bats/sql-local-remote.bats
  integration-tests/bats/sql-shell-slash-cmds.expect
Labels: correctness_approved

#8235 [no-release-notes] Fix `dolt version` error output when GitHub returns a 403
  go/cmd/dolt/commands/version.go
Labels: correctness_approved

#8129 Add optimized diffing and three-way merge of indexed JSON Documents.
  go/go.mod
  go/go.sum
  go/libraries/doltcore/merge/merge_prolly_rows.go
  go/libraries/doltcore/merge/schema_merge_test.go
  go/libraries/doltcore/merge/three_way_json_differ.go
  go/store/prolly/tree/diff.go
  go/store/prolly/tree/indexed_json_diff.go
  go/store/prolly/tree/json_cursor.go
  go/store/prolly/tree/json_diff.go
  go/store/prolly/tree/json_diff_test.go
  go/store/prolly/tree/json_indexed_document.go
  go/store/prolly/tree/json_indexed_document_test.go
  go/store/prolly/tree/json_location.go
  go/store/prolly/tree/json_scanner.go
  go/store/prolly/tree/json_type_categories.go
Labels: correctness_approved

#8259 liuliu/graph-remove-extra-s
  go/cmd/dolt/commands/log_graph.go
Labels: correctness_approved

#8245 Feature: support for --empty=[drop|keep] in dolt_rebase()
  go/cmd/dolt/cli/arg_parser_helpers.go
  go/cmd/dolt/cli/flags.go
  go/cmd/dolt/commands/cherry-pick.go
  go/cmd/dolt/commands/rebase.go
  go/cmd/dolt/commands/utils.go
  go/gen/fb/serial/workingset.go
  go/libraries/doltcore/cherry_pick/cherry_pick.go
  go/libraries/doltcore/doltdb/workingset.go
  go/libraries/doltcore/sqle/dprocedures/dolt_cherry_pick.go
  go/libraries/doltcore/sqle/dprocedures/dolt_rebase.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_rebase.go
  go/serial/workingset.fbs
  go/store/datas/dataset.go
  go/store/datas/workingset.go
  integration-tests/bats/cherry-pick.bats
  integration-tests/bats/rebase.bats
  integration-tests/bats/sql-cherry-pick.bats
Labels: correctness_approved

#8258 Bug fix: Testing for invalid global configuration dir permissions earlier, to prevent a panic
  go/cmd/dolt/dolt.go
  integration-tests/bats/no-repo.bats
Labels: correctness_approved

#8261 liuliu/graph-spaces-fix
  go/cmd/dolt/commands/log_graph.go
  go/cmd/dolt/commands/utils.go
Labels: correctness_approved

#8253 Add dolt_workspace_* system tables
  go/libraries/doltcore/doltdb/system_table.go
  go/libraries/doltcore/sqle/database.go
  go/libraries/doltcore/sqle/dolt_diff_table_function.go
  go/libraries/doltcore/sqle/dolt_patch_table_function.go
  go/libraries/doltcore/sqle/dtables/column_diff_table.go
  go/libraries/doltcore/sqle/dtables/diff_iter.go
  go/libraries/doltcore/sqle/dtables/diff_table.go
  go/libraries/doltcore/sqle/dtables/workspace.go
  go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
  go/libraries/doltcore/sqle/enginetest/dolt_engine_tests.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_workspace.go
  integration-tests/bats/ls.bats
Labels: correctness_approved

#8242 Skip filterIter match check when a key range is contiguous
  go/libraries/doltcore/sqle/index/dolt_index.go
  go/libraries/doltcore/sqle/index/index_reader.go
  go/libraries/doltcore/sqle/kvexec/builder.go
  go/store/prolly/tuple_map.go
  go/store/prolly/tuple_range.go
Labels: correctness_approved

#8241 [no-release-notes] range select perf bump
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/database_provider.go
  go/performance/microsysbench/sysbench_test.go
Labels: correctness_approved

#8266 [auto-bump] [no-release-notes] dependency by tbantle22
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8271 [auto-bump] [no-release-notes] dependency by jennifersp
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8260 Fixes for dolt installer bash-script
  go/utils/publishrelease/install.sh
Labels: contribution

#8274 Allow duplicate indexes, to match MySQL behavior
  go/go.mod
  go/go.sum
  go/libraries/doltcore/schema/index_coll.go
  go/libraries/doltcore/schema/index_test.go
Labels: correctness_approved

#8273 ResolveDefaultExpression should return a ColumnDefaultValue instance, because it has information about the type of the column and performs conversions.
  go/libraries/doltcore/sqle/expranalysis/expranalysis.go
Labels: correctness_approved

#8279 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8280 [no-release-notes] Revert PR causing index issues
  go/libraries/doltcore/sqle/index/dolt_index.go
  go/libraries/doltcore/sqle/index/index_reader.go
  go/libraries/doltcore/sqle/kvexec/builder.go
  go/store/prolly/tuple_map.go
  go/store/prolly/tuple_range.go
Labels: correctness_approved

#8286 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8288 Skip filter iter, with more test fixes
  go/libraries/doltcore/sqle/index/dolt_index.go
  go/libraries/doltcore/sqle/index/index_reader.go
  go/libraries/doltcore/sqle/kvexec/builder.go
  go/store/prolly/tuple_map.go
  go/store/prolly/tuple_range.go
Labels: correctness_approved

#8290 [auto-bump] [no-release-notes] dependency by max-hoffman
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8291 [commands] faster sqldump query scanner
  go/cmd/dolt/cli/command.go
  go/cmd/dolt/commands/engine/sqlengine.go
  go/cmd/dolt/commands/filter-branch.go
  go/cmd/dolt/commands/sql.go
  go/cmd/dolt/commands/sql_statement_scanner.go
  go/cmd/dolt/commands/sql_statement_scanner_test.go
  go/cmd/dolt/commands/sqlserver/queryist_utils.go
Labels: correctness_approved

#8296 fix case insensitive column match in kv iter
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/kvexec/lookup_join.go
  go/libraries/doltcore/sqle/kvexec/lookup_join_test.go
Labels: correctness_approved

#8299 More consistent return types for dolt procedures
  go/libraries/doltcore/sqle/dprocedures/dolt_cherry_pick.go
  go/libraries/doltcore/sqle/dprocedures/dolt_conflicts_resolve.go
  go/libraries/doltcore/sqle/dprocedures/dolt_remote.go
  go/libraries/doltcore/sqle/dprocedures/dolt_tag.go
  integration-tests/mysql-client-tests/node/workbenchTests/databases.js
Labels: correctness_approved

#8186 Add support for Doltgres indexes
  go/go.mod
  go/go.sum
  go/go.work.sum
  go/libraries/doltcore/sqle/dtables/commit_diff_table.go
  go/libraries/doltcore/sqle/index/dolt_index.go
  go/libraries/doltcore/sqle/index/dolt_index_test.go
  go/libraries/doltcore/sqle/index/doltgres_iter.go
  go/libraries/doltcore/sqle/index/index_reader.go
  go/libraries/doltcore/sqle/index/prolly_index_iter.go
  go/libraries/doltcore/sqle/index/testutils.go
  go/libraries/doltcore/sqle/procedures_table.go
Labels: correctness_approved

#8300 Fix nil panic in using `dolt show` to inspect secondary indexes.
  go/store/types/serial_message.go
  integration-tests/bats/show.bats
Labels: correctness_approved

#8302 [auto-bump] [no-release-notes] dependency by nicktobey
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8297 dolt_workspace_* update and delete support
  go/libraries/doltcore/merge/schema_merge_test.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_replica_applier.go
  go/libraries/doltcore/sqle/database.go
  go/libraries/doltcore/sqle/dsess/session.go
  go/libraries/doltcore/sqle/dsess/table_writer.go
  go/libraries/doltcore/sqle/dtables/docs_table.go
  go/libraries/doltcore/sqle/dtables/ignore_table.go
  go/libraries/doltcore/sqle/dtables/workspace.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_workspace.go
  go/libraries/doltcore/sqle/tables.go
  go/libraries/doltcore/sqle/temp_table.go
  go/libraries/doltcore/sqle/writer/noms_write_session.go
  go/libraries/doltcore/sqle/writer/prolly_table_writer.go
  go/libraries/doltcore/sqle/writer/prolly_write_session.go
  go/libraries/doltcore/table/editor/pk_table_editor.go
Labels: correctness_approved

#8304 [auto-bump] [no-release-notes] dependency by nicktobey
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8303 Perf: Optimize SQL transaction commits in binlog replication applier
  go/libraries/doltcore/sqle/binlogreplication/binlog_replica_applier.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_replication_test.go
  go/libraries/doltcore/sqle/dsess/session.go
Labels: correctness_approved

#8294 Feature: Data conflict resolution during interactive rebase
  go/cmd/dolt/commands/rebase.go
  go/gen/fb/serial/workingset.go
  go/libraries/doltcore/cherry_pick/cherry_pick.go
  go/libraries/doltcore/doltdb/workingset.go
  go/libraries/doltcore/rebase/rebase.go
  go/libraries/doltcore/sqle/dprocedures/dolt_rebase.go
  go/libraries/doltcore/sqle/dsess/session.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_rebase.go
  go/serial/workingset.fbs
  go/store/datas/dataset.go
  go/store/datas/workingset.go
  integration-tests/bats/rebase.bats
Labels: correctness_approved

#8311 [kvexec] fix more lookup bugs related to schema/projection inconsistencies
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/index/index_reader.go
  go/libraries/doltcore/sqle/kvexec/builder.go
  go/libraries/doltcore/sqle/kvexec/lookup_join.go
Labels: correctness_approved
