Repository dolthub/dolt, pull requests merged in 2024-10, with the labels that each got.

#8404 use global variable for default unix socket file path
  go/libraries/doltcore/servercfg/serverconfig.go
Labels: correctness_approved

#8405 [auto-bump] [no-release-notes] dependency by reltuk
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8412 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8411 Return `schema.table` for table name columns in dolt diff/status tables and functions for doltgres
  go/libraries/doltcore/diff/table_deltas.go
  go/libraries/doltcore/doltdb/workingset.go
  go/libraries/doltcore/env/actions/commit.go
  go/libraries/doltcore/sqle/dolt_diff_stat_table_function.go
  go/libraries/doltcore/sqle/dolt_diff_summary_table_function.go
  go/libraries/doltcore/sqle/dolt_diff_table_function.go
  go/libraries/doltcore/sqle/dolt_patch_table_function.go
  go/libraries/doltcore/sqle/dolt_schema_diff_table_function.go
  go/libraries/doltcore/sqle/dprocedures/dolt_conflicts_resolve.go
  go/libraries/doltcore/sqle/dprocedures/dolt_merge.go
  go/libraries/doltcore/sqle/dtables/column_diff_table.go
  go/libraries/doltcore/sqle/dtables/merge_status_table.go
  go/libraries/doltcore/sqle/dtables/schema_conflicts_table.go
  go/libraries/doltcore/sqle/dtables/status_table.go
  go/libraries/doltcore/sqle/dtables/table_of_tables_in_conflict.go
  go/libraries/doltcore/sqle/dtables/unscoped_diff_table.go
Labels: correctness_approved

#8393 Pass `nil` `sql.QueryFlags` to `planbuilder.Binder` and bump
  go/cmd/dolt/commands/dump.go
  go/go.mod
  go/go.sum
  go/libraries/doltcore/mvdata/engine_table_reader.go
  go/libraries/doltcore/mvdata/engine_table_writer.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_replica_applier.go
  go/libraries/doltcore/sqle/database.go
  go/libraries/doltcore/sqle/enginetest/dolt_branch_queries.go
  go/libraries/doltcore/sqle/enginetest/testgen_test.go
  go/libraries/doltcore/sqle/expranalysis/expranalysis.go
  go/libraries/doltcore/sqle/index/mergeable_indexes_test.go
  go/libraries/doltcore/sqle/kvexec/count_agg_test.go
  go/libraries/doltcore/sqle/kvexec/lookup_join_test.go
  go/libraries/doltcore/sqle/sqlutil/schema.go
Labels: correctness_approved

#8414 [no-release-notes] Rewrote history table tests to be more doltgres compatible
  go/libraries/doltcore/sqle/enginetest/dolt_queries.go
  go/libraries/doltcore/sqle/history_table.go
Labels: correctness_approved

#8415 Clean up table functions, fix `dolt_patch` for doltgres
  go/cmd/dolt/commands/diff_output.go
  go/libraries/doltcore/sqle/database_provider.go
  go/libraries/doltcore/sqle/dtablefunctions/dolt_diff_stat_table_function.go
  go/libraries/doltcore/sqle/dtablefunctions/dolt_diff_summary_table_function.go
  go/libraries/doltcore/sqle/dtablefunctions/dolt_diff_table_function.go
  go/libraries/doltcore/sqle/dtablefunctions/dolt_log_table_function.go
  go/libraries/doltcore/sqle/dtablefunctions/dolt_patch_table_function.go
  go/libraries/doltcore/sqle/dtablefunctions/dolt_query_diff_table_function.go
  go/libraries/doltcore/sqle/dtablefunctions/dolt_schema_diff_table_function.go
  go/libraries/doltcore/sqle/dtablefunctions/init.go
  go/libraries/doltcore/sqle/dtablefunctions/reflog_table_function.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_diff.go
Labels: correctness_approved

#8418 Properly Read and Write DECIMAL types with Parquet
  go/libraries/doltcore/table/typed/parquet/reader.go
  go/libraries/doltcore/table/typed/parquet/writer.go
  integration-tests/bats/export-tables.bats
Labels: correctness_approved

#8420 Check for `StringType` support before casting
  go/libraries/doltcore/schema/schema_impl.go
Labels: correctness_approved

#8409 dolt fsck
  go/cmd/dolt/cli/flags.go
  go/cmd/dolt/commands/fsck.go
  go/cmd/dolt/commands/utils.go
  go/cmd/dolt/dolt.go
  go/libraries/doltcore/doltdb/doltdb.go
  go/store/chunks/chunk_store.go
  go/store/chunks/memory_store.go
  go/store/chunks/test_utils.go
  go/store/nbs/archive_chunk_source.go
  go/store/nbs/archive_test.go
  go/store/nbs/chunk_source_adapter.go
  go/store/nbs/empty_chunk_source.go
  go/store/nbs/file_table_reader.go
  go/store/nbs/journal_chunk_source.go
  go/store/nbs/journal_record.go
  go/store/nbs/nbs_metrics_wrapper.go
  go/store/nbs/store.go
  go/store/nbs/table.go
  integration-tests/bats/corrupt_dbs/README.md
  integration-tests/bats/corrupt_dbs/bad_commit/noms/9tj851gpv71861ln5k6uutfot66u79r4
  integration-tests/bats/corrupt_dbs/bad_commit/noms/LOCK
  integration-tests/bats/corrupt_dbs/bad_commit/noms/manifest
  integration-tests/bats/corrupt_dbs/bad_commit/noms/oldgen/LOCK
  integration-tests/bats/corrupt_dbs/bad_commit/noms/oldgen/aa3a08lf6sbtq9cl58mledifrqvt3fid
  integration-tests/bats/corrupt_dbs/bad_commit/noms/oldgen/manifest
  integration-tests/bats/corrupt_dbs/bad_commit/repo_state.json
  integration-tests/bats/corrupt_dbs/bad_journal_crc/noms/LOCK
  integration-tests/bats/corrupt_dbs/bad_journal_crc/noms/journal.idx
  integration-tests/bats/corrupt_dbs/bad_journal_crc/noms/manifest
  integration-tests/bats/corrupt_dbs/bad_journal_crc/noms/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
  integration-tests/bats/corrupt_dbs/bad_journal_crc/repo_state.json
  integration-tests/bats/fsck.bats
  integration-tests/bats/helper/local-remote.bash
Labels: correctness_approved

#8424 Add information_schema test for detached head
  go/libraries/doltcore/sqle/enginetest/dolt_queries.go
Labels: correctness_approved

#8427 Fix AllSchemas for detached head
  go/libraries/doltcore/sqle/database.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries.go
Labels: correctness_approved

#8426 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8430 Database returns tables in all schemas when schema is not set
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/database.go
  go/libraries/doltcore/sqle/resolve/resolve_tables.go
Labels: correctness_approved

#8434 Fix GetSchema for detached head
  go/libraries/doltcore/sqle/database.go
Labels: correctness_approved

#8436 [no-release-notes] parser perf bump
  go/go.mod
  go/go.sum
Labels: correctness_approved

#8437 [auto-bump] [no-release-notes] dependency by max-hoffman
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8438 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8439 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8432 support partial foreign key updates
  go/go.mod
  go/go.sum
  integration-tests/bats/foreign-keys.bats
Labels: correctness_approved

#8445 [no-release-notes] add warning test for dotnet integration
  go/go.mod
  go/go.sum
  integration-tests/mysql-client-tests/dotnet/MySqlClient/Program.cs
Labels: correctness_approved

#8446 Implemented checking out a table or tables from another commit
  go/cmd/dolt/commands/checkout.go
  go/libraries/doltcore/sqle/dprocedures/dolt_checkout.go
  go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries.go
  go/libraries/utils/argparser/parser_test.go
  integration-tests/bats/checkout.bats
Labels: correctness_approved

#8450 log server metrics heartbeat
  go/cmd/dolt/commands/sqlserver/server.go
Labels: correctness_approved

#8449 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8454 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, keep-alive, correctness_approved

#8459 Fix merge bugs for doltgres
  go/cmd/dolt/commands/read_tables.go
  go/libraries/doltcore/doltdb/root_val.go
  go/libraries/doltcore/env/actions/checkout.go
  go/libraries/doltcore/merge/action.go
  go/libraries/doltcore/merge/merge.go
  go/libraries/doltcore/merge/schema_merge_test.go
  go/libraries/doltcore/sqle/dprocedures/dolt_merge.go
Labels: correctness_approved

#8462 dolt gc --full: Implement a flag for GC which will collect everything, including the old gen.
  go/cmd/dolt/cli/arg_parser_helpers.go
  go/cmd/dolt/cli/flags.go
  go/cmd/dolt/commands/gc.go
  go/libraries/doltcore/doltdb/doltdb.go
  go/libraries/doltcore/doltdb/gc_test.go
  go/libraries/doltcore/sqle/dprocedures/dolt_gc.go
  go/store/chunks/chunk_store.go
  go/store/chunks/memory_store.go
  go/store/chunks/test_utils.go
  go/store/datas/database.go
  go/store/datas/database_common.go
  go/store/nbs/archive_chunk_source.go
  go/store/nbs/generational_chunk_store.go
  go/store/nbs/nbs_metrics_wrapper.go
  go/store/nbs/store.go
  go/store/nbs/store_test.go
  go/store/nbs/table_set.go
  go/store/types/value_store.go
  go/store/types/value_store_test.go
  integration-tests/bats/garbage_collection.bats
Labels: correctness_approved

#8463 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8464 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8465 go/libraries/doltcore/doltdb: root_val.go: Restore ForeignKey TableNames noms serialization as just strings.
  go/libraries/doltcore/doltdb/root_val.go
Labels: correctness_approved

#8470 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8471 [auto-bump] [no-release-notes] dependency by jennifersp
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8451 Stats purge and prune
  go/libraries/doltcore/sqle/dprocedures/init.go
  go/libraries/doltcore/sqle/dprocedures/stats_funcs.go
  go/libraries/doltcore/sqle/enginetest/stats_queries.go
  go/libraries/doltcore/sqle/statsnoms/database.go
  go/libraries/doltcore/sqle/statsnoms/write.go
  go/libraries/doltcore/sqle/statspro/auto_refresh.go
  go/libraries/doltcore/sqle/statspro/configure.go
  go/libraries/doltcore/sqle/statspro/interface.go
  go/libraries/doltcore/sqle/statspro/stats_provider.go
  go/store/datas/database_common.go
  go/store/datas/statistics.go
  integration-tests/bats/stats.bats
Labels: correctness_approved

#8473 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, keep-alive, correctness_approved

#8475 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8474 [no-release-notes] Replace ConvertToSecondaryKeylessIndex with AddHashToSchema
  go/cmd/dolt/commands/schcmds/import.go
  go/libraries/doltcore/doltdb/commit_hooks_test.go
  go/libraries/doltcore/doltdb/doltdb_test.go
  go/libraries/doltcore/doltdb/durable/index.go
  go/libraries/doltcore/doltdb/durable/table.go
  go/libraries/doltcore/doltdb/root_val.go
  go/libraries/doltcore/doltdb/table.go
  go/libraries/doltcore/dtestutils/testcommands/multienv.go
  go/libraries/doltcore/merge/fulltext_rebuild.go
  go/libraries/doltcore/merge/merge_prolly_indexes.go
  go/libraries/doltcore/merge/merge_prolly_rows.go
  go/libraries/doltcore/merge/mutable_secondary_index.go
  go/libraries/doltcore/merge/violations_fk.go
  go/libraries/doltcore/sqle/alterschema_test.go
  go/libraries/doltcore/sqle/common_test.go
  go/libraries/doltcore/sqle/dtables/conflicts_tables_prolly.go
  go/libraries/doltcore/sqle/dtables/diff_table.go
  go/libraries/doltcore/sqle/enginetest/validation.go
  go/libraries/doltcore/sqle/tables.go
  go/libraries/doltcore/sqle/temp_table.go
  go/libraries/doltcore/sqle/testutil.go
  go/libraries/doltcore/sqle/writer/prolly_table_writer.go
  go/libraries/doltcore/table/editor/creation/external_build_index.go
  go/libraries/doltcore/table/editor/creation/index.go
  go/libraries/doltcore/table/untyped/sqlexport/sqlwriter_test.go
  go/store/datas/statistics.go
  go/store/prolly/shim/shim.go
  go/store/prolly/tuple_map.go
Labels: correctness_approved

#8480 [no-release-notes] remove queryprocess bump
  go/go.mod
  go/go.sum
  go/libraries/doltcore/mvdata/engine_table_writer.go
Labels: correctness_approved

#8485 [no-release-notes] remove exchange bump
  go/cmd/dolt/commands/engine/sqlengine.go
  go/cmd/dolt/commands/filter-branch.go
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/enginetest/dolt_query_plans.go
  go/libraries/doltcore/sqle/enginetest/testgen_test.go
  go/libraries/doltcore/sqle/sqlddl_test.go
Labels: correctness_approved

#8484 [no-release-notes] /go/performance/continuous_integration/SysbenchDockerfile: bump doltgres version tested in sysbench tester
  go/performance/continuous_integration/SysbenchDockerfile
  go/performance/utils/benchmark_runner/doltgres.go
Labels: correctness_approved

#8453 turn on stats collect by default
  go/cmd/dolt/commands/sqlserver/server.go
  go/libraries/doltcore/sqle/cluster/controller.go
  go/libraries/doltcore/sqle/dprocedures/stats_funcs.go
  go/libraries/doltcore/sqle/enginetest/dolt_harness.go
  go/libraries/doltcore/sqle/statspro/configure.go
  go/libraries/doltcore/sqle/statspro/initdbhook.go
  go/libraries/doltcore/sqle/statspro/interface.go
  go/libraries/doltcore/sqle/statspro/stats_provider.go
  go/libraries/doltcore/sqle/system_variables.go
  integration-tests/bats/stats.bats
Labels: correctness_approved

#8487 Fix server init race
  go/cmd/dolt/commands/engine/sqlengine.go
Labels: correctness_approved

#8489 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8479 cross-schema foreign key support for doltgres tables
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/clusterdb/database.go
  go/libraries/doltcore/sqle/dsess/session_db_provider.go
  go/libraries/doltcore/sqle/tables.go
  go/libraries/doltcore/sqle/user_space_database.go
Labels: correctness_approved

#8492 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8494 Fix bounds check in import scanner
  go/cmd/dolt/commands/sql_statement_scanner.go
  go/cmd/dolt/commands/sql_statement_scanner_test.go
Labels: correctness_approved

#8493 add bats test for `kill query <pid>`
  go/cmd/dolt/commands/sqlserver/queryist_utils.go
  go/go.mod
  go/go.sum
  integration-tests/bats/processlist.bats
Labels: correctness_approved

#8501 Bug fixes for replication
  go/libraries/doltcore/sqle/binlogreplication/binlog_primary_streamer.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_primary_test.go
  go/libraries/doltcore/sqle/binlogreplication/system_variable_utils.go
Labels: correctness_approved

#8482 Move dolt system tables to dolt schema for doltgres
  go/libraries/doltcore/doltdb/system_table.go
  go/libraries/doltcore/env/actions/table.go
  go/libraries/doltcore/sqle/database.go
  go/libraries/doltcore/sqle/database_provider.go
  go/libraries/doltcore/sqle/dtables/branches_table.go
  go/libraries/doltcore/sqle/dtables/docs_table.go
  go/libraries/doltcore/sqle/dtables/log_table.go
  go/libraries/doltcore/sqle/dtables/status_table.go
  go/libraries/doltcore/sqle/dtables/tags_table.go
  go/libraries/doltcore/sqle/resolve/resolve_tables.go
  go/libraries/doltcore/sqle/resolve/search_path.go
Labels: correctness_approved

#8506 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8507 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, keep-alive, correctness_approved

#8499 scanner more safe whitespace skip
  go/cmd/dolt/commands/sql_statement_scanner.go
  go/cmd/dolt/commands/sql_statement_scanner_test.go
Labels: correctness_approved

#8505 Fix panics on schema changes
  go/libraries/doltcore/sqle/enginetest/stats_queries.go
  go/libraries/doltcore/sqle/statsnoms/database.go
  go/libraries/doltcore/sqle/statspro/analyze.go
  go/libraries/doltcore/sqle/statspro/auto_refresh.go
  go/libraries/doltcore/sqle/statspro/interface.go
  integration-tests/bats/stats.bats
Labels: correctness_approved

#8508 Update more system tables for doltgres
  go/libraries/doltcore/doltdb/system_table.go
  go/libraries/doltcore/sqle/database.go
  go/libraries/doltcore/sqle/dtables/branches_table.go
  go/libraries/doltcore/sqle/dtables/column_diff_table.go
  go/libraries/doltcore/sqle/dtables/commit_ancestors_table.go
  go/libraries/doltcore/sqle/dtables/commits_table.go
  go/libraries/doltcore/sqle/dtables/log_table.go
  go/libraries/doltcore/sqle/dtables/merge_status_table.go
  go/libraries/doltcore/sqle/dtables/remotes_table.go
  go/libraries/doltcore/sqle/dtables/schema_conflicts_table.go
  go/libraries/doltcore/sqle/dtables/status_table.go
  go/libraries/doltcore/sqle/dtables/table_of_tables_in_conflict.go
  go/libraries/doltcore/sqle/dtables/table_of_tables_with_violations.go
  go/libraries/doltcore/sqle/dtables/tags_table.go
  go/libraries/doltcore/sqle/dtables/unscoped_diff_table.go
Labels: correctness_approved

#8510 [auto-bump] [no-release-notes] dependency by max-hoffman
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved
