Repository dolthub/dolt, pull requests merged in 2024-11, with the labels that each got.

#8518 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, keep-alive, correctness_approved

#8515 [no-release-notes] bump planbuilder changes
  go/cmd/dolt/commands/dump.go
  go/cmd/dolt/commands/engine/sqlengine.go
  go/go.mod
  go/go.sum
  go/libraries/doltcore/mvdata/engine_table_reader.go
  go/libraries/doltcore/mvdata/engine_table_writer.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_replica_applier.go
  go/libraries/doltcore/sqle/database.go
  go/libraries/doltcore/sqle/enginetest/dolt_branch_queries.go
  go/libraries/doltcore/sqle/enginetest/testgen_test.go
  go/libraries/doltcore/sqle/expranalysis/expranalysis.go
  go/libraries/doltcore/sqle/index/mergeable_indexes_test.go
  go/libraries/doltcore/sqle/kvexec/count_agg_test.go
  go/libraries/doltcore/sqle/kvexec/lookup_join_test.go
  go/libraries/doltcore/sqle/sqlutil/schema.go
  go/libraries/doltcore/sqle/statsnoms/iter.go
Labels: correctness_approved

#8522 libraries/doltcore/remotestorage: Improve connection reuse when fetching chunks from remote storage.
  go/libraries/doltcore/env/grpc_dial_provider.go
  go/libraries/doltcore/remotestorage/chunk_store.go
Labels: correctness_approved

#8523 [no-release-notes] Planbuilder Authorization changes
  go/go.mod
  go/go.sum
  go/go.work.sum
  go/libraries/doltcore/mvdata/channel_row_source.go
  go/libraries/doltcore/sqle/dtablefunctions/dolt_diff_stat_table_function.go
  go/libraries/doltcore/sqle/dtablefunctions/dolt_diff_summary_table_function.go
  go/libraries/doltcore/sqle/dtablefunctions/dolt_diff_table_function.go
  go/libraries/doltcore/sqle/dtablefunctions/dolt_log_table_function.go
  go/libraries/doltcore/sqle/dtablefunctions/dolt_patch_table_function.go
  go/libraries/doltcore/sqle/dtablefunctions/dolt_query_diff_table_function.go
  go/libraries/doltcore/sqle/dtablefunctions/dolt_schema_diff_table_function.go
  go/libraries/doltcore/sqle/dtablefunctions/reflog_table_function.go
  integration-tests/bats/sql-local-remote.bats
  integration-tests/bats/sql-shell.bats
  integration-tests/bats/sql.bats
Labels: correctness_approved

#8514 Better view caching
  go/libraries/doltcore/doltdb/root_val.go
  go/libraries/doltcore/sqle/database.go
  go/libraries/doltcore/sqle/schema_table.go
Labels: correctness_approved

#8526 Avoid comparing `sql.Types` in `dolt diff`
  go/cmd/dolt/commands/diff.go
  integration-tests/bats/diff.bats
Labels: correctness_approved

#8529 [no-release-notes] tests for read-commit translation isolation level
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/enginetest/dolt_transaction_queries.go
Labels: correctness_approved

#8534 Fix issue where JSON diff would fail under specific circumstances.
  go/store/prolly/tree/indexed_json_diff.go
  go/store/prolly/tree/json_diff_test.go
  go/store/prolly/tree/json_scanner.go
Labels: correctness_approved

#8532 [no-release-notes] test views with dolt procedures
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/enginetest/dolt_queries_diff.go
Labels: correctness_approved

#8517 [no-release-notes] add dolt ci init and destroy
  go/cmd/dolt/commands/ci/ci.go
  go/cmd/dolt/commands/ci/destroy.go
  go/cmd/dolt/commands/ci/init.go
  go/cmd/dolt/dolt.go
  go/libraries/doltcore/doltdb/doltdb.go
  go/libraries/doltcore/doltdb/system_table.go
  go/libraries/doltcore/env/actions/dolt_ci/foreign_key.go
  go/libraries/doltcore/env/actions/dolt_ci/schema.go
  go/libraries/doltcore/env/actions/dolt_ci/workflow_event_trigger_activities.go
  go/libraries/doltcore/env/actions/dolt_ci/workflow_event_trigger_branches.go
  go/libraries/doltcore/env/actions/dolt_ci/workflow_event_triggers.go
  go/libraries/doltcore/env/actions/dolt_ci/workflow_events.go
  go/libraries/doltcore/env/actions/dolt_ci/workflow_jobs.go
  go/libraries/doltcore/env/actions/dolt_ci/workflow_saved_query_step_expected_row_column_results.go
  go/libraries/doltcore/env/actions/dolt_ci/workflow_saved_query_steps.go
  go/libraries/doltcore/env/actions/dolt_ci/workflow_steps.go
  go/libraries/doltcore/env/actions/dolt_ci/workflows.go
  go/libraries/doltcore/schema/index_coll.go
  go/libraries/doltcore/schema/reserved_tags.go
  go/libraries/doltcore/sqle/alterschema.go
  go/libraries/doltcore/sqle/database.go
  go/libraries/doltcore/sqle/tables.go
  integration-tests/bats/ci.bats
Labels: correctness_approved

#8538 Fix JSON merge issue that would report imprecise diffs in some situations
  go/store/prolly/tree/indexed_json_diff.go
  go/store/prolly/tree/json_cursor.go
  go/store/prolly/tree/json_diff_test.go
Labels: correctness_approved

#8527 Support multiple schema for system tables with $tablename for doltgres
  go/libraries/doltcore/sqle/database.go
  go/libraries/doltcore/sqle/dtables/blame_view.go
  go/libraries/doltcore/sqle/dtables/commit_diff_table.go
  go/libraries/doltcore/sqle/dtables/conflicts_tables.go
  go/libraries/doltcore/sqle/dtables/conflicts_tables_prolly.go
  go/libraries/doltcore/sqle/dtables/constraint_violations.go
  go/libraries/doltcore/sqle/dtables/constraint_violations_prolly.go
  go/libraries/doltcore/sqle/dtables/diff_table.go
  go/libraries/doltcore/sqle/dtables/workspace_table.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_diff.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_merge.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_workspace.go
  go/libraries/doltcore/sqle/history_table.go
Labels: correctness_approved

#8540 liuliu/pass-databaseName-to-DoltDBFromCS
  go/libraries/doltcore/doltdb/doltdb.go
  go/libraries/doltcore/env/memory.go
  go/libraries/doltcore/migrate/integration_test.go
Labels: correctness_approved

#8542 liuliu/return databasename
  go/libraries/doltcore/doltdb/doltdb.go
Labels: correctness_approved

#8543 [no-release-notes] /go/libraries/doltcore/env/actions/dolt_ci/schema.go: export expected tables
  go/libraries/doltcore/env/actions/dolt_ci/schema.go
Labels: correctness_approved

#8544 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8516 [no-release-notes] Bump dolt for GMS vector indexes.
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/index/dolt_index.go
  go/libraries/doltcore/sqle/sqlfmt/schema_fmt.go
Labels: correctness_approved

#8554 use new decimal type for `dolt diff`
  go/cmd/dolt/commands/diff.go
  integration-tests/bats/diff.bats
Labels: correctness_approved

#8556 [auto-bump] [no-release-notes] dependency by jennifersp
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8557 [no-release-notes] /go/{cmd,libraries}: add ci remove
  go/cmd/dolt/commands/ci/ci.go
  go/cmd/dolt/commands/ci/remove.go
  go/libraries/doltcore/env/actions/dolt_ci/workflow_manager.go
Labels: correctness_approved

#8558 [no-release-notes] /go/libraries/doltcore/env/actions/dolt_ci/workflow_manager.go: fix export
  go/libraries/doltcore/env/actions/dolt_ci/schema.go
  go/libraries/doltcore/env/actions/dolt_ci/workflow_manager.go
Labels: correctness_approved

#8555 In order to support multiple index types, create interface types for prolly Maps, and make the tree.MutableMap class generic.
  go/libraries/doltcore/doltdb/durable/artifact_index.go
  go/libraries/doltcore/doltdb/durable/index.go
  go/libraries/doltcore/doltdb/durable/table.go
  go/libraries/doltcore/sqle/enginetest/validation.go
  go/libraries/doltcore/sqle/index/dolt_index.go
  go/libraries/doltcore/sqle/writer/prolly_index_writer.go
  go/libraries/doltcore/sqle/writer/prolly_index_writer_keyless.go
  go/libraries/doltcore/sqle/writer/prolly_table_writer.go
  go/store/prolly/address_map.go
  go/store/prolly/artifact_map.go
  go/store/prolly/commit_closure.go
  go/store/prolly/map_interface.go
  go/store/prolly/mutable_map_flusher.go
  go/store/prolly/shim/shim.go
  go/store/prolly/tree/map.go
  go/store/prolly/tree/mutable_map.go
  go/store/prolly/tuple_map.go
  go/store/prolly/tuple_mutable_map.go
Labels: correctness_approved

#8521 [no-release-notes] Refactor methods that parse messages to return the message id tag.
  go/cmd/dolt/commands/roots.go
  go/libraries/doltcore/doltdb/durable/artifact_index.go
  go/libraries/doltcore/doltdb/durable/table.go
  go/libraries/doltcore/doltdb/root_val_storage.go
  go/store/cmd/noms/noms_show.go
  go/store/datas/commit_closure.go
  go/store/datas/refmap.go
  go/store/datas/stashlist.go
  go/store/prolly/address_map.go
  go/store/prolly/commit_closure.go
  go/store/prolly/map_test.go
  go/store/prolly/message/address_map.go
  go/store/prolly/message/blob.go
  go/store/prolly/message/message.go
  go/store/prolly/shim/shim.go
  go/store/prolly/tree/blob_builder.go
  go/store/prolly/tree/json_chunker.go
  go/store/prolly/tree/node.go
  go/store/prolly/tree/node_builder.go
  go/store/prolly/tree/node_store.go
  go/store/prolly/tree/node_test.go
  go/store/prolly/tree/testutils.go
  go/store/types/serial_message.go
  go/store/valuefile/value_file_test.go
Labels: correctness_approved

#8559 [auto-bump] [no-release-notes] dependency by tbantle22
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8541 reverse keyless indexscans apply reversal
  go/libraries/doltcore/sqle/index/index_reader.go
  go/libraries/doltcore/sqle/index/prolly_index_iter.go
Labels: correctness_approved

#8560 [no-release-notes] auth test skip
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/enginetest/privilege_test.go
Labels: correctness_approved

#8564 [auto-bump] [no-release-notes] dependency by tbantle22
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8565 [auto-bump] [no-release-notes] dependency by tbantle22
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8566 Bug fix: `dolt_commit_diff` support for detached head mode
  go/libraries/doltcore/sqle/database.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_diff.go
Labels: correctness_approved

#8567 patch with tag collision test
  go/libraries/doltcore/diff/table_deltas.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_diff.go
Labels: correctness_approved

#8568 [auto-bump] [no-release-notes] dependency by max-hoffman
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8569 [no-release-notes] /go/performance/utils/benchmark_runner: fix for latest doltgres
  go/performance/continuous_integration/SysbenchDockerfile
  go/performance/utils/benchmark_runner/constants.go
  go/performance/utils/benchmark_runner/doltgres.go
  go/performance/utils/benchmark_runner/doltgres_server_config.go
Labels: correctness_approved

#8570 [no-release-notes] dolt ci bats tests
  go/libraries/doltcore/env/actions/dolt_ci/column_value.go
  go/libraries/doltcore/env/actions/dolt_ci/schema.go
  go/libraries/doltcore/env/actions/dolt_ci/workflow_manager.go
  integration-tests/bats/ci.bats
Labels: correctness_approved

#8573 [auto-bump] [no-release-notes] dependency by max-hoffman
  go/Godeps/LICENSES
  go/go.mod
  go/go.sum
  go/go.work.sum
  integration-tests/go-sql-server-driver/go.mod
  integration-tests/go-sql-server-driver/go.sum
Labels: gms-bump, keep-alive, correctness_approved

#8577 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, keep-alive, correctness_approved

#8576 Change LateBindQueryist to use `mysql.NewSalt()`
  go/cmd/dolt/commands/utils.go
Labels: correctness_approved

#8578 Fix dolt_rebase and dolt_ignore for doltgres
  go/cmd/dolt/commands/stashcmds/pop.go
  go/libraries/doltcore/cherry_pick/cherry_pick.go
  go/libraries/doltcore/doltdb/ignore.go
  go/libraries/doltcore/merge/merge.go
  go/libraries/doltcore/sqle/database.go
  go/libraries/doltcore/sqle/dprocedures/dolt_merge.go
  go/libraries/doltcore/sqle/dprocedures/dolt_rebase.go
  go/libraries/doltcore/sqle/dtables/ignore_table.go
Labels: correctness_approved

#8581 Support per-schema dolt_ignore for doltgres
  go/libraries/doltcore/diff/table_deltas.go
  go/libraries/doltcore/doltdb/ignore.go
  go/libraries/doltcore/doltdb/root_val.go
  go/libraries/doltcore/sqle/database.go
  go/libraries/doltcore/sqle/dprocedures/dolt_rebase.go
  go/libraries/doltcore/sqle/dtables/ignore_table.go
Labels: correctness_approved

#8587 [auto-bump] [no-release-notes] dependency by Hydrocharged
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/binlogreplication/binlog_replication_test.go
  integration-tests/bats/cli-hosted.bats
  integration-tests/bats/sql-server.bats
Labels: gms-bump, keep-alive, correctness_approved

#8582 Support dolt.rebase for doltgres
  go/cmd/dolt/commands/commit.go
  go/cmd/dolt/commands/status.go
  go/cmd/dolt/commands/tblcmds/rm.go
  go/libraries/doltcore/doltdb/ignore.go
  go/libraries/doltcore/doltdb/system_table.go
  go/libraries/doltcore/sqle/database.go
  go/libraries/doltcore/sqle/database_provider.go
  go/libraries/doltcore/sqle/dtables/docs_table.go
  go/libraries/doltcore/sqle/resolve/search_path.go
  go/libraries/doltcore/sqle/tables.go
  go/libraries/doltcore/sqle/user_space_database.go
Labels: correctness_approved

#8588 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8590 system variables cannot have nil defaults
  go/libraries/doltcore/sqle/system_variables.go
  integration-tests/bats/sql-server.bats
Labels: correctness_approved

#8561 [kvexec] merge join
  go/libraries/doltcore/sqle/index/index_reader.go
  go/libraries/doltcore/sqle/index/prolly_index_iter.go
  go/libraries/doltcore/sqle/kvexec/builder.go
  go/libraries/doltcore/sqle/kvexec/lookup_join.go
  go/libraries/doltcore/sqle/kvexec/merge_join.go
Labels: correctness_approved

#8594 [auto-bump] [no-release-notes] dependency by Hydrocharged
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8596 go/store/nbs: table_index.go: Improve support for large table files.
  go/store/nbs/table_index.go
Labels: correctness_approved

#8599 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8602 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/binlogreplication/binlog_replication_test.go
Labels: gms-bump, correctness_approved

#8608 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8583 [no-release-notes] /{go,integration-tests}: remove trigger activities table in favor of typed activities
  go/libraries/doltcore/doltdb/system_table.go
  go/libraries/doltcore/env/actions/dolt_ci/schema.go
  go/libraries/doltcore/env/actions/dolt_ci/workflow_config.go
  go/libraries/doltcore/env/actions/dolt_ci/workflow_event.go
  go/libraries/doltcore/env/actions/dolt_ci/workflow_event_trigger.go
  go/libraries/doltcore/env/actions/dolt_ci/workflow_event_trigger_activity.go
  go/libraries/doltcore/env/actions/dolt_ci/workflow_manager.go
  go/libraries/doltcore/env/actions/dolt_ci/workflow_saved_query_step.go
  go/libraries/doltcore/env/actions/dolt_ci/workflow_saved_query_step_expected_row_column_result.go
  go/libraries/doltcore/env/actions/dolt_ci/workflow_step.go
  integration-tests/bats/ci.bats
Labels: correctness_approved

#8589 Fix dolt_statistics table for multiple schemas for doltgres
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/database.go
  go/libraries/doltcore/sqle/dtables/statistics_table.go
  go/libraries/doltcore/sqle/statsnoms/iter.go
  go/libraries/doltcore/sqle/statsnoms/load.go
  go/libraries/doltcore/sqle/statspro/analyze.go
  go/libraries/doltcore/sqle/statspro/auto_refresh.go
  go/libraries/doltcore/sqle/statspro/stats_provider.go
Labels: correctness_approved

#8614 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved
