Repository dolthub/dolt, pull requests merged in 2024-04, with the labels that each got.

#7673 CLI Docs: Adding docs for `system_variables` field in config.yaml for sql-server command
  go/cmd/dolt/commands/sqlserver/sqlserver.go
  go/cmd/dolt/commands/sqlserver/yaml_config.go
  go/cmd/dolt/commands/sqlserver/yaml_config_test.go
Labels: correctness_approved

#7674 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
Labels: gms-bump, keep-alive, correctness_approved

#7666 [statspro] Avoid copying histograms, perf improvement
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/statsnoms/database.go
  go/libraries/doltcore/sqle/statsnoms/load.go
  go/libraries/doltcore/sqle/statsnoms/write.go
  go/libraries/doltcore/sqle/statspro/analyze.go
  go/libraries/doltcore/sqle/statspro/auto_refresh.go
  go/libraries/doltcore/sqle/statspro/dolt_stats.go
  go/libraries/doltcore/sqle/statspro/interface.go
  go/libraries/doltcore/sqle/statspro/stats_provider.go
  go/libraries/doltcore/sqle/statspro/update.go
  go/libraries/doltcore/sqle/statspro/update_test.go
  go/store/chunks/chunk_store.go
  go/store/nbs/store.go
Labels: correctness_approved

#7677 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/enginetest/dolt_harness.go
Labels: gms-bump, keep-alive, correctness_approved

#7672 [store] use hasCache to minimize pendingRef pool
  go/libraries/doltcore/remotestorage/chunk_store.go
  go/store/chunks/chunk_store.go
  go/store/chunks/chunk_store_common_test.go
  go/store/chunks/memory_store.go
  go/store/chunks/test_utils.go
  go/store/nbs/benchmarks/block_store_benchmarks.go
  go/store/nbs/benchmarks/file_block_store.go
  go/store/nbs/block_store_test.go
  go/store/nbs/generational_chunk_store.go
  go/store/nbs/store_test.go
  go/store/nbs/table_set.go
  go/store/prolly/tree/node_store.go
  go/store/spec/spec_test.go
  go/store/types/value_store.go
  go/store/valuefile/file_value_store.go
  go/store/valuefile/value_file.go
Labels: correctness_approved

#7683 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#7688 add alternative type check for auto_increment type validation
  go/libraries/doltcore/schema/schema_impl.go
Labels: correctness_approved

#7691 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
Labels: gms-bump, keep-alive, correctness_approved

#7679 `dolt_verify_constraints()` support for all constraint types
  go/libraries/doltcore/merge/merge.go
  go/libraries/doltcore/merge/merge_prolly_rows.go
  go/libraries/doltcore/merge/merge_rows.go
  go/libraries/doltcore/sqle/dprocedures/dolt_verify_constraints.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_merge.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_verify_constraints.go
Labels: correctness_approved

#7693 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/enginetest/dolt_queries.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_schema_override.go
  go/libraries/doltcore/sqle/enginetest/privilege_test.go
  integration-tests/bats/create-views.bats
  integration-tests/mysql-client-tests/node/index.js
  integration-tests/mysql-client-tests/node/workbenchTests/table.js
  integration-tests/mysql-client-tests/python/mysql.connector-test.py
  integration-tests/mysql-client-tests/python/pymysql-test.py
  integration-tests/mysql-client-tests/python/sqlalchemy-test.py
  integration-tests/mysql-client-tests/r/rmariadb-test.r
  integration-tests/mysql-client-tests/r/rmysql-test.r
Labels: gms-bump, keep-alive, correctness_approved

#7701 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/binlogreplication/binlog_replication_test.go
Labels: gms-bump, keep-alive, correctness_approved

#7707 go/libraries/doltcore/dbfactory, misc: Ensure we close a *grpc.ClientConn when we are done with it.
  go/cmd/dolt/commands/credcmds/check.go
  go/cmd/dolt/commands/credcmds/import.go
  go/cmd/dolt/commands/send_metrics.go
  go/cmd/dolt/commands/sqlserver/server.go
  go/libraries/doltcore/dbfactory/grpc.go
  go/libraries/doltcore/remotestorage/chunk_store.go
  go/libraries/doltcore/sqle/cluster/controller.go
  go/libraries/doltcore/sqle/cluster/mysqldb_persister.go
Labels: correctness_approved

#7689 Allow 'old' versions of Dolt to handle future table file versions
  go/cmd/dolt/dolt.go
  go/libraries/doltcore/doltdb/doltdb.go
  go/libraries/doltcore/env/multi_repo_env.go
  go/store/nbs/table.go
  go/store/nbs/table_index.go
  go/store/nbs/table_index_test.go
  go/store/nbs/table_reader.go
Labels: correctness_approved

#7713 [statspro] Avoid duplicating branch suffix when resolving stats database
  go/libraries/doltcore/sqle/enginetest/stats_queries.go
  go/libraries/doltcore/sqle/statspro/analyze.go
  go/libraries/doltcore/sqle/statspro/auto_refresh.go
Labels: correctness_approved

#7708 chore: fix function names in comment
  go/cmd/dolt/commands/dump.go
  go/cmd/dolt/commands/utils.go
  go/libraries/doltcore/doltdb/foreign_key_serialization.go
Labels: contribution

#7719 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#7699 Add per-table locking for AutoIncrementTracker
  go/libraries/doltcore/sqle/dsess/autoincrement_tracker.go
  go/libraries/doltcore/sqle/dsess/mutexmap/mutexmap.go
Labels: correctness_approved

#7711 match mysql fk name generation
  go/go.mod
  go/go.sum
  go/libraries/doltcore/doltdb/foreign_key_coll.go
  go/libraries/doltcore/doltdb/foreign_key_test.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_merge.go
  go/libraries/doltcore/sqle/enginetest/dolt_transaction_queries.go
  integration-tests/bats/diff.bats
  integration-tests/bats/foreign-keys.bats
  integration-tests/mysql-client-tests/node/workbenchTests/diffs.js
  integration-tests/mysql-client-tests/node/workbenchTests/table.js
Labels: correctness_approved

#7721 Improve error messaging when encountering a primary key schema change during a merge.
  go/libraries/doltcore/merge/merge_schema.go
  go/libraries/doltcore/merge/schema_integration_test.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_merge.go
  integration-tests/bats/cherry-pick.bats
  integration-tests/bats/primary-key-changes.bats
  integration-tests/bats/sql-cherry-pick.bats
Labels: correctness_approved

#7706 [store] use struct{} as a value in a hashset
  go/store/datas/commit.go
  go/store/nbs/frag/main.go
  go/store/nbs/util.go
Labels: contribution

#7718 [store] use struct{} as a value in a hashset
  go/store/datas/commit.go
  go/store/nbs/frag/main.go
  go/store/nbs/util.go
Labels: correctness_approved

#7724 Move Version
  .github/workflows/cd-release-pgo.yaml
  go/cmd/dolt/dolt.go
  go/cmd/dolt/doltversion/version.go
Labels: correctness_approved

#7670 Add name on cd-release-pgo workflows
  .github/workflows/cd-release-pgo.yaml
Labels: contribution

#7729 [no-release-notes] Remove unused test and bump GMS version.
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/enginetest/dolt_procedure_queries.go
Labels: correctness_approved

#7703 [no-release-notes] skip failed test files for Doltgres sysbench benchmark
  go/performance/utils/benchmark_runner/doltgres.go
Labels: correctness_approved

#7733 [no-release-notes] fix sysbench test cleanup
  go/performance/utils/benchmark_runner/sysbench.go
Labels: correctness_approved

#7704 Implement `traditional` auto-increment lock mode hold the lock for the duration of the insert iter.
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/dsess/autoincrement_tracker.go
  go/libraries/doltcore/sqle/dsess/globalstate.go
  go/libraries/doltcore/sqle/dsess/mutexmap/mutexmap.go
  go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
  go/libraries/doltcore/sqle/globalstate/auto_increment_tracker.go
  go/libraries/doltcore/sqle/sqlutil/static_errors.go
  go/libraries/doltcore/sqle/writer/noms_table_writer.go
  go/libraries/doltcore/sqle/writer/prolly_table_writer.go
  integration-tests/bats/auto_increment_lock_modes.bats
  integration-tests/bats/sql-server.bats
Labels: correctness_approved

#7730 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#7734 [no-release-notes] unskipping tests and bumping
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/enginetest/dolt_procedure_queries.go
Labels: correctness_approved

#7739 Fix some comments
  go/cmd/dolt/commands/commit.go
  go/cmd/dolt/commands/tblcmds/import.go
  go/libraries/doltcore/doltdb/foreign_key_serialization.go
  go/libraries/doltcore/doltdb/ignore.go
  go/libraries/doltcore/doltdb/stash.go
  go/libraries/doltcore/dtestutils/sql_server_driver/server.go
  go/libraries/doltcore/env/actions/reset.go
Labels: contribution

#7741 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#7736 [no-release-notes] fix stats races
  go/libraries/doltcore/sqle/enginetest/dolt_harness.go
Labels: correctness_approved

#7743 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#7750 [auto-bump] [no-release-notes] dependency by jennifersp
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#7759 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#7757 chore: fix some comments
  go/libraries/doltcore/doltdb/durable/index.go
  go/libraries/doltcore/dtestutils/data.go
  go/libraries/doltcore/dtestutils/sql_server_driver/server.go
  go/libraries/doltcore/env/actions/remotes.go
  go/libraries/doltcore/env/grpc_dial_provider.go
  go/performance/continuous_integration/SysbenchDockerfile
  go/serial/workingset.fbs
Labels: contribution

#7761 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#7771 Don't generate new tags for column type changes
  go/libraries/doltcore/sqle/dolt_patch_table_function.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_diff.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_merge.go
  go/libraries/doltcore/sqle/tables.go
  integration-tests/MySQLDockerfile
  integration-tests/bats/column_tags.bats
Labels: correctness_approved

#7769 `AUTO_INCREMENT` columns have `NOT NULL` constraint
  go/go.mod
  go/go.sum
  go/libraries/doltcore/schema/column.go
Labels: correctness_approved

#7731 [nbs] getMany read planning and parallelize
  go/store/nbs/journal_chunk_source.go
  go/store/nbs/journal_writer.go
Labels: correctness_approved

#7777 [auto-bump] [no-release-notes] dependency by max-hoffman
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#7775 Allow updating conflict table even if the underlying table schema changed.
  go/libraries/doltcore/merge/schema_integration_test.go
  go/libraries/doltcore/sqle/dtables/conflicts_tables_prolly.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_merge.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_schema_merge.go
  go/libraries/doltcore/sqle/writer/prolly_index_writer.go
Labels: correctness_approved

#7768 fix: fix function name
  go/libraries/doltcore/merge/schema_merge_test.go
Labels: contribution

#7782 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#7784 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#7790 chore: fix some function names
  go/libraries/doltcore/sqle/index/dolt_map_iter.go
  go/performance/utils/benchmark_runner/results_test.go
  go/store/chunks/memory_store.go
  go/store/config/resolver.go
Labels: contribution

#7786 [no-release-notes] go/utils/publishrelease/buildpgobinaries.sh: Update for CGO.
  README.md
  go/Godeps/LICENSES
  go/cmd/dolt/commands/admin/admin.go
  go/cmd/dolt/commands/admin/zstd.go
  go/go.mod
  go/go.sum
  go/utils/3pdeps/MUSL_COPYRIGHT
  go/utils/3pdeps/main.go
  go/utils/publishrelease/buildbinaries.sh
  go/utils/publishrelease/buildpgobinaries.sh
  go/utils/remotesrv/main.go
  integration-tests/DataDumpLoadDockerfile
  integration-tests/bats/zstd.bats
Labels: correctness_approved

#7791 [auto-bump] [no-release-notes] dependency by jennifersp
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#7792 Fix nil write session panic
  go/libraries/doltcore/sqle/dprocedures/dolt_conflicts_resolve.go
  go/libraries/doltcore/sqle/dsess/database_session_state.go
  go/libraries/doltcore/sqle/dsess/session.go
  go/libraries/doltcore/sqle/dtables/docs_table.go
  go/libraries/doltcore/sqle/dtables/ignore_table.go
  go/libraries/doltcore/sqle/tables.go
  integration-tests/go-sql-server-driver/tests/sql-server-cluster.yaml
Labels: correctness_approved

#7766 chore: use errors.New to replace fmt.Errorf with no parameters
  go/cmd/dolt/cli/arg_parser_helpers.go
  go/cmd/dolt/cli/cli_context.go
  go/cmd/dolt/cli/credentials.go
  go/cmd/dolt/commands/cnfcmds/cat.go
  go/cmd/dolt/commands/cnfcmds/conflictsplitter.go
  go/cmd/dolt/commands/diff.go
  go/cmd/dolt/commands/docscmds/write.go
  go/cmd/dolt/commands/engine/jwtplugin.go
  go/cmd/dolt/commands/engine/sql_print.go
  go/cmd/dolt/commands/sqlserver/creds.go
Labels: contribution

#7776 `dolt_history` tables: Issue a warning when types have changed
  go/libraries/doltcore/sqle/enginetest/dolt_queries.go
  go/libraries/doltcore/sqle/history_table.go
Labels: correctness_approved

#7802 adding `--name-only` option for `dolt diff`
  go/cmd/dolt/cli/cli_context.go
  go/cmd/dolt/commands/diff.go
  integration-tests/bats/diff.bats
Labels: correctness_approved
