Repository dolthub/dolt, pull requests merged in 2024-06, with the labels that each got.

#7937 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#7941 Bug fix for AllSchemas method for schemas
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/database.go
Labels: correctness_approved

#7940 dolt sql slash cmds
  go/cmd/dolt/cli/cli_context.go
  go/cmd/dolt/commands/add.go
  go/cmd/dolt/commands/branch.go
  go/cmd/dolt/commands/checkout.go
  go/cmd/dolt/commands/commit.go
  go/cmd/dolt/commands/diff.go
  go/cmd/dolt/commands/log.go
  go/cmd/dolt/commands/merge.go
  go/cmd/dolt/commands/reset.go
  go/cmd/dolt/commands/sql.go
  go/cmd/dolt/commands/sql_slash.go
  go/cmd/dolt/commands/status.go
  go/cmd/dolt/commands/utils.go
  go/store/util/outputpager/page_output.go
  integration-tests/bats/sql-shell-slash-cmds.expect
  integration-tests/bats/sql-shell.bats
Labels: correctness_approved

#7951 [auto-bump] [no-release-notes] dependency by nicktobey
  go/Godeps/LICENSES
  go/go.mod
  go/go.sum
  integration-tests/bats/validation.bats
Labels: gms-bump, keep-alive, correctness_approved

#7954 [auto-bump] [no-release-notes] dependency by fulghum
  go/Godeps/LICENSES
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#7952 Made drop table work with search path
  go/libraries/doltcore/sqle/database.go
Labels: correctness_approved

#7955 [types] cache frequently read value store chunks (like working set roots)
  go/store/types/incremental_test.go
  go/store/types/list_test.go
  go/store/types/value_store.go
  go/store/types/value_store_test.go
Labels: correctness_approved

#7967 go/libraries/doltcore/remotesrv: grpc.go: Respect X-Forwarded-Proto when generating HTTP download links in the gRPC server.
  go/libraries/doltcore/remotesrv/grpc.go
  go/libraries/doltcore/remotesrv/grpc_test.go
Labels: correctness_approved

#7969 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/tables.go
Labels: gms-bump, keep-alive, correctness_approved

#7965 Bug fix: Allow unresolved FKs to merge with resolved FKs
  go/libraries/doltcore/doltdb/foreign_key_coll.go
  go/libraries/doltcore/merge/merge_schema.go
  go/libraries/doltcore/sqle/enginetest/dolt_transaction_queries.go
Labels: correctness_approved

#7979 Allow pulling from a remote if the only changes are to ignored tables.
  go/libraries/doltcore/env/actions/checkout.go
  go/libraries/doltcore/sqle/dprocedures/dolt_pull.go
  integration-tests/bats/pull.bats
Labels: correctness_approved

#7981 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
  go/libraries/doltcore/doltdb/foreign_key_test.go
  go/libraries/doltcore/merge/schema_integration_test.go
  go/libraries/doltcore/sqle/enginetest/dolt_branch_queries.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_diff.go
  go/libraries/doltcore/sqle/enginetest/dolt_transaction_queries.go
  go/libraries/doltcore/sqle/enginetest/stats_queries.go
  go/libraries/doltcore/sqle/sqlddl_test.go
  integration-tests/bats/constraint-violations.bats
  integration-tests/bats/diff.bats
  integration-tests/bats/foreign-keys.bats
  integration-tests/bats/index.bats
  integration-tests/bats/stats.bats
Labels: gms-bump, keep-alive, correctness_approved

#7975 implemented dolt_hashof_db function
  go/libraries/doltcore/sqle/dfunctions/hashof_database.go
  go/libraries/doltcore/sqle/dfunctions/init.go
  go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries.go
Labels: correctness_approved

#7983 [auto-bump] [no-release-notes] dependency by nicktobey
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#7985 [auto-bump] [no-release-notes] dependency by nicktobey
  go/go.mod
  go/go.sum
  go/libraries/doltcore/merge/violations_fk_prolly.go
  go/libraries/doltcore/merge/violations_unique_prolly.go
  go/libraries/doltcore/sqle/json/noms_json_value.go
  go/libraries/doltcore/sqle/statspro/dolt_stats.go
Labels: gms-bump, keep-alive, correctness_approved

#7987 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#7990 support `auto_increment` on temporary tables
  go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries.go
  go/libraries/doltcore/sqle/temp_table.go
Labels: correctness_approved

#7914 Feature: Binlog replication
  go/cmd/dolt/commands/engine/sqlengine.go
  go/cmd/dolt/commands/sqlserver/server.go
  go/libraries/doltcore/doltdb/doltdb.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_primary_controller.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_primary_hooks.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_primary_streamer.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_primary_test.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_producer.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_replication_test.go
  go/libraries/doltcore/sqle/binlogreplication/system_variable_utils.go
  go/libraries/doltcore/sqle/database_provider.go
  go/libraries/doltcore/sqle/dsess/session.go
  go/libraries/doltcore/sqle/system_variables.go
  integration-tests/bats/config.bats
  integration-tests/bats/global-args.bats
  integration-tests/bats/replication-multidb.bats
Labels: correctness_approved

#7966 [prolly] filteredIter optimization for exact prefix ranges
  go/libraries/doltcore/sqle/index/dolt_index.go
  go/store/prolly/map_test.go
  go/store/prolly/tuple_map.go
  go/store/prolly/tuple_range.go
  go/store/prolly/tuple_range_test.go
Labels: correctness_approved

#8000 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, keep-alive, correctness_approved

#7999 Generate `TEMPORARY TABLE` tags the same as normal `TABLE`s
  go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries.go
  go/libraries/doltcore/sqle/temp_table.go
Labels: correctness_approved

#8001 Feature: Support `restore` subcommand in `dolt_backup()`
  go/libraries/doltcore/sqle/dprocedures/dolt_backup.go
  integration-tests/bats/sql-backup.bats
Labels: correctness_approved

#8007 [auto-bump] [no-release-notes] dependency by nicktobey
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/enginetest/dolt_queries_merge.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_verify_constraints.go
Labels: gms-bump, correctness_approved

#7912 Add `IndexedJsonDocument`, a `JSONWrapper` implementation that stores JSON documents in a prolly tree with probabilistic hashing.
  go/Godeps/LICENSES
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/binlogreplication/binlog_json_serialization.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_type_serialization.go
  go/store/prolly/message/item_access.go
  go/store/prolly/tree/blob_builder.go
  go/store/prolly/tree/chunker.go
  go/store/prolly/tree/json_chunker.go
  go/store/prolly/tree/json_cursor.go
  go/store/prolly/tree/json_indexed_document.go
  go/store/prolly/tree/json_indexed_document_test.go
  go/store/prolly/tree/json_location.go
  go/store/prolly/tree/json_scanner.go
  go/store/prolly/tree/node_builder.go
  go/store/prolly/tree/node_cursor.go
  go/store/prolly/tree/node_splitter.go
  go/store/prolly/tree/prolly_fields.go
Labels: correctness_approved

#8014 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8019 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8020 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8021 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8018 Archive DDict cache and multi-file bug fixes
  go/store/nbs/archive_build.go
  go/store/nbs/archive_chunk_source.go
  go/store/nbs/archive_reader.go
  go/store/nbs/archive_test.go
  integration-tests/bats/archive.bats
Labels: correctness_approved

#7963 Create pg_catalog by default for Doltgres
  go/libraries/doltcore/sqle/database.go
  go/libraries/doltcore/sqle/database_provider.go
Labels: correctness_approved

#8026 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8027 [no-release-notes] bump for stats perf
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/statspro/update.go
Labels: correctness_approved

#8025 [prolly] Float keyRange increment bug
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
  go/libraries/doltcore/sqle/index/dolt_index.go
  go/store/prolly/map_test.go
  go/store/prolly/tuple_range.go
  go/store/prolly/tuple_range_test.go
Labels: correctness_approved

#8015 [no-release-notes] Initialize sysbench statistics, for perf
  go/performance/utils/benchmark_runner/sysbench.go
  go/performance/utils/benchmark_runner/tpcc.go
Labels: correctness_approved

#8043 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8045 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8046 [no-release-notes] Engine test framework for Doltgres
  go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
  go/libraries/doltcore/sqle/enginetest/dolt_engine_tests.go
  go/libraries/doltcore/sqle/enginetest/dolt_harness.go
  go/libraries/doltcore/sqle/enginetest/dolt_server_test.go
  go/libraries/doltcore/sqle/enginetest/dolt_server_tests.go
Labels: correctness_approved

#8041 Truncate MCVs
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/enginetest/stats_queries.go
  go/libraries/doltcore/sqle/statsnoms/load.go
  go/libraries/doltcore/sqle/statspro/update.go
  go/libraries/doltcore/sqle/statspro/update_test.go
  integration-tests/bats/stats.bats
Labels: correctness_approved

#8048 [auto-bump] [no-release-notes] dependency by max-hoffman
  go/go.mod
  go/go.sum
Labels: gms-bump

#8049 [no-release-notes] follow up fixes to mcv calculation
  go/libraries/doltcore/sqle/statspro/update.go
  go/libraries/doltcore/sqle/statspro/update_test.go
  integration-tests/bats/stats.bats
Labels: correctness_approved

#8056 Revert "Merge pull request #7940 from dolthub/macneale4/slash-cmds"
  go/cmd/dolt/cli/cli_context.go
  go/cmd/dolt/commands/add.go
  go/cmd/dolt/commands/branch.go
  go/cmd/dolt/commands/checkout.go
  go/cmd/dolt/commands/commit.go
  go/cmd/dolt/commands/diff.go
  go/cmd/dolt/commands/log.go
  go/cmd/dolt/commands/merge.go
  go/cmd/dolt/commands/reset.go
  go/cmd/dolt/commands/sql.go
  go/cmd/dolt/commands/sql_slash.go
  go/cmd/dolt/commands/status.go
  go/cmd/dolt/commands/utils.go
  go/store/util/outputpager/page_output.go
  integration-tests/bats/sql-shell-slash-cmds.expect
  integration-tests/bats/sql-shell.bats
Labels: correctness_approved

#8055 [no-release-notes] need stats to run on dolt servers
  go/performance/utils/benchmark_runner/sysbench.go
  go/performance/utils/benchmark_runner/tpcc.go
Labels: correctness_approved

#8036 [statspro] Bootstrap database statistics once on startup
  go/libraries/doltcore/env/actions/branch.go
  go/libraries/doltcore/sqle/dsess/variables.go
  go/libraries/doltcore/sqle/enginetest/dolt_engine_tests.go
  go/libraries/doltcore/sqle/statsnoms/iter.go
  go/libraries/doltcore/sqle/statsnoms/load.go
  go/libraries/doltcore/sqle/statsnoms/write.go
  go/libraries/doltcore/sqle/statspro/analyze.go
  go/libraries/doltcore/sqle/statspro/configure.go
  go/libraries/doltcore/sqle/system_variables.go
  integration-tests/bats/stats.bats
Labels: correctness_approved

#8057 [auto-bump] [no-release-notes] dependency by nicktobey
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8063 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/binlogreplication/binlog_primary_controller.go
Labels: gms-bump, keep-alive, correctness_approved

#8064 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/binlogreplication/binlog_replica_applier.go
  go/libraries/doltcore/sqle/enginetest/dolt_engine_tests.go
  go/libraries/doltcore/sqle/enginetest/dolt_harness.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries.go
  go/libraries/doltcore/sqle/enginetest/dolt_server_tests.go
  go/libraries/doltcore/sqle/integration_test/database_revision_test.go
  integration-tests/bats/sql-multi-db.bats
  integration-tests/bats/sql.bats
  integration-tests/go-sql-server-driver/tests/sql-server-cluster.yaml
  integration-tests/go-sql-server-driver/tests/sql-server-orig.yaml
  integration-tests/mysql-client-tests/node/workbenchTests/databases.js
Labels: gms-bump, keep-alive

#8060 [no-release-notes] add bindings to `AssertErr` and `AssertErrCtx` test methods
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/enginetest/branch_control_test.go
  go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
  go/libraries/doltcore/sqle/enginetest/privilege_test.go
  go/libraries/doltcore/sqle/enginetest/stats_queries.go
  integration-tests/bats/import-create-tables.bats
Labels: correctness_approved

#8067 [auto-bump] [no-release-notes] dependency by Hydrocharged
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8062 add SchemaName to DatabaseSchema interface
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/binlogreplication/binlog_replica_applier.go
  go/libraries/doltcore/sqle/database.go
  go/libraries/doltcore/sqle/database_provider.go
  go/libraries/doltcore/sqle/enginetest/dolt_engine_tests.go
  go/libraries/doltcore/sqle/enginetest/dolt_harness.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries.go
  go/libraries/doltcore/sqle/enginetest/dolt_server_tests.go
  go/libraries/doltcore/sqle/integration_test/database_revision_test.go
  integration-tests/bats/sql-multi-db.bats
  integration-tests/bats/sql.bats
  integration-tests/go-sql-server-driver/tests/sql-server-cluster.yaml
  integration-tests/go-sql-server-driver/tests/sql-server-orig.yaml
  integration-tests/mysql-client-tests/node/workbenchTests/databases.js
Labels: correctness_approved

#7783 [no-release-notes] tracing infra
  go/cmd/dolt/commands/sql.go
  go/go.mod
  go/go.sum
  go/libraries/doltcore/remotesrv/dbcache.go
  go/libraries/doltcore/remotesrv/grpc.go
  go/performance/import_benchmarker/testdef.go
  go/performance/utils/benchmark_runner/tpcc.lua
  go/store/nbs/archive_chunk_source.go
  go/store/nbs/empty_chunk_source.go
  go/store/nbs/generational_chunk_store.go
  go/store/nbs/journal.go
  go/store/nbs/journal_chunk_source.go
  go/store/nbs/journal_test.go
  go/store/nbs/journal_writer.go
  go/store/nbs/journal_writer_test.go
  go/store/nbs/store.go
  go/store/nbs/table.go
  go/store/nbs/table_reader.go
Labels: correctness_approved

#8077 /go/libraries/doltcore/remotestorage/chunk_fetcher.go: fix nil pointer
  go/libraries/doltcore/remotestorage/chunk_fetcher.go
Labels: correctness_approved

#8073 Added schema to index creation
  go/libraries/doltcore/sqle/database.go
  go/libraries/doltcore/sqle/tables.go
Labels: correctness_approved

#8080 Re-enable doltgres sysbench scripts
  go/performance/utils/benchmark_runner/sysbench_config.go
Labels: correctness_approved

#8081 Fixed keyless secondary indexing for Doltgres
  go/store/prolly/tuple_map.go
  go/store/val/extended_comparator.go
Labels: correctness_approved

#8078 Archive index rework to make loading faster
  go/store/nbs/archive.go
  go/store/nbs/archive_build.go
  go/store/nbs/archive_reader.go
  go/store/nbs/archive_test.go
  go/store/nbs/archive_writer.go
Labels: correctness_approved

#8083 [auto-bump] [no-release-notes] dependency by nicktobey
  go/go.mod
  go/go.sum
  go/libraries/doltcore/merge/merge_prolly_rows.go
  go/libraries/doltcore/merge/three_way_json_differ.go
  go/store/prolly/tree/json_indexed_document.go
Labels: gms-bump, correctness_approved
