Repository dolthub/dolt, pull requests merged in 2024-03, with the labels that each got.

#7560 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
  go/libraries/doltcore/schema/encoding/integration_test.go
Labels: gms-bump, keep-alive, correctness_approved

#7562 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#7566 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#7567 [no-release-notes] TPC-C CI runs longer
  go/performance/utils/benchmark_runner/tpcc_tests.go
Labels: correctness_approved

#7553 go/store/datas/pull: Create a PullChunkTracker for keeping track of what to pull.
  go/store/datas/pull/pull_chunk_tracker.go
  go/store/datas/pull/pull_chunk_tracker_test.go
  go/store/datas/pull/puller.go
Labels: correctness_approved

#7573 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#7575 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#7581 fix bad charset tests and dolt table import schema
  go/go.mod
  go/go.sum
  go/libraries/doltcore/mvdata/engine_table_writer.go
  go/libraries/doltcore/schema/encoding/integration_test.go
Labels: correctness_approved

#7584 fix comparison for `[]byte`
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/index/dolt_index.go
Labels: correctness_approved

#7539 Feature: Schema overriding
  go/libraries/doltcore/doltdb/table.go
  go/libraries/doltcore/sqle/database.go
  go/libraries/doltcore/sqle/database_provider.go
  go/libraries/doltcore/sqle/dsess/variables.go
  go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_schema_override.go
  go/libraries/doltcore/sqle/history_table.go
  go/libraries/doltcore/sqle/schema_override.go
  go/libraries/doltcore/sqle/system_variables.go
  go/libraries/doltcore/sqle/tables.go
Labels: correctness_approved

#7587 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#7590 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#7591 go/store/datas/pull: Revert puller changes from 1.34.0 until we investigate changes in resource utilization.
  go/store/datas/pull/pull_chunk_tracker.go
  go/store/datas/pull/pull_chunk_tracker_test.go
  go/store/datas/pull/puller.go
Labels: correctness_approved

#7595 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#7598 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#7606 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#7614 [no-release-notes] Fixed breaking interface changes from GMS
  go/cmd/dolt/commands/sqlserver/server.go
  go/go.mod
  go/go.sum
Labels: correctness_approved

#7609 Drop the nbs.addr type in favor of hash.Hash type
  go/store/hash/base32.go
  go/store/hash/hash.go
  go/store/nbs/aws_chunk_source.go
  go/store/nbs/aws_table_persister.go
  go/store/nbs/aws_table_persister_test.go
  go/store/nbs/bs_manifest.go
  go/store/nbs/bs_persister.go
  go/store/nbs/chunk_source_adapter.go
  go/store/nbs/cmp_chunk_table_writer.go
  go/store/nbs/conjoiner.go
  go/store/nbs/conjoiner_test.go
  go/store/nbs/dynamo_manifest.go
  go/store/nbs/dynamo_manifest_test.go
  go/store/nbs/empty_chunk_source.go
  go/store/nbs/file_manifest.go
  go/store/nbs/file_manifest_test.go
  go/store/nbs/file_table_persister.go
  go/store/nbs/file_table_persister_test.go
  go/store/nbs/file_table_reader.go
  go/store/nbs/gc_copier.go
  go/store/nbs/index_transformer.go
  go/store/nbs/index_transformer_test.go
  go/store/nbs/journal.go
  go/store/nbs/journal_chunk_source.go
  go/store/nbs/journal_index_record.go
  go/store/nbs/journal_index_record_test.go
  go/store/nbs/journal_record.go
  go/store/nbs/journal_record_test.go
  go/store/nbs/journal_test.go
  go/store/nbs/journal_writer.go
  go/store/nbs/journal_writer_test.go
  go/store/nbs/manifest.go
  go/store/nbs/mem_table.go
  go/store/nbs/mem_table_test.go
  go/store/nbs/must_test.go
  go/store/nbs/no_conjoin_bs_persister.go
  go/store/nbs/root_tracker_test.go
  go/store/nbs/s3_fake_test.go
  go/store/nbs/s3_table_reader.go
  go/store/nbs/store.go
  go/store/nbs/store_test.go
  go/store/nbs/table.go
  go/store/nbs/table_index.go
  go/store/nbs/table_index_test.go
  go/store/nbs/table_persister.go
  go/store/nbs/table_reader.go
  go/store/nbs/table_set.go
  go/store/nbs/table_set_test.go
  go/store/nbs/table_test.go
  go/store/nbs/table_writer.go
  go/store/nbs/util.go
Labels: correctness_approved

#7615 [sqle] Allow bindvars in most function constructors
  go/libraries/doltcore/sqle/dolt_diff_stat_table_function.go
  go/libraries/doltcore/sqle/dolt_diff_summary_table_function.go
  go/libraries/doltcore/sqle/dolt_diff_table_function.go
  go/libraries/doltcore/sqle/dolt_patch_table_function.go
  go/libraries/doltcore/sqle/dolt_schema_diff_table_function.go
  go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_diff.go
Labels: correctness_approved

#7592 go/store/datas/pull: Restore puller optimization for parallel HasMany calls. Fix crash in pull_chunk_tracker.
  go/store/datas/pull/pull_chunk_tracker.go
  go/store/datas/pull/pull_chunk_tracker_test.go
  go/store/datas/pull/puller.go
Labels: correctness_approved

#7616 [sqle] don't panic reading history table
  go/libraries/doltcore/sqle/database.go
  go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
  go/libraries/doltcore/sqle/enginetest/prepared_queries.go
Labels: correctness_approved

#7610 Optimize full-text to selectively rebuild
  go/libraries/doltcore/merge/fulltext_rebuild.go
  go/libraries/doltcore/merge/fulltext_table.go
  go/libraries/doltcore/merge/merge.go
  go/libraries/doltcore/schema/index_coll.go
  integration-tests/bats/fulltext.bats
Labels: correctness_approved

#7582 add dolt_hashof_table func and dolt_hashof (Deprecate hashof)
  go/libraries/doltcore/sqle/dfunctions/hashof.go
  go/libraries/doltcore/sqle/dfunctions/hashof_table.go
  go/libraries/doltcore/sqle/dfunctions/init.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries.go
Labels: correctness_approved

#7572 go/store/datas/pull: pull_table_file_writer.go: Optimize pull/push to allow for concurrent table file uploads.
  go/go.mod
  go/go.sum
  go/store/datas/pull/pull_table_file_writer.go
  go/store/datas/pull/pull_table_file_writer_test.go
  go/store/datas/pull/puller.go
  integration-tests/go-sql-server-driver/go.mod
  integration-tests/go-sql-server-driver/go.sum
Labels: correctness_approved

#7629 refactor tablespec
  go/go.mod
  go/go.sum
  go/libraries/doltcore/mvdata/engine_table_writer.go
  go/libraries/doltcore/schema/typeinfo/blobstring.go
  go/libraries/doltcore/schema/typeinfo/enum.go
  go/libraries/doltcore/schema/typeinfo/set.go
  go/libraries/doltcore/schema/typeinfo/varstring.go
  go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
  go/libraries/doltcore/sqle/enginetest/dolt_harness.go
  go/libraries/doltcore/sqle/index/key_builder.go
  go/libraries/doltcore/sqle/sqlfmt/schema_fmt.go
  go/libraries/doltcore/sqle/sqlutil/schema.go
  go/libraries/doltcore/sqle/tables.go
  go/libraries/doltcore/sqle/writer/prolly_table_writer.go
Labels: correctness_approved

#7632 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#7579 use system variable interface
  go/cmd/dolt/commands/sql_test.go
  go/cmd/dolt/commands/sqlserver/server.go
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/cluster/controller.go
  go/libraries/doltcore/sqle/dsess/dolt_session_test.go
  go/libraries/doltcore/sqle/dsess/session.go
  go/libraries/doltcore/sqle/dsess/variables.go
  go/libraries/doltcore/sqle/replication_test.go
  go/libraries/doltcore/sqle/schema_table.go
  go/libraries/doltcore/sqle/system_variables.go
Labels: correctness_approved

#7637 `innodb_autoinc_lock_mode` tests
  go/go.mod
  go/go.sum
  integration-tests/bats/sql-server.bats
Labels: correctness_approved

#7643 [no release notes] odd n ends clean up
  go/store/nbs/cmp_chunk_table_writer.go
  go/store/nbs/journal.go
  go/store/nbs/table.go
  go/store/nbs/table_index.go
  go/store/nbs/table_reader.go
Labels: correctness_approved

#7618 [no-release-notes] Refactored config reading / initialization
  go/cmd/dolt/commands/sqlserver/command_line_config.go
  go/cmd/dolt/commands/sqlserver/serverconfig.go
  go/cmd/dolt/commands/sqlserver/sqlserver.go
  go/cmd/dolt/commands/sqlserver/yaml_config.go
  go/cmd/dolt/dolt.go
Labels: correctness_approved

#7647 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#7648 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#7644 go/store/datas/pull: pull_chunk_fetcher: Move chunk fetching to a streaming interface instead of batch.
  go/store/datas/pull/pull_chunk_fetcher.go
  go/store/datas/pull/pull_chunk_fetcher_test.go
  go/store/datas/pull/pull_chunk_tracker.go
  go/store/datas/pull/pull_chunk_tracker_test.go
  go/store/datas/pull/puller.go
Labels: correctness_approved

#7652 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#7558 Statistics for multiple branches
  go/Godeps/LICENSES
  go/cmd/dolt/commands/engine/sqlengine.go
  go/go.mod
  go/go.sum
  go/libraries/doltcore/dbfactory/file.go
  go/libraries/doltcore/doltdb/doltdb.go
  go/libraries/doltcore/migrate/environment.go
  go/libraries/doltcore/ref/ref.go
  go/libraries/doltcore/ref/stats_ref.go
  go/libraries/doltcore/schema/statistic.go
  go/libraries/doltcore/sqle/cluster/initdbhook.go
  go/libraries/doltcore/sqle/database.go
  go/libraries/doltcore/sqle/database_provider.go
  go/libraries/doltcore/sqle/dprocedures/stats_funcs.go
  go/libraries/doltcore/sqle/dsess/variables.go
  go/libraries/doltcore/sqle/dtables/statistics_table.go
  go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
  go/libraries/doltcore/sqle/enginetest/dolt_harness.go
  go/libraries/doltcore/sqle/enginetest/privilege_test.go
  go/libraries/doltcore/sqle/enginetest/stats_queries.go
  go/libraries/doltcore/sqle/logictest/dolt/doltharness.go
  go/libraries/doltcore/sqle/stats/auto_refresh.go
  go/libraries/doltcore/sqle/stats/stats_provider.go
  go/libraries/doltcore/sqle/stats/write.go
  go/libraries/doltcore/sqle/statsnoms/database.go
  go/libraries/doltcore/sqle/statsnoms/iter.go
  go/libraries/doltcore/sqle/statsnoms/load.go
  go/libraries/doltcore/sqle/statsnoms/write.go
  go/libraries/doltcore/sqle/statspro/analyze.go
  go/libraries/doltcore/sqle/statspro/auto_refresh.go
  go/libraries/doltcore/sqle/statspro/configure.go
  go/libraries/doltcore/sqle/statspro/dolt_stats.go
  go/libraries/doltcore/sqle/statspro/initdbhook.go
  go/libraries/doltcore/sqle/statspro/interface.go
  go/libraries/doltcore/sqle/statspro/stats_provider.go
  go/libraries/doltcore/sqle/statspro/update.go
  go/libraries/doltcore/sqle/statspro/update_test.go
  go/libraries/doltcore/sqle/system_variables.go
  go/store/prolly/tuple_mutable_map.go
  integration-tests/bats/stats.bats
Labels: correctness_approved

#7659 Don't panic for conflicts in the `dolt pull` command
  go/cmd/dolt/commands/merge.go
  integration-tests/bats/fetch.bats
  integration-tests/bats/helper/local-remote.bash
  integration-tests/bats/pull.bats
  integration-tests/bats/push.bats
Labels: correctness_approved

#7655 [no-release-notes] /{.github,go,integration-tests}: bump go version
  .github/workflows/bump-dependency.yaml
  .github/workflows/cd-release-pgo.yaml
  .github/workflows/ci-bats-macos.yaml
  .github/workflows/ci-bats-unix-remote.yaml
  .github/workflows/ci-bats-unix.yaml
  .github/workflows/ci-bats-windows.yaml
  .github/workflows/ci-check-repo.yaml
  .github/workflows/ci-compatibility-tests.yaml
  .github/workflows/ci-go-race-tests.yaml
  .github/workflows/ci-go-tests.yaml
  .github/workflows/ci-lambdabats-unix.yaml
  .github/workflows/ci-sql-server-integration-tests.yaml
  .github/workflows/import-perf.yaml
  .github/workflows/merge-perf.yaml
  .github/workflows/sysbench-perf.yaml
  go/go.mod
  go/performance/continuous_integration/SysbenchDockerfile
  integration-tests/DataDumpLoadDockerfile
  integration-tests/MySQLDockerfile
  integration-tests/ORMDockerfile
  integration-tests/go-sql-server-driver/go.mod
Labels: correctness_approved

#7663 [auto-bump] [no-release-notes] dependency by max-hoffman
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#7667 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#7669 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved
