Repository dolthub/dolt, pull requests merged in 2024-01, with the labels that each got.

#7231 [auto-bump] [no-release-notes] dependency by nicktobey
  go/go.mod
  go/go.sum
Labels: gms-bump

#7232 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump

#7236 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/enginetest/dolt_queries.go
  integration-tests/bats/create-views.bats
  integration-tests/bats/sql.bats
Labels: gms-bump, keep-alive

#7240 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump

#7251 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump, keep-alive

#7269 [auto-bump] [no-release-notes] dependency by max-hoffman
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
Labels: gms-bump

#7273 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump, keep-alive

#7290 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump

#7299 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump

#7310 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump

#7321 [auto-bump] [no-release-notes] dependency by jycor
  .github/scripts/sql-correctness/current_correctness.txt
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#7325 [no-release-notes] /.github/workflows/sql-regressions.yaml: only run on changes to go dir
  .github/workflows/sql-regressions.yaml
Labels: correctness_approved

#7333 [auto-bump] [no-release-notes] dependency by max-hoffman
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#7327 fix tests from string to bool conversion change
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/binlogreplication/binlog_replication_reconnect_test.go
  go/libraries/doltcore/sqle/sqlinsert_test.go
Labels: correctness_approved

#7336 Fixed spurious error message for event scheduling when the dolt_schem…
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/database.go
  go/libraries/doltcore/sqle/database_test.go
  go/libraries/doltcore/sqle/procedures_table_test.go
Labels: correctness_approved

#7342 [auto-bump] [no-release-notes] dependency by jycor
  go/cmd/dolt/commands/add.go
  go/cmd/dolt/commands/assist.go
  go/cmd/dolt/commands/branch.go
  go/cmd/dolt/commands/commit.go
  go/cmd/dolt/commands/merge.go
  go/cmd/dolt/commands/pull.go
  go/cmd/dolt/commands/push.go
  go/cmd/dolt/commands/reset.go
  go/cmd/dolt/commands/revert.go
  go/cmd/dolt/commands/sql.go
  go/cmd/dolt/commands/utils.go
  go/go.mod
  go/go.sum
  go/libraries/doltcore/mvdata/engine_table_writer.go
  go/libraries/doltcore/sqle/enginetest/branch_control_test.go
  go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
  go/libraries/doltcore/sqle/enginetest/dolt_harness.go
  go/libraries/doltcore/sqle/index/mergeable_indexes_test.go
  go/libraries/doltcore/sqle/show_create_table.go
  go/libraries/doltcore/sqle/sqlddl_test.go
  go/libraries/doltcore/sqle/writer/noms_table_writer_test.go
Labels: gms-bump, keep-alive, correctness_approved

#7355 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
  integration-tests/bats/sql-server.bats
  integration-tests/go-sql-server-driver/tests/sql-server-config.yaml
Labels: gms-bump, keep-alive, correctness_approved

#7357 [no-release-notes] refactoring BinaryExpression
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/dfunctions/dolt_merge_base.go
  go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
  go/libraries/doltcore/sqle/expreval/expression_evaluator.go
  go/libraries/doltcore/sqle/expreval/expression_evaluator_test.go
Labels: correctness_approved

#7366 [no-release-notes] update sqllogictest/go version
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/logictest/dolt/doltharness.go
Labels: correctness_approved

#7363 dolt merge noop fix
  go/cmd/dolt/commands/merge.go
  go/cmd/dolt/commands/pull.go
  go/cmd/dolt/commands/utils.go
  go/libraries/doltcore/sqle/dprocedures/dolt_merge.go
  go/libraries/doltcore/sqle/dprocedures/dolt_pull.go
  go/libraries/doltcore/sqle/dprocedures/init.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_diff.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_merge.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_rebase.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_schema_merge.go
  go/libraries/doltcore/sqle/enginetest/dolt_transaction_queries.go
  integration-tests/bats/constraint-violations.bats
  integration-tests/bats/sql-merge.bats
  integration-tests/mysql-client-tests/node/workbenchTests/merge.js
Labels: minor version bump, correctness_approved

#7369 [auto-bump] [no-release-notes] dependency by max-hoffman
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#7377 Push tags on remote replication
  go/libraries/doltcore/doltdb/hooksdatabase.go
  integration-tests/bats/replication.bats
Labels: correctness_approved

#7379 [no-release-notes] simplified warn on error behavior
  go/libraries/doltcore/env/actions/tag.go
  go/libraries/doltcore/sqle/read_replica_database.go
  go/libraries/doltcore/sqle/read_replica_database_test.go
  go/libraries/doltcore/sqle/replication.go
  integration-tests/bats/replication.bats
Labels: correctness_approved

#7243 Write stats to disk and `dolt_statistics` table
  .github/scripts/sql-correctness/current_correctness.txt
  go/cmd/dolt/commands/engine/sqlengine.go
  go/cmd/dolt/commands/stashcmds/stash.go
  go/gen/fb/serial/fileidentifiers.go
  go/gen/fb/serial/stat.go
  go/go.mod
  go/go.sum
  go/libraries/doltcore/doltdb/doltdb.go
  go/libraries/doltcore/doltdb/root_val.go
  go/libraries/doltcore/doltdb/system_table.go
  go/libraries/doltcore/ref/ref.go
  go/libraries/doltcore/ref/stats_ref.go
  go/libraries/doltcore/schema/statistic.go
  go/libraries/doltcore/sqle/database.go
  go/libraries/doltcore/sqle/database_provider.go
  go/libraries/doltcore/sqle/dtables/statistics_table.go
  go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
  go/libraries/doltcore/sqle/enginetest/dolt_harness.go
  go/libraries/doltcore/sqle/enginetest/stats_queries.go
  go/libraries/doltcore/sqle/stats/read.go
  go/libraries/doltcore/sqle/stats/refresh.go
  go/libraries/doltcore/sqle/stats/refresh_test.go
  go/libraries/doltcore/sqle/stats/stats_provider.go
  go/libraries/doltcore/sqle/stats/write.go
  go/serial/fileidentifiers.go
  go/serial/generate.sh
  go/serial/stat.fbs
  go/store/datas/database.go
  go/store/datas/database_common.go
  go/store/datas/dataset.go
  go/store/datas/statistics.go
  go/store/prolly/message/message.go
  go/store/types/serial_message.go
Labels: correctness_approved

#7386 Cleaner clone CLI
  go/libraries/doltcore/doltdb/doltdb.go
  go/libraries/doltcore/env/actions/clone.go
  integration-tests/bats/remotes.bats
Labels: correctness_approved

#7394 [auto-bump] [no-release-notes] dependency by max-hoffman
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#7373 add `dolt rebase` command
  go/cmd/dolt/commands/commit.go
  go/cmd/dolt/commands/rebase.go
  go/cmd/dolt/dolt.go
  go/gen/proto/dolt/services/eventsapi/v1alpha1/client_event.pb.go
  go/gen/proto/dolt/services/eventsapi/v1alpha1/client_event_grpc.pb.go
  go/gen/proto/dolt/services/eventsapi/v1alpha1/event_constants.pb.go
  go/gen/proto/dolt/services/remotesapi/v1alpha1/chunkstore.pb.go
  go/gen/proto/dolt/services/remotesapi/v1alpha1/chunkstore_grpc.pb.go
  go/gen/proto/dolt/services/remotesapi/v1alpha1/credentials.pb.go
  go/gen/proto/dolt/services/remotesapi/v1alpha1/credentials_grpc.pb.go
  go/gen/proto/dolt/services/replicationapi/v1alpha1/replication.pb.go
  go/gen/proto/dolt/services/replicationapi/v1alpha1/replication_grpc.pb.go
  go/libraries/doltcore/sqle/dprocedures/dolt_rebase.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_rebase.go
  go/libraries/utils/editor/edit.go
  go/libraries/utils/editor/edit_test.go
  integration-tests/bats/helper/local-remote.bash
  integration-tests/bats/rebase.bats
  integration-tests/bats/sql-local-remote.bats
  proto/dolt/services/eventsapi/v1alpha1/event_constants.proto
Labels: correctness_approved

#7398 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump, keep-alive, correctness_approved

#7367 [no-release-notes] update sysbench runner to create and init data dir for mysql
  .github/scripts/performance-benchmarking/get-mysql-dolt-job-json.sh
  go/performance/continuous_integration/config.json
  go/performance/continuous_integration/tpcc-config.json
  go/performance/utils/sysbench_runner/config.go
  go/performance/utils/sysbench_runner/mysql.go
  go/performance/utils/sysbench_runner/postgres.go
Labels: correctness_approved

#7400 dolt backup restore --force: Add a --force option to dolt backup restore, which allows restoring into an already existing database.
  go/cmd/dolt/cli/arg_parser_helpers.go
  go/cmd/dolt/commands/backup.go
  integration-tests/bats/backup.bats
Labels: correctness_approved

#7403 [auto-bump] [no-release-notes] dependency by jycor
  .github/scripts/sql-correctness/current_correctness.txt
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#7405 /go/performance/utils/{sysbench_runner,tpcc_runner}: use temp dir in tpcc
  go/performance/utils/sysbench_runner/mysql.go
  go/performance/utils/tpcc_runner/mysql.go
Labels: correctness_approved

#7406 [auto-bump] [no-release-notes] dependency by nicktobey
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#7407 Bug fix: Unresolved FK fields were not included in the FK's hash
  go/libraries/doltcore/doltdb/foreign_key_coll.go
  go/libraries/doltcore/doltdb/foreign_key_test.go
  go/libraries/doltcore/env/actions/checkout.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_merge.go
  go/libraries/doltcore/sqle/enginetest/dolt_transaction_queries.go
  integration-tests/bats/diff.bats
  integration-tests/bats/foreign-keys.bats
  integration-tests/mysql-client-tests/node/workbenchTests/diffs.js
  integration-tests/mysql-client-tests/node/workbenchTests/table.js
Labels: correctness_approved

#7410 Prevent panic when sorting by `commit_hash` in various dolt system tables
  go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries.go
  go/libraries/doltcore/sqle/enginetest/dolt_query_plans.go
  go/libraries/doltcore/sqle/index/dolt_index.go
Labels: correctness_approved

#7401 fix bats tests to include backticks for column names in default and generated expressions
  go/go.mod
  go/go.sum
  integration-tests/bats/default-values.bats
Labels: correctness_approved

#7408 Adds support for `dolt log --stat`
  go/cmd/dolt/cli/arg_parser_helpers.go
  go/cmd/dolt/cli/flags.go
  go/cmd/dolt/commands/diff.go
  go/cmd/dolt/commands/log.go
  go/cmd/dolt/commands/merge.go
  go/cmd/dolt/commands/utils.go
  integration-tests/bats/log.bats
Labels: correctness_approved

#7412 When aborting a merge/cherry-pick, avoid resetting ignored tables.
  go/libraries/doltcore/merge/action.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries.go
Labels: correctness_approved

#7399 [no-release-notes] fix stats errors
  go/cmd/dolt/commands/engine/sqlengine.go
  go/go.mod
  go/go.sum
  go/libraries/doltcore/doltdb/doltdb.go
  go/libraries/doltcore/sqle/enginetest/stats_queries.go
  go/libraries/doltcore/sqle/stats/read.go
  go/libraries/doltcore/sqle/stats/refresh.go
  go/libraries/doltcore/sqle/stats/stats_provider.go
Labels: correctness_approved

#7423 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, keep-alive, correctness_approved

#7390 Concurrent table deletion and schema modification should be reported as a schema conflict.
  go/libraries/doltcore/cherry_pick/cherry_pick.go
  go/libraries/doltcore/doltdb/root_val.go
  go/libraries/doltcore/doltdb/table.go
  go/libraries/doltcore/doltdb/workingset.go
  go/libraries/doltcore/merge/merge.go
  go/libraries/doltcore/merge/merge_rows.go
  go/libraries/doltcore/merge/merge_schema.go
  go/libraries/doltcore/merge/schema_merge_test.go
  go/libraries/doltcore/schema/tag.go
  go/libraries/doltcore/sqle/alterschema.go
  go/libraries/doltcore/sqle/alterschema_test.go
  go/libraries/doltcore/sqle/database.go
  go/libraries/doltcore/sqle/dtables/schema_conflicts_table.go
  integration-tests/bats/cherry-pick.bats
  integration-tests/bats/merge.bats
  integration-tests/bats/sql-cherry-pick.bats
  integration-tests/bats/stash.bats
Labels: correctness_approved

#7425 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, keep-alive, correctness_approved

#7426 fix sqllogictest harness to use float rounding
  .github/scripts/sql-correctness/current_correctness.txt
  go/libraries/doltcore/sqle/logictest/dolt/doltharness.go
Labels: correctness_approved

#7432 dolt_clone and --user
  go/libraries/doltcore/env/actions/clone.go
  go/libraries/doltcore/sqle/database_provider.go
  go/libraries/doltcore/sqle/dprocedures/dolt_clone.go
  integration-tests/bats/sql-server-remotesrv.bats
Labels: correctness_approved

#7439 [auto-bump] [no-release-notes] dependency by max-hoffman
  .github/scripts/sql-correctness/current_correctness.txt
  go/go.mod
  go/go.sum
Labels: gms-bump, keep-alive, correctness_approved

#7440 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump, keep-alive, correctness_approved
