Repository dolthub/dolt, pull requests merged in 2025-08, with the labels that each got.

#9617 Fix DBeaver infinite loop from system table database context errors
  go/libraries/doltcore/sqle/database.go
  go/libraries/doltcore/sqle/dtables/backups_table.go
  go/libraries/doltcore/sqle/dtables/remotes_table.go
  go/libraries/doltcore/sqle/dtables/stashes_table.go
  integration-tests/bats/sql-server.bats
Labels: correctness_approved

#9600 Add `dolt ci run`
  go/cmd/dolt/commands/ci/ci.go
  go/cmd/dolt/commands/ci/run.go
  go/cmd/dolt/commands/ci/view.go
  go/libraries/doltcore/env/actions/dolt_ci/utils.go
  go/libraries/doltcore/env/actions/dolt_ci/workflow_manager.go
  integration-tests/bats/ci.bats
Labels: correctness_approved

#9619 dolthub/dolt#9530 - Overflow check for auto_inc
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/dsess/autoincrement_tracker.go
Labels: correctness_approved

#9622 [auto-bump] [no-release-notes] dependency by angelamayxie
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9625 [auto-bump] [no-release-notes] dependency by angelamayxie
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9618 Agent.md dolt doc
  go/cmd/dolt/commands/docscmds/read.go
  go/cmd/dolt/commands/docscmds/write.go
  go/libraries/doltcore/doltdb/system_table.go
  go/libraries/doltcore/sqle/dtables/docs_table.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries.go
  go/libraries/doltcore/sqle/sqldelete_test.go
  go/libraries/doltcore/sqle/sqlinsert_test.go
  go/libraries/doltcore/sqle/sqlreplace_test.go
  go/libraries/doltcore/sqle/sqlselect_test.go
  go/libraries/doltcore/sqle/sqlupdate_test.go
  integration-tests/bats/docs.bats
  integration-tests/bats/init.bats
  integration-tests/mysql-client-tests/node/workbenchTests/docs.js
Labels: correctness_approved

#9627 [auto-bump] [no-release-notes] dependency by elianddb
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9629 A more comprehensive default AGENT.md
  go/libraries/doltcore/doltdb/system_table.go
  integration-tests/bats/docs.bats
  integration-tests/bats/init.bats
Labels: correctness_approved

#9630 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9639 Small fixes to ci, --help & valid branch names
  go/cmd/dolt/commands/ci/import.go
  go/libraries/doltcore/env/actions/dolt_ci/workflow_config.go
  integration-tests/bats/ci.bats
Labels: correctness_approved

#9644 [auto-bump] [no-release-notes] dependency by elianddb
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9646 Add UUID key recommendation to default AGENT.md
  go/libraries/doltcore/doltdb/system_table.go
Labels: correctness_approved

#9648 Bug fix: ensure `dolt_checkout()` initializes a branch's working set
  go/libraries/doltcore/sqle/dprocedures/dolt_checkout.go
  integration-tests/bats/sql-server-remotesrv.bats
Labels: correctness_approved

#9650 [no-release-notes] fix local sysbench scripts to use SSL
  go/performance/scripts/local_sysbench.sh
  go/performance/scripts/local_tpcc.sh
Labels: correctness_approved

#9638 cache keys in iters to reduce gc
  go/Godeps/LICENSES
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/writer/prolly_index_writer.go
  go/libraries/doltcore/sqle/writer/prolly_table_writer.go
Labels: correctness_approved

#9658 [auto-bump] [no-release-notes] dependency by angelamayxie
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9662 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/enginetest/dolt_queries.go
Labels: gms-bump, keep-alive, correctness_approved

#9663 avoid using `sql.Row.Append()`
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/dtablefunctions/dolt_log.go
  go/libraries/doltcore/sqle/dtablefunctions/dolt_patch.go
Labels: correctness_approved

#9671 [auto-bump] [no-release-notes] dependency by timsehn
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9674 Remove references to branch wildcards in Dolt CI YAML in AGENT.md
  go/libraries/doltcore/doltdb/system_table.go
Labels: correctness_approved

#9673 [no-release-notes] Move binlog tests to a separate CI job
  .github/workflows/ci-binlog-tests.yaml
  .github/workflows/ci-go-tests.yaml
Labels: correctness_approved

#9679 [auto-bump] [no-release-notes] dependency by angelamayxie
  go/go.mod
  go/go.sum
Labels: gms-bump

#9683 [auto-bump] [no-release-notes] dependency by angelamayxie
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9704 [no-release-notes] Make updates for new GroupBy validation in gms
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/kvexec/builder.go
  integration-tests/bats/sql.bats
  integration-tests/mysql-client-tests/node/workbenchTests/table.js
Labels: correctness_approved

#9710 Fixes for Doltgres-related procedure calling
  go/libraries/doltcore/doltdb/root_val.go
  go/libraries/doltcore/env/actions/reset.go
  go/libraries/doltcore/sqle/dsess/session.go
  go/libraries/doltcore/sqle/expranalysis/expranalysis.go
Labels: correctness_approved

#9719 Drop old event messages
  go/libraries/events/collector.go
  go/libraries/events/emitter.go
  go/libraries/events/events_test.go
Labels: correctness_approved

#9721 disable `only_full_group_by` in sysbench
  go/performance/scripts/local_sysbench.sh
  go/performance/scripts/local_tpcc.sh
  go/performance/utils/benchmark_runner/dolt_server_config.go
  go/performance/utils/benchmark_runner/results_test.go
Labels: correctness_approved

#9678 dolt_tests system table
  go/libraries/doltcore/doltdb/system_table.go
  go/libraries/doltcore/sqle/database.go
  go/libraries/doltcore/sqle/dtables/query_catalog_table.go
  go/libraries/doltcore/sqle/dtables/tests_table.go
  go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
  go/libraries/doltcore/sqle/enginetest/dolt_engine_tests.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_test_table.go
Labels: correctness_approved

#9720 [no-release-notes] conjoin prep
  go/libraries/doltcore/remotesrv/grpc.go
  go/store/nbs/archive.go
  go/store/nbs/archive_build.go
  go/store/nbs/archive_chunk_source.go
  go/store/nbs/archive_reader.go
  go/store/nbs/archive_test.go
  go/store/nbs/archive_writer.go
  go/store/nbs/aws_table_persister.go
  go/store/nbs/metadata.go
Labels: correctness_approved

#9723 [auto-bump] [no-release-notes] dependency by angelamayxie
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9728 dolthub/dolt#9725 - Fix AUTO_INCREMENT reuse after HA failover by refreshing trackers
  go/libraries/doltcore/sqle/cluster/controller.go
  integration-tests/go-sql-server-driver/tests/sql-server-cluster.yaml
Labels: correctness_approved

#9732 [auto-bump] [no-release-notes] dependency by angelamayxie
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9730 Fix dolt_conflicts_resolve for doltgres
  go/libraries/doltcore/sqle/dprocedures/dolt_conflicts_resolve.go
Labels: correctness_approved

#9682 aws archive conjoin support
  go/store/nbs/archive_build.go
  go/store/nbs/archive_reader.go
  go/store/nbs/archive_test.go
  go/store/nbs/archive_writer.go
  go/store/nbs/aws_table_persister.go
  go/store/nbs/aws_table_persister_test.go
  go/store/nbs/bs_persister.go
  go/store/nbs/file_table_persister.go
  go/store/nbs/file_table_reader.go
  go/store/nbs/journal.go
  go/store/nbs/table.go
  go/store/nbs/table_persister.go
  integration-tests/bats/admin-conjoin.bats
  integration-tests/go-sql-server-driver/gc_oldgen_conjoin_test.go
Labels: correctness_approved

#9716 add option to start an http mcp server when dolt sql-server is running
  go/Godeps/LICENSES
  go/cmd/dolt/commands/sqlserver/mcp.go
  go/cmd/dolt/commands/sqlserver/mcp_validate.go
  go/cmd/dolt/commands/sqlserver/server.go
  go/cmd/dolt/commands/sqlserver/sqlserver.go
  go/go.mod
  go/go.sum
  integration-tests/bats/helper/common.bash
  integration-tests/bats/sql-server-mcp.bats
  integration-tests/go-sql-server-driver/go.mod
  integration-tests/go-sql-server-driver/go.sum
Labels: correctness_approved

#9737 add DOLT_PAGER to override default pager
  go/cmd/dolt/commands/log_test.go
  go/store/util/outputpager/page_output.go
  integration-tests/bats/pager.bats
  integration-tests/bats/pager.expect
Labels: correctness_approved

#9727 `dolt_test_run` table function
  go/Godeps/LICENSES
  go/go.mod
  go/libraries/doltcore/env/actions/test_table_helpers.go
  go/libraries/doltcore/sqle/dtablefunctions/dolt_test_run.go
  go/libraries/doltcore/sqle/dtablefunctions/init.go
  go/libraries/doltcore/sqle/enginetest/dolt_engine_tests.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_test_table.go
Labels: correctness_approved

#9750 [auto-bump] [no-release-notes] dependency by angelamayxie
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9749 support `mcp_server` in the the `dolt sql-server` configuration file
  go/cmd/dolt/commands/sqlserver/command_line_config.go
  go/cmd/dolt/commands/sqlserver/server_test.go
  go/cmd/dolt/commands/sqlserver/sqlserver.go
  go/libraries/doltcore/servercfg/serverconfig.go
  go/libraries/doltcore/servercfg/testdata/minver_validation.txt
  go/libraries/doltcore/servercfg/yaml_config.go
  integration-tests/bats/sql-server-mcp-config.bats
Labels: correctness_approved

#9751 Optimize commit iterator
  go/cmd/dolt/commands/archive.go
  go/libraries/doltcore/doltdb/commit_itr.go
  go/libraries/doltcore/doltdb/doltdb.go
  go/libraries/doltcore/env/actions/commitwalk/commitwalk.go
  go/libraries/doltcore/rebase/rebase.go
  go/libraries/doltcore/sqle/database.go
  go/libraries/doltcore/sqle/dolt_procedures_diff_table.go
  go/libraries/doltcore/sqle/dolt_schemas_diff_table.go
  go/libraries/doltcore/sqle/dprocedures/dolt_count_commits.go
  go/libraries/doltcore/sqle/dtablefunctions/dolt_log.go
  go/libraries/doltcore/sqle/dtables/column_diff_table.go
  go/libraries/doltcore/sqle/dtables/commit_ancestors_table.go
  go/libraries/doltcore/sqle/dtables/commits_table.go
  go/libraries/doltcore/sqle/dtables/diff_table.go
  go/libraries/doltcore/sqle/dtables/log_table.go
  go/libraries/doltcore/sqle/dtables/unscoped_diff_table.go
  go/libraries/doltcore/sqle/history_table.go
  go/performance/dolt_log_bench/.gitignore
  go/performance/dolt_log_bench/dolt_log_test.go
  go/store/datas/database_common.go
Labels: correctness_approved
