Repository dolthub/dolt, pull requests merged in 2025-03, with the labels that each got.

#8910 Report auto increment changes in dolt diff and `dolt_diff_summary()`
  go/go.mod
  go/go.sum
  go/go.work.sum
  go/libraries/doltcore/diff/table_deltas.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_diff.go
  go/libraries/doltcore/sqle/tables.go
  integration-tests/bats/auto_increment.bats
  integration-tests/bats/diff.bats
Labels: correctness_approved

#8925 [auto-bump] [no-release-notes] dependency by nicktobey
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8921 [no-release-notes] go.mod: Bump github.com/aws/aws-sdk-go to v1.55.6.
  go/go.mod
  go/go.sum
Labels: correctness_approved

#8935 [no-release-notes] go/store/nbs: Fix some minor bugs affecting doltremoteapi in nbs/store.
  go/store/nbs/aws_table_persister.go
  go/store/nbs/store.go
Labels: correctness_approved

#8931 fix use info schema panic
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/dsess/session.go
Labels: correctness_approved

#8929 [auto-bump] [no-release-notes] dependency by jycor
  go/go.sum
  go/libraries/doltcore/sqle/binlogreplication/binlog_replication_test.go
  integration-tests/mysql-client-tests/mysql-client-tests.bats
Labels: gms-bump, keep-alive, correctness_approved

#8915 [no-release-notes] go: doltcore: env: Add ability to override the audience for auth JWTs bound to remotesapi.
  go/libraries/doltcore/env/grpc_dial_provider.go
Labels: correctness_approved

#8946 [auto-bump] [no-release-notes] dependency by reltuk
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8940 [no-release-notes] go: dbfactory: aws_test.go: Add some tests for credential configuration behavior.
  go/libraries/doltcore/dbfactory/aws_test.go
  go/libraries/doltcore/dbfactory/testdata/alt_creds_file
  go/libraries/doltcore/dbfactory/testdata/basic_config_file
  go/libraries/doltcore/dbfactory/testdata/basic_creds_file
Labels: correctness_approved

#8948 go: cmd/dolt: sqlserver: When stopping the svcs.Controller for the sql-server, drain client connections so that the handler is guaranteed to no longer be handling any connections when the server is stopped.
  go/cmd/dolt/commands/sqlserver/server.go
Labels: correctness_approved

#8949 [auto-bump] [no-release-notes] dependency by reltuk
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8902 go/store/nbs: Move to golang maps instead of dolthub/swiss.
  go/Godeps/LICENSES
  go/store/nbs/journal_chunk_source.go
  go/store/nbs/journal_writer.go
  go/store/nbs/journal_writer_test.go
Labels: correctness_approved

#8950 go: cmd/dolt: sqlserver: Create a Config struct to encapsulate arguments that control sqlserver.ConfigureServices behavior.
  go/cmd/dolt/commands/sqlserver/server.go
  go/cmd/dolt/commands/sqlserver/server_test.go
  go/cmd/dolt/commands/sqlserver/sqlserver.go
  go/libraries/doltcore/sqle/enginetest/dolt_server_tests.go
  go/performance/replicationbench/replica_test.go
  go/performance/serverbench/bench_test.go
Labels: correctness_approved

#8944 Added documentation for auto_gc_behavior
  go/cmd/dolt/commands/sqlserver/server_test.go
  go/cmd/dolt/commands/sqlserver/sqlserver.go
  go/libraries/doltcore/servercfg/yaml_config.go
Labels: correctness_approved

#8937 [no-release-notes] go: Migrate to aws-sdk-go-v2.
  go/Godeps/LICENSES
  go/go.mod
  go/go.sum
  go/go.work.sum
  go/libraries/doltcore/dbfactory/aws.go
  go/libraries/doltcore/dbfactory/aws_test.go
  go/libraries/utils/awsrefreshcreds/creds.go
  go/libraries/utils/awsrefreshcreds/creds_test.go
  go/store/nbs/aws_table_persister.go
  go/store/nbs/aws_table_persister_test.go
  go/store/nbs/benchmarks/main.go
  go/store/nbs/dynamo_fake_test.go
  go/store/nbs/dynamo_manifest.go
  go/store/nbs/frag/main.go
  go/store/nbs/s3_fake_test.go
  go/store/nbs/s3_object_reader.go
  go/store/nbs/s3_table_reader_test.go
  go/store/nbs/store.go
  go/store/spec/spec.go
Labels: correctness_approved

#8920 Sql debug cmd
  go/cmd/dolt/commands/debug.go
  go/cmd/dolt/commands/sql.go
  go/cmd/dolt/dolt.go
  go/cmd/dolt/doltcmd/doltcmd.go
  integration-tests/bats/debug.bats
Labels: correctness_approved

#8963 store/nbs: s3_object_reader: Fix a regression which prevented loading large table files with the AWS NomsBlockStore backend.
  go/go.mod
  go/go.sum
  go/store/nbs/s3_fake_test.go
  go/store/nbs/s3_object_reader.go
  go/store/nbs/s3_object_reader_test.go
Labels: correctness_approved

#8962 Backup restore procedure can load aws config
  go/libraries/doltcore/sqle/dprocedures/dolt_backup.go
Labels: correctness_approved

#8967 [no-release-notes] more info in debug output
  go/cmd/dolt/commands/debug.go
Labels: correctness_approved

#8969 [statspro] stats ignore non prolly indexes
  go/cmd/dolt/commands/debug.go
  go/libraries/doltcore/doltdb/durable/index.go
  go/libraries/doltcore/sqle/enginetest/stats_queries.go
  go/libraries/doltcore/sqle/statspro/analyze.go
  go/libraries/doltcore/sqle/statspro/auto_refresh.go
  go/libraries/doltcore/sqle/statspro/update.go
Labels: correctness_approved

#8971 [auto-bump] [no-release-notes] dependency by max-hoffman
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8970 Fix InsertID discrepancy tests
  go/go.mod
  go/go.sum
  go/go.work.sum
  go/libraries/doltcore/sqle/enginetest/dolt_procedure_queries.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_merge.go
Labels: correctness_approved

#8974 Add support for setting notices in the session
  go/libraries/doltcore/sqle/dsess/session.go
Labels: correctness_approved

#8976 go: sqle/dsess: session.go: Fix transaction savepoint creation when cluster replication is enabled.
  go/libraries/doltcore/sqle/dsess/session.go
  integration-tests/go-sql-server-driver/tests/sql-server-cluster.yaml
Labels: correctness_approved

#8980 [no-release-notes] compress dictionary
  go/store/nbs/archive_writer.go
  integration-tests/bats/archive.bats
Labels: correctness_approved

#8984 Fix schema merge bug when schema is identical with multiple indexes on the same columns
  go/libraries/doltcore/merge/merge_schema.go
  go/libraries/doltcore/schema/index_coll.go
  go/libraries/doltcore/schema/schema.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_schema_merge.go
Labels: correctness_approved

#8850 refactor: using clear to simplify the code
  go/libraries/doltcore/sqle/dsess/session_cache.go
  go/store/hash/hash.go
  go/store/util/sizecache/size_cache.go
Labels: contribution

#8989 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/enginetest/dolt_queries.go
Labels: gms-bump, keep-alive, correctness_approved

#8990 Remove unnecessary `hashicorp/go-uuid` dependency
  go/go.mod
  go/go.sum
  go/go.work.sum
  go/libraries/doltcore/sqle/enginetest/dolt_queries.go
Labels: contribution

#8993 Bump golang.org/x/net in /go/gen/proto/dolt/services/eventsapi
  go/gen/proto/dolt/services/eventsapi/go.mod
  go/gen/proto/dolt/services/eventsapi/go.sum
  go/go.mod
  go/go.sum
  go/go.work.sum
  integration-tests/go-sql-server-driver/go.mod
  integration-tests/go-sql-server-driver/go.sum
Labels: correctness_approved

#8994 Bug fix for TypeCompatibilityChecker to ignore ExtenedTypes
  go/libraries/doltcore/schema/typecompatibility/type_compatibility.go
  go/libraries/doltcore/schema/typecompatibility/type_compatibility_test.go
Labels: correctness_approved

#8996 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9003 Up server config default max conns from 100 to 1000
  go/cmd/dolt/commands/sqlserver/server_test.go
  go/libraries/doltcore/servercfg/serverconfig.go
  go/libraries/doltcore/servercfg/yaml_config_test.go
Labels: correctness_approved

#9005 go/store/nbs: Fix perf regression in taking backups.
  go/store/nbs/store.go
Labels: correctness_approved

#9009 [auto-bump] [no-release-notes] dependency by max-hoffman
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9010 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9011 [auto-bump] [no-release-notes] dependency by max-hoffman
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9012 [auto-bump] [no-release-notes] dependency by max-hoffman
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9000 Fix spelling
  go/libraries/doltcore/dbfactory/aws.go
  go/libraries/doltcore/sqle/writer/noms_write_session.go
  go/store/nbs/store.go
  integration-tests/bats/checkout.bats
  integration-tests/bats/foreign-keys.bats
  integration-tests/bats/keyless-foreign-keys.bats
  integration-tests/bats/sql-mysqldb-privs.bats
  integration-tests/mysql-client-tests/dotnet/MySqlClient/Program.cs
  integration-tests/mysql-client-tests/dotnet/MySqlConnector/Program.cs
Labels: contribution

#9002 Replace `golang.org/x/exp/slices` with stdlib `slices`
  go/Godeps/LICENSES
  go/cmd/dolt/commands/add.go
  go/go.mod
  go/libraries/doltcore/sqle/dtablefunctions/dolt_patch_table_function.go
  go/store/prolly/tree/indexed_json_diff.go
Labels: correctness_approved

#8991 Remove duplicate `github.com/vbauerster/mpb` dependency
  go/cmd/dolt/cli/stdio_test.go
  go/go.mod
  go/go.sum
Labels: contribution

#9016 Remove duplicate `github.com/vbauerster/mpb` dependency
  go/cmd/dolt/cli/stdio_test.go
  go/go.mod
  go/go.sum
Labels: correctness_approved

#9006 Replace `jpillora/backoff` with `cenkalti/backoff/v4`
  go/Godeps/LICENSES
  go/go.mod
  go/go.sum
  go/store/nbs/s3_object_reader.go
Labels: contribution

#8995 [no-release-notes] archive hot convert
  go/cmd/dolt/commands/admin/admin.go
  go/cmd/dolt/commands/admin/storage.go
  go/store/datas/pull/pull_table_file_writer.go
  go/store/nbs/archive_build.go
  go/store/nbs/archive_chunker.go
  go/store/nbs/archive_reader.go
  go/store/nbs/archive_writer.go
  go/store/nbs/cmp_chunk_table_writer.go
  go/store/nbs/cmp_chunk_table_writer_test.go
  go/store/nbs/file_table_reader.go
  go/store/nbs/gc_copier.go
  go/store/nbs/metadata.go
  integration-tests/bats/archive-aws.bats
  integration-tests/bats/archive-test-repos/README.txt
  integration-tests/bats/archive-test-repos/base/noms/8p5e2m6skovfdjlh4jg3llr8sfvu384l
  integration-tests/bats/archive-test-repos/base/noms/LOCK
  integration-tests/bats/archive-test-repos/base/noms/manifest
  integration-tests/bats/archive-test-repos/base/noms/oldgen/29o8a3uevcpr15tilcemb3s438edmoog.darc
  integration-tests/bats/archive-test-repos/base/noms/oldgen/LOCK
  integration-tests/bats/archive-test-repos/base/noms/oldgen/dnu4lr5j8sstbj5usbld7alsnuj5nf23.darc
  integration-tests/bats/archive-test-repos/base/noms/oldgen/manifest
  integration-tests/bats/archive-test-repos/base/repo_state.json
  integration-tests/bats/archive-test-repos/large_clone/noms/29o8a3uevcpr15tilcemb3s438edmoog.darc
  integration-tests/bats/archive-test-repos/large_clone/noms/LOCK
  integration-tests/bats/archive-test-repos/large_clone/noms/dnu4lr5j8sstbj5usbld7alsnuj5nf23.darc
  integration-tests/bats/archive-test-repos/large_clone/noms/manifest
  integration-tests/bats/archive-test-repos/large_clone/noms/oldgen/LOCK
  integration-tests/bats/archive-test-repos/large_clone/noms/oldgen/b5j6kmj2m68sukiu22ouoke7u9281a06
  integration-tests/bats/archive-test-repos/large_clone/noms/oldgen/manifest
  integration-tests/bats/archive-test-repos/large_clone/noms/p6d0rsovtipdk6r2b1kh9qrndif41703
  integration-tests/bats/archive-test-repos/large_clone/repo_state.json
  integration-tests/bats/archive-test-repos/small_clone/noms/29o8a3uevcpr15tilcemb3s438edmoog.darc
  integration-tests/bats/archive-test-repos/small_clone/noms/LOCK
  integration-tests/bats/archive-test-repos/small_clone/noms/dnu4lr5j8sstbj5usbld7alsnuj5nf23.darc
  integration-tests/bats/archive-test-repos/small_clone/noms/manifest
  integration-tests/bats/archive-test-repos/small_clone/noms/oldgen/LOCK
  integration-tests/bats/archive-test-repos/small_clone/noms/oldgen/c5j9u4ced6eg6cnegk0mgdglc3t04air
  integration-tests/bats/archive-test-repos/small_clone/noms/oldgen/manifest
  integration-tests/bats/archive-test-repos/small_clone/noms/sv0o2e33pel8caor7979s4rk227raink
  integration-tests/bats/archive-test-repos/small_clone/repo_state.json
  integration-tests/bats/archive.bats
Labels: correctness_approved

#9017 [auto-bump] [no-release-notes] dependency by max-hoffman
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9020 go: branch_control,sqle/dsess: Pass the *sql.Context to the GetBranch accessor. Wrap it for the branch_control.Context conversion.
  go/cmd/dolt/commands/rebase.go
  go/libraries/doltcore/branch_control/branch_control.go
  go/libraries/doltcore/sqle/dprocedures/dolt_checkout.go
  go/libraries/doltcore/sqle/dsess/session.go
  go/libraries/doltcore/sqle/statspro/controller.go
Labels: correctness_approved

#9019 [no-release-notes] go: Fix a few call sites where the wrong context was passed.
  go/cmd/dolt/commands/branch.go
  go/libraries/doltcore/remotesrv/grpc.go
Labels: correctness_approved

#9018 [no-release-notes] Fix races in doltgres
  go/cmd/dolt/commands/engine/sqlengine.go
  go/cmd/dolt/commands/sqlserver/server.go
  go/cmd/dolt/commands/utils.go
  go/libraries/doltcore/doltdb/durable/index.go
  go/libraries/doltcore/sqle/enginetest/dolt_harness.go
  go/libraries/doltcore/sqle/statspro/controller.go
  go/libraries/doltcore/sqle/statspro/jobqueue/serialqueue.go
  go/libraries/doltcore/sqle/statspro/listener.go
  go/libraries/doltcore/sqle/statspro/stats_kv.go
  go/libraries/doltcore/sqle/statspro/worker.go
  go/libraries/doltcore/sqle/statspro/worker_test.go
Labels: correctness_approved

#9021 go: gcctx,dsess: Move GCSafepointController into an independent package. Make dsess.AutoIncrementTracker background database access participate in GC lifecycle callbacks.
  go/cmd/dolt/commands/engine/sqlengine.go
  go/libraries/doltcore/doltdb/gcctx/context.go
  go/libraries/doltcore/doltdb/gcctx/gc_safepoint_controller.go
  go/libraries/doltcore/doltdb/gcctx/gc_safepoint_controller_test.go
  go/libraries/doltcore/sqle/dprocedures/dolt_gc.go
  go/libraries/doltcore/sqle/dsess/autoincrement_tracker.go
  go/libraries/doltcore/sqle/dsess/session.go
  go/libraries/doltcore/sqle/enginetest/dolt_harness.go
  go/libraries/doltcore/sqle/logictest/dolt/doltharness.go
  go/libraries/doltcore/sqle/sqlddl_test.go
  go/libraries/doltcore/sqle/statspro/worker_test.go
  go/libraries/doltcore/sqle/testutil.go
Labels: correctness_approved

#8997 [no-release-notes] integration-tests/go-sql-server-driver: Add dynamic port allocation and run these tests in parallel.
  go/libraries/doltcore/dtestutils/sql_server_driver/server.go
  integration-tests/go-sql-server-driver/auto_gc_test.go
  integration-tests/go-sql-server-driver/concurrent_gc_test.go
  integration-tests/go-sql-server-driver/gc_oldgen_conjoin_test.go
  integration-tests/go-sql-server-driver/genjwt_test.go
  integration-tests/go-sql-server-driver/main_test.go
  integration-tests/go-sql-server-driver/sqlserver_info_test.go
  integration-tests/go-sql-server-driver/testdef.go
  integration-tests/go-sql-server-driver/tests/sql-server-cluster-read-only.yaml
  integration-tests/go-sql-server-driver/tests/sql-server-cluster-tls.yaml
  integration-tests/go-sql-server-driver/tests/sql-server-cluster-users-and-grants.yaml
  integration-tests/go-sql-server-driver/tests/sql-server-cluster.yaml
  integration-tests/go-sql-server-driver/tests/sql-server-config.yaml
  integration-tests/go-sql-server-driver/tests/sql-server-jwt-auth.yaml
  integration-tests/go-sql-server-driver/tests/sql-server-orig.yaml
  integration-tests/go-sql-server-driver/tests/sql-server-remotesapi.yaml
  integration-tests/go-sql-server-driver/tests/sql-server-tls.yaml
Labels: correctness_approved

#9028 Test new connection configuration in vitess
  go/cmd/dolt/commands/sqlserver/command_line_config.go
  go/cmd/dolt/commands/sqlserver/server.go
  go/cmd/dolt/commands/sqlserver/server_test.go
  go/cmd/dolt/commands/sqlserver/sqlserver.go
  go/go.mod
  go/go.sum
  go/libraries/doltcore/servercfg/serverconfig.go
  go/libraries/doltcore/servercfg/testdata/minver_validation.txt
  go/libraries/doltcore/servercfg/yaml_config.go
  go/libraries/doltcore/servercfg/yaml_config_test.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_primary_test.go
  go/store/datas/commit_meta.go
  integration-tests/bats/sql-server-config-file-generation.bats
  integration-tests/bats/sql-server.bats
Labels: gms-bump, keep-alive, correctness_approved

#9034 Be more flexible for missing working sets when loading db
  go/libraries/doltcore/sqle/database_provider.go
Labels: correctness_approved

#9043 [auto-bump] [no-release-notes] dependency by Hydrocharged
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9033 [no-release-notes] better stats err log
  go/libraries/doltcore/sqle/dtables/statistics_table.go
  go/libraries/doltcore/sqle/statspro/controller.go
Labels: correctness_approved

#9029 go: Add some GC lifecycle callbacks to commands which use a local SqlEngine.
  go/cmd/dolt/commands/assist.go
  go/cmd/dolt/commands/cvcmds/verify_constraints.go
  go/cmd/dolt/commands/docscmds/diff.go
  go/cmd/dolt/commands/docscmds/read.go
  go/cmd/dolt/commands/docscmds/write.go
  go/libraries/doltcore/merge/schema_merge_test.go
  go/libraries/doltcore/schema/encoding/integration_test.go
Labels: correctness_approved

#9023 go: mvdata: Improve dump, import and export so that these commands create a single SqlEngine over their lifetime.
  go/cmd/dolt/commands/dump.go
  go/cmd/dolt/commands/engine/sqlengine.go
  go/cmd/dolt/commands/tblcmds/export.go
  go/cmd/dolt/commands/tblcmds/import.go
  go/libraries/doltcore/mvdata/data_loc_test.go
  go/libraries/doltcore/mvdata/data_mover.go
  go/libraries/doltcore/mvdata/engine_table_reader.go
  go/libraries/doltcore/mvdata/engine_table_writer.go
  go/libraries/doltcore/mvdata/file_data_loc.go
Labels: correctness_approved

#9032 integration-tests/go-sql-server-driver: Move max-connections testing to go-sql-server-driver.
  go/go.mod
  go/go.sum
  go/libraries/doltcore/dtestutils/sql_server_driver/cmd.go
  integration-tests/bats/sql-server.bats
  integration-tests/go-sql-server-driver/go.mod
  integration-tests/go-sql-server-driver/go.sum
  integration-tests/go-sql-server-driver/sql_server_max_conns_test.go
Labels: correctness_approved

#9041 go: store/datas/pull: Error handling improvements. Target an approximate file size instead of a number of chunks when uploading files.
  go/libraries/doltcore/doltdb/doltdb.go
  go/store/datas/pull/pull_chunk_fetcher.go
  go/store/datas/pull/pull_chunk_fetcher_test.go
  go/store/datas/pull/pull_chunk_tracker.go
  go/store/datas/pull/pull_chunk_tracker_test.go
  go/store/datas/pull/pull_table_file_writer.go
  go/store/datas/pull/pull_table_file_writer_test.go
  go/store/datas/pull/puller.go
  go/store/datas/pull/puller_test.go
Labels: correctness_approved

#8965 Root Objects
  go/go.work.sum
  go/libraries/doltcore/diff/table_deltas.go
  go/libraries/doltcore/doltdb/root_object.go
  go/libraries/doltcore/doltdb/root_val.go
  go/libraries/doltcore/env/actions/reset.go
  go/libraries/doltcore/env/actions/staged.go
  go/libraries/doltcore/env/actions/table.go
  go/libraries/doltcore/merge/merge.go
  go/libraries/doltcore/merge/merge_rows.go
  go/libraries/doltcore/merge/merge_schema.go
  go/libraries/doltcore/sqle/dprocedures/dolt_add.go
  go/libraries/doltcore/sqle/dprocedures/dolt_checkout.go
  go/libraries/doltcore/sqle/dtablefunctions/dolt_diff_summary_table_function.go
  go/libraries/doltcore/sqle/resolve/resolve_tables.go
Labels: correctness_approved

#9050 go,integration-tests/{bats,go-sql-server-driver}: Implement GC sesssion lifecycle validation at the storage layer. Enable checks for bats and go sql server integration tests.
  go/cmd/dolt/commands/engine/sqlengine.go
  go/cmd/dolt/commands/show.go
  go/cmd/dolt/commands/sql.go
  go/cmd/dolt/commands/sqlserver/server.go
  go/cmd/dolt/commands/tblcmds/export.go
  go/cmd/dolt/commands/utils.go
  go/libraries/doltcore/doltdb/gcctx/context.go
  go/libraries/doltcore/sqle/database_provider.go
  go/libraries/doltcore/sqle/dprocedures/dolt_test_valctx.go
  go/libraries/doltcore/sqle/dsess/autoincrement_tracker.go
  go/libraries/doltcore/sqle/dsess/session.go
  go/libraries/doltcore/sqle/statspro/controller.go
  go/libraries/doltcore/sqle/statspro/jobqueue/serialqueue.go
  go/libraries/utils/valctx/valctx.go
  go/store/nbs/store.go
  integration-tests/bats/garbage_collection.bats
  integration-tests/bats/helper/common.bash
  integration-tests/go-sql-server-driver/testdef.go
  integration-tests/go-sql-server-driver/valctx_enabled_test.go
Labels: correctness_approved

#9047 go: utils/publishrelease/buildpgobinaries.sh: Bump optcross to pick up new dolthub_toolchains changes.
  go/utils/publishrelease/buildpgobinaries.sh
Labels: correctness_approved

#9059 go: cmd/dolt: commands/sql: Fix the displayed query time in interactive mode after a query completes.
  go/cmd/dolt/commands/sql.go
  integration-tests/bats/sql-shell.bats
Labels: correctness_approved
