Repository dolthub/dolt, pull requests merged in 2025-10, with the labels that each got.

#9898 [auto-bump] [no-release-notes] dependency by elianddb
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9900 Added collation ignoring for information_schema
  go/go.mod
  go/go.sum
  integration-tests/mysql-client-tests/java/MySQLConnectorTest_Collation.java
  integration-tests/mysql-client-tests/mysql-client-tests.bats
Labels: correctness_approved

#9918 [auto-bump] [no-release-notes] dependency by elianddb
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9923 [auto-bump] [no-release-notes] dependency by angelamayxie
  go/go.mod
  go/go.sum
Labels: gms-bump, keep-alive, correctness_approved

#9924 Implement dolt_global_tables system table
  go/go.mod
  go/go.sum
  go/libraries/doltcore/doltdb/ignore.go
  go/libraries/doltcore/doltdb/nonlocal_tables.go
  go/libraries/doltcore/doltdb/system_table.go
  go/libraries/doltcore/doltdb/table_name_patterns.go
  go/libraries/doltcore/sqle/database.go
  go/libraries/doltcore/sqle/dtables/docs_table.go
  go/libraries/doltcore/sqle/dtables/ignore_table.go
  go/libraries/doltcore/sqle/dtables/nonlocal_table.go
  go/libraries/doltcore/sqle/dtables/query_catalog_table.go
  go/libraries/doltcore/sqle/dtables/user_space_system_table.go
  go/libraries/doltcore/sqle/tables.go
  integration-tests/bats/helper/local-remote.bash
  integration-tests/bats/nonlocal.bats
Labels: correctness_approved

#9930 Revert refactor of dolt_docs table.
  go/libraries/doltcore/sqle/dtables/docs_table.go
Labels: correctness_approved

#9929 [no-release-notes] get records range duplication
  go/store/nbs/archive_chunk_source.go
  go/store/nbs/archive_test.go
Labels: correctness_approved
