Repository dolthub/dolt, pull requests merged in 2025-09, with the labels that each got.

#9757 Cache materialized commits on `doltdb`
  go/libraries/doltcore/doltdb/doltdb.go
  go/libraries/doltcore/env/memory.go
  go/libraries/doltcore/migrate/integration_test.go
Labels: correctness_approved

#9768 Replace Dolt CI testing references in AGENT.md with reference to `dolt_tests`
  go/libraries/doltcore/doltdb/system_table.go
Labels: correctness_approved

#9776 [no-release-notes] Move AGENT.md into it's own file
  go/libraries/doltcore/doltdb/AGENT.md
  go/libraries/doltcore/doltdb/system_table.go
Labels: correctness_approved

#9758 Add support for VECTOR column type
  go/go.mod
  go/go.sum
  go/libraries/doltcore/schema/serial_encoding.go
  go/libraries/doltcore/schema/typeinfo/typeinfo.go
  go/libraries/doltcore/schema/typeinfo/vector.go
  go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
  go/libraries/doltcore/sqle/sqlfmt/row_fmt.go
  go/store/prolly/message/message.go
  go/store/prolly/proximity_map.go
  go/store/prolly/proximity_map_test.go
  go/store/prolly/proximity_mutable_map.go
  go/store/prolly/shim/shim.go
  go/store/prolly/tree/blob_builder_test.go
  go/store/prolly/tree/chunker.go
  go/store/prolly/tree/node.go
  go/store/prolly/tree/node_cursor.go
  go/store/prolly/tree/patch_generator.go
  go/store/prolly/tree/prolly_fields.go
  go/store/prolly/tree/proximity_map.go
  go/store/prolly/tree/stats_test.go
  go/store/prolly/vector_index_chunker.go
  go/store/val/tuple_builder_test.go
  go/store/val/tuple_descriptor.go
  integration-tests/bats/dump.bats
Labels: correctness_approved

#9783 Bug fix: allow aborting a merge when there is a table rename
  go/libraries/doltcore/doltdb/ignore.go
  go/libraries/doltcore/merge/action.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_merge.go
Labels: correctness_approved

#9786 [auto-bump] [no-release-notes] dependency by angelamayxie
  go/go.mod
  go/go.sum
Labels: gms-bump, keep-alive, correctness_approved

#9796 [auto-bump] [no-release-notes] dependency by angelamayxie
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9802 [auto-bump] [no-release-notes] dependency by elianddb
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9790 dolthub/dolt#9794 - Add --skinny support for DOLT_DIFF table func
  go/cmd/dolt/cli/arg_parser_helpers.go
  go/cmd/dolt/cli/flags.go
  go/cmd/dolt/commands/diff.go
  go/cmd/dolt/commands/show.go
  go/libraries/doltcore/sqle/dtablefunctions/dolt_diff.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_diff.go
  integration-tests/bats/helper/sql-diff.bash
  integration-tests/bats/sql-diff.bats
Labels: correctness_approved

#9813 /go/cmd/dolt/commands/sqlserver/sqlserver.go: remove incorrect help text line from --mcp-password option.
  go/cmd/dolt/commands/sqlserver/sqlserver.go
Labels: correctness_approved

#9804 [no-release-notes] fix error message
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/enginetest/ddl_queries.go
Labels: correctness_approved

#9822 fix missed `context canceled` error for `dolt_test_run()`
  go/libraries/doltcore/env/actions/test_table_helpers.go
  go/libraries/doltcore/sqle/dtablefunctions/dolt_test_run.go
  integration-tests/bats/dolt-test-run.bats
Labels: correctness_approved

#9825 [auto-bump] [no-release-notes] dependency by angelamayxie
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9819 Allow foreign keys to reference `dolt_branches` system table
  go/libraries/doltcore/sqle/dtablefunctions/dolt_patch.go
  go/libraries/doltcore/sqle/dtables/branches_table.go
  go/libraries/doltcore/sqle/dtables/dtable_fk_editor.go
  go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
  go/libraries/doltcore/sqle/enginetest/dolt_engine_tests.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries.go
  go/libraries/doltcore/sqle/fk/fk_references.go
  go/libraries/doltcore/sqle/index/dolt_index.go
  go/libraries/doltcore/sqle/sqlutil/convert.go
  go/libraries/doltcore/sqle/tables.go
Labels: correctness_approved

#9823 dolthub/dolt#9817 - Add bats for binary ops
  integration-tests/bats/types.bats
Labels: correctness_approved

#9842 [auto-bump] [no-release-notes] dependency by angelamayxie
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9839 go/go.mod: Bump eventsapi_schema.
  go/go.mod
  go/go.sum
Labels: correctness_approved

#9846 [auto-bump] [no-release-notes] dependency by reltuk
  .github/workflows/ci-go-tests.yaml
  go/Godeps/LICENSES
  go/go.mod
  go/go.sum
  go/performance/continuous_integration/SysbenchDockerfile
  integration-tests/DataDumpLoadDockerfile
Labels: gms-bump, correctness_approved

#9849 [auto-bump] [no-release-notes] dependency by jennifersp
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9856 [auto-bump] [no-release-notes] dependency by elianddb
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9854 /go/{go.mod,go.sum}: bump dolt-mcp, supports Dolt Tests via tool calls
  go/go.mod
  go/go.sum
Labels: correctness_approved

#9850 [no-release-notes] add `dolt admin archive-inspect` cmd
  go/cmd/dolt/commands/admin/admin.go
  go/cmd/dolt/commands/admin/archive_inspect.go
  go/store/nbs/archive_inspect.go
  go/store/nbs/archive_reader.go
  integration-tests/bats/admin-archive-inspect.bats
  integration-tests/bats/helper/local-remote.bash
Labels: correctness_approved

#9853 [no-release-notes] Update invalid test query
  go/libraries/doltcore/sqle/enginetest/prepared_queries.go
Labels: correctness_approved

#9859 [no-release-notes] bump golang version
  .github/workflows/cd-release-pgo.yaml
  docker/serverDockerfile
  go/cmd/dolt/commands/archive.go
  go/go.mod
  go/go.sum
  go/utils/batsee/main.go
  integration-tests/DataDumpLoadDockerfile
  integration-tests/MySQLDockerfile
  integration-tests/ORMDockerfile
  integration-tests/go-sql-server-driver/go.mod
Labels: correctness_approved

#9861 [auto-bump] [no-release-notes] dependency by angelamayxie
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9855 Preemptively store extended adaptive values out-of-band if they're too large to fit in a Tuple
  go/libraries/doltcore/schema/serial_encoding.go
  go/store/prolly/tree/prolly_fields.go
  go/store/val/tuple_builder.go
Labels: correctness_approved

#9882 [auto-bump] [no-release-notes] dependency by nicktobey
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9888 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved
