Repository dolthub/dolt, pull requests merged in 2025-05, with the labels that each got.

#9167 test for temporary tables in stored procedures
  go/libraries/doltcore/sqle/enginetest/dolt_queries.go
Labels: correctness_approved

#9165 go: keymutex: Improve cleanup and refcnt implementation so that we can keep the mutexes map clean in more cases.
  go/libraries/utils/keymutex/keymutex.go
  go/libraries/utils/keymutex/keymutex_test.go
Labels: correctness_approved

#9120 Consistently use pointer receiver for ByteArray
  go/store/val/value_store.go
Labels: correctness_approved

#9155 fix status command after removing origin from remote
  go/cmd/dolt/commands/status.go
  integration-tests/bats/status.bats
Labels: cli, contribution

#9171 dolt status user contribution
  go/cmd/dolt/commands/status.go
  integration-tests/bats/status.bats
Labels: correctness_approved

#9174 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9177 [auto-bump] [no-release-notes] dependency by nicktobey
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9181 go: sqle/dprocedures: fetch,pull,push: Rebase the remote database before we interact with it.
  go/libraries/doltcore/sqle/dprocedures/dolt_fetch.go
  go/libraries/doltcore/sqle/dprocedures/dolt_pull.go
  go/libraries/doltcore/sqle/dprocedures/dolt_push.go
  integration-tests/go-sql-server-driver/auto_gc_test.go
  integration-tests/go-sql-server-driver/concurrent_gc_test.go
  integration-tests/go-sql-server-driver/gc_oldgen_conjoin_test.go
  integration-tests/go-sql-server-driver/sql_server_commit_concurrency_test.go
  integration-tests/go-sql-server-driver/sql_server_max_conns_test.go
  integration-tests/go-sql-server-driver/sqlserver_info_test.go
  integration-tests/go-sql-server-driver/testdef.go
  integration-tests/go-sql-server-driver/tests/sql-server-orig.yaml
  integration-tests/go-sql-server-driver/valctx_enabled_test.go
Labels: correctness_approved

#9189 [auto-bump] [no-release-notes] dependency by nicktobey
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9192 go: statspro: Make it possible for callers of StatsController.Stop() to block on the worker thread shutdown.
  go/libraries/doltcore/sqle/dprocedures/dolt_gc.go
  go/libraries/doltcore/sqle/dprocedures/stats_funcs.go
  go/libraries/doltcore/sqle/statspro/controller.go
  go/libraries/doltcore/sqle/statspro/listener.go
  go/libraries/doltcore/sqle/statspro/listener_test.go
  go/libraries/doltcore/sqle/statspro/worker_test.go
Labels: correctness_approved

#9193 go: store/datas/pull: puller.go: Fix incorrect location for Close call on PullChunkTracker.
  go/store/datas/pull/puller.go
Labels: correctness_approved

#9186 Fix --branch global option always flagging error "no valid repository"
  go/cmd/dolt/commands/status.go
  go/cmd/dolt/dolt.go
  integration-tests/bats/global-args.bats
Labels: correctness_approved

#9179 refactor: replace map iteration with maps.Copy
  go/libraries/utils/concurrentmap/concurrentmap.go
Labels: contribution

#9200 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9205 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9208 When a table is deleted on one branch and has its data modified on the other, record this as a schema conflict.
  go/libraries/doltcore/doltdb/root_val.go
  go/libraries/doltcore/merge/merge.go
  go/libraries/doltcore/schema/tag.go
  go/libraries/doltcore/sqle/alterschema.go
  go/libraries/doltcore/sqle/database.go
  go/libraries/doltcore/sqle/dtables/schema_conflicts_table.go
  integration-tests/bats/cherry-pick.bats
  integration-tests/bats/merge.bats
  integration-tests/bats/sql-cherry-pick.bats
Labels: correctness_approved

#9217 Run transaction tests with prepared statements
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
  go/libraries/doltcore/sqle/enginetest/dolt_engine_tests.go
  go/libraries/doltcore/sqle/enginetest/dolt_transaction_queries.go
Labels: correctness_approved

#9218 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9219 Adding `dolt_update_column_tag()` stored procedure
  go/cmd/dolt/cli/arg_parser_helpers.go
  go/cmd/dolt/commands/schcmds/update-tag.go
  go/libraries/doltcore/sqle/dprocedures/dolt_update_column_tag.go
  go/libraries/doltcore/sqle/dprocedures/init.go
  integration-tests/bats/sql-update-column-tag.bats
Labels: correctness_approved

#9224 [auto-bump] [no-release-notes] dependency by nicktobey
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9204 feat(import,csv,psv): Add support for importing CSV and PSV files without header rows
  go/cmd/dolt/commands/tblcmds/import.go
  go/libraries/doltcore/mvdata/csv_helper.go
  go/libraries/doltcore/mvdata/data_mover.go
  go/libraries/doltcore/mvdata/file_data_loc.go
  go/libraries/doltcore/mvdata/stream_data_loc.go
  integration-tests/bats/helper/local-remote.bash
  integration-tests/bats/import-no-header-csv.bats
  integration-tests/bats/import-no-header-psv.bats
Labels: contribution

#9225 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9215 go/store/nbs: table_index.go: Fix uint32 overflow in findPrefix when working with large table files.
  go/store/nbs/table_index.go
  go/store/nbs/table_index_test.go
Labels: correctness_approved

#9230 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9232 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9236 go: sqle/statspro: prollyStats: FlushFromMem: Fix long-held lock when flushing stats to disk.
  go/libraries/doltcore/sqle/statspro/stats_kv.go
  integration-tests/go-sql-server-driver/stats_gc_test.go
Labels: correctness_approved

#9234 [auto-bump] [no-release-notes] dependency by NathanGabrielson
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9238 [auto-bump] [no-release-notes] dependency by jennifersp
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9235 Log errors on a binlog connection
  go/libraries/doltcore/sqle/binlogreplication/binlog_replica_applier.go
Labels: correctness_approved

#9237 Sql shell warnings
  go/cmd/dolt/cli/command.go
  go/cmd/dolt/commands/blame.go
  go/cmd/dolt/commands/cvcmds/verify_constraints.go
  go/cmd/dolt/commands/engine/sql_print.go
  go/cmd/dolt/commands/schcmds/tags.go
  go/cmd/dolt/commands/sql.go
  go/cmd/dolt/commands/sql_slash.go
  go/cmd/dolt/commands/sqlserver/queryist_utils.go
  go/libraries/doltcore/sqle/system_variables.go
  integration-tests/bats/sql-shell.bats
  integration-tests/bats/sql-show-warnings.expect
  integration-tests/bats/sql-warning-detail.expect
  integration-tests/bats/sql-warning-summary.expect
Labels: correctness_approved

#9247 Made dolt diff --stat -r sql an error
  go/cmd/dolt/commands/diff_output.go
  integration-tests/bats/sql-diff.bats
Labels: correctness_approved

#9251 Allow dumping wrapper values to SQL
  go/libraries/doltcore/sqle/sqlfmt/row_fmt.go
  integration-tests/bats/export-tables.bats
Labels: correctness_approved

#9246 --all option for dolt log
  go/cmd/dolt/cli/arg_parser_helpers.go
  go/cmd/dolt/commands/log.go
  integration-tests/bats/log.bats
Labels: correctness_approved

#9254 Add support for MariaDB's GTID format
  go/libraries/doltcore/sqle/binlogreplication/binlog_position_store.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_replica_applier.go
Labels: correctness_approved

#9250 Implement commit_order in dolt_log system table and table function
  go/cmd/dolt/commands/utils.go
  go/libraries/doltcore/sqle/dtablefunctions/dolt_log_table_function.go
  go/libraries/doltcore/sqle/dtables/log_table.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries.go
  go/libraries/doltcore/sqle/sqlselect_test.go
  integration-tests/bats/system-tables.bats
  integration-tests/mysql-client-tests/node/workbenchTests/logs.js
  integration-tests/mysql-client-tests/node/workbenchTests/matchers.js
  integration-tests/mysql-client-tests/node/workbenchTests/merge.js
Labels: correctness_approved

#9267 Remove the --new-format flag from dolt init
  go/cmd/dolt/commands/init.go
  integration-tests/bats/init.bats
Labels: correctness_approved

#9272 Added a new constant for string columns created during schema import.
  go/cmd/dolt/commands/tblcmds/import.go
  go/libraries/doltcore/env/actions/infer_schema.go
  go/libraries/doltcore/env/actions/infer_schema_test.go
  go/libraries/doltcore/schema/typeinfo/varstring.go
  integration-tests/bats/import-create-tables.bats
  integration-tests/bats/schema-import.bats
Labels: correctness_approved

#9269 manifest safety checks
  go/store/nbs/file_manifest.go
  go/store/nbs/store_test.go
Labels: correctness_approved

#9273 Fix input validation of primary keys
  go/libraries/doltcore/mvdata/data_mover.go
  integration-tests/bats/import-create-tables.bats
Labels: correctness_approved
