Repository dolthub/dolt, pull requests merged in 2025-06, with the labels that each got.

#9122 implement `dolt_branch_status()`
  go/libraries/doltcore/sqle/dfunctions/has_ancestor.go
  go/libraries/doltcore/sqle/dfunctions/merge_base.go
  go/libraries/doltcore/sqle/dtablefunctions/dolt_branch_status_table_function.go
  go/libraries/doltcore/sqle/dtablefunctions/init.go
  go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
  go/libraries/doltcore/sqle/enginetest/dolt_engine_tests.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries.go
Labels: correctness_approved

#9296 Check for invalid ancestor merge spec
  go/libraries/doltcore/doltdb/ancestor_spec.go
  go/libraries/doltcore/doltdb/ancestor_spec_test.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries.go
Labels: correctness_approved

#9299 Improved chunk tracking during clone
  go/libraries/doltcore/env/actions/clone.go
  go/libraries/utils/iohelp/read_with_stats.go
Labels: correctness_approved

#9304 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump, keep-alive, correctness_approved

#9309 go/store/nbs: Fix a bug where GetChunkLocations{,WithPaths} can return the same chunk more than once if it is in newgen and oldgen.
  go/store/nbs/generational_chunk_store_test.go
  go/store/nbs/store.go
Labels: correctness_approved

#9311 [auto-bump] [no-release-notes] dependency by angelamayxie
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9310 tidy up errors
  go/go.mod
  go/go.sum
  go/libraries/doltcore/schema/index_coll.go
Labels: correctness_approved

#9317 go/store/nbs: archive_chunk_source.go: Make sure we skip getRecords marked found when fetching chunks.
  go/store/nbs/archive_chunk_source.go
  integration-tests/go-sql-server-driver/auto_gc_test.go
Labels: correctness_approved

#9327 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9328 [auto-bump] [no-release-notes] dependency by angelamayxie
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9331 [auto-bump] [no-release-notes] dependency by angelamayxie
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9329 go: store/datas/database_common: store/nbs/store.go: Fix some issues when pushing to a dolt sql-server that is itself running GC.
  go/cmd/dolt/dolt.go
  go/libraries/doltcore/env/actions/remotes.go
  go/libraries/utils/dynassert/dynassert.go
  go/libraries/utils/dynassert/dynassert_test.go
  go/store/datas/database_common.go
  go/store/nbs/file_table_persister.go
  go/store/nbs/file_table_reader.go
  go/store/nbs/store.go
  go/store/nbs/table_reader.go
  go/store/nbs/table_set.go
  integration-tests/bats/helper/common.bash
  integration-tests/go-sql-server-driver/auto_gc_test.go
  integration-tests/go-sql-server-driver/testdef.go
Labels: correctness_approved

#9308 dolt_stash stored procedure
  go/cmd/dolt/cli/arg_parser_helpers.go
  go/cmd/dolt/cli/flags.go
  go/cmd/dolt/commands/stashcmds/clear.go
  go/cmd/dolt/commands/stashcmds/drop.go
  go/cmd/dolt/commands/stashcmds/list.go
  go/cmd/dolt/commands/stashcmds/pop.go
  go/cmd/dolt/commands/stashcmds/stash.go
  go/libraries/doltcore/doltdb/doltdb.go
  go/libraries/doltcore/doltdb/stash.go
  go/libraries/doltcore/doltdb/system_table.go
  go/libraries/doltcore/ref/ref.go
  go/libraries/doltcore/ref/stash_ref.go
  go/libraries/doltcore/sqle/database.go
  go/libraries/doltcore/sqle/dprocedures/dolt_stash.go
  go/libraries/doltcore/sqle/dprocedures/init.go
  go/libraries/doltcore/sqle/dtables/stashes_table.go
  go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
  go/libraries/doltcore/sqle/enginetest/dolt_engine_tests.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_stash.go
  integration-tests/bats/ls.bats
  integration-tests/bats/sql-stash.bats
Labels: correctness_approved

#9338 [no-release-notes] manual bump
  go/go.mod
  go/go.sum
Labels: correctness_approved

#9271 go: sqle/statspro: Make ANALYZE TABLE faster by circumventing the rate limiter on stats work.
  go/libraries/doltcore/sqle/statspro/controller.go
  go/libraries/doltcore/sqle/statspro/jobqueue/serialqueue.go
  go/libraries/doltcore/sqle/statspro/jobqueue/serialqueue_test.go
  go/libraries/doltcore/sqle/statspro/listener.go
  go/libraries/doltcore/sqle/statspro/listener_test.go
  go/libraries/doltcore/sqle/statspro/rate_limiter.go
  go/libraries/doltcore/sqle/statspro/rate_limiter_test.go
  go/libraries/doltcore/sqle/statspro/stats_kv.go
  go/libraries/doltcore/sqle/statspro/stats_kv_test.go
  go/libraries/doltcore/sqle/statspro/worker.go
  go/libraries/doltcore/sqle/statspro/worker_test.go
  integration-tests/go-sql-server-driver/stats_gc_test.go
Labels: correctness_approved

#9336 Fix 4160 dolt commit amend flag for initial commit
  go/libraries/doltcore/sqle/dsess/session.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries.go
  go/store/datas/database_common.go
Labels: correctness_approved

#9354 [auto-bump] [no-release-notes] dependency by angelamayxie
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9364 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9377 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9378 [auto-bump] [no-release-notes] dependency by angelamayxie
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9369 Dolt Stash CLI Migration
  go/cmd/dolt/commands/stash.go
  go/cmd/dolt/commands/stashcmds/clear.go
  go/cmd/dolt/commands/stashcmds/drop.go
  go/cmd/dolt/commands/stashcmds/list.go
  go/cmd/dolt/commands/stashcmds/pop.go
  go/cmd/dolt/commands/stashcmds/stash.go
  go/cmd/dolt/doltcmd/doltcmd.go
  go/libraries/doltcore/doltdb/stash.go
  go/libraries/doltcore/sqle/dprocedures/dolt_stash.go
  go/libraries/doltcore/sqle/dtables/stashes_table.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_help.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_stash.go
  integration-tests/bats/helper/local-remote.bash
  integration-tests/bats/stash.bats
Labels: correctness_approved

#9382 contribution test
  go/cmd/dolt/commands/tblcmds/import.go
  go/cmd/dolt/commands/tblcmds/import_test.go
  integration-tests/bats/import-create-tables.bats
  integration-tests/bats/import-tables.bats
Labels: correctness_approved

#9380 [no-release-notes] backtick tests
  go/go.mod
  go/go.sum
  go/libraries/doltcore/merge/schema_integration_test.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_diff.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_schema_merge.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_verify_constraints.go
  go/libraries/doltcore/sqle/expranalysis/expranalysis.go
  integration-tests/bats/drop-create.bats
  integration-tests/bats/sql-check-constraints.bats
Labels: correctness_approved

#9361 Implemented `dolt_history_dolt_schemas` and `dolt_diff_dolt_schemas`
  go/libraries/doltcore/doltdb/system_table.go
  go/libraries/doltcore/sqle/database.go
  go/libraries/doltcore/sqle/dolt_schemas_diff_table.go
  go/libraries/doltcore/sqle/dolt_schemas_history_table.go
  go/libraries/doltcore/sqle/integration_test/dolt_schemas_history_diff_test.go
  integration-tests/bats/system-tables.bats
Labels: correctness_approved

#9399 go/libraries/doltcore/remotestorage: chunk_store.go: Fix a bug where we did not refresh expired table file URLs appropriately.
  go/libraries/doltcore/remotestorage/chunk_store.go
  go/libraries/doltcore/remotestorage/chunk_store_test.go
Labels: correctness_approved

#9387 archive format 3. Supporting larger indexes
  go/store/nbs/archive.go
  go/store/nbs/archive_reader.go
  go/store/nbs/archive_test.go
  go/store/nbs/archive_writer.go
  integration-tests/bats/archive-test-repos/README.txt
  integration-tests/bats/archive-test-repos/v1/noms/8p5e2m6skovfdjlh4jg3llr8sfvu384l
  integration-tests/bats/archive-test-repos/v1/noms/LOCK
  integration-tests/bats/archive-test-repos/v1/noms/manifest
  integration-tests/bats/archive-test-repos/v1/noms/oldgen/29o8a3uevcpr15tilcemb3s438edmoog.darc
  integration-tests/bats/archive-test-repos/v1/noms/oldgen/LOCK
  integration-tests/bats/archive-test-repos/v1/noms/oldgen/dnu4lr5j8sstbj5usbld7alsnuj5nf23.darc
  integration-tests/bats/archive-test-repos/v1/noms/oldgen/manifest
  integration-tests/bats/archive-test-repos/v1/repo_state.json
  integration-tests/bats/archive-test-repos/v2/noms/LOCK
  integration-tests/bats/archive-test-repos/v2/noms/i8ivrn485g73hao1foo3p7l2clq3gqqv
  integration-tests/bats/archive-test-repos/v2/noms/manifest
  integration-tests/bats/archive-test-repos/v2/noms/oldgen/27avtn2a3upddh52eu750m4709gfps7s.darc
  integration-tests/bats/archive-test-repos/v2/noms/oldgen/LOCK
  integration-tests/bats/archive-test-repos/v2/noms/oldgen/manifest
  integration-tests/bats/archive-test-repos/v2/noms/oldgen/sc0dq3agumuop5ngirrn7nqtgbk7lbrv
  integration-tests/bats/archive-test-repos/v2/repo_state.json
  integration-tests/bats/archive.bats
Labels: correctness_approved

#9396 Implement `dolt_diff_dolt_procedures`
  go/libraries/doltcore/sqle/database.go
  go/libraries/doltcore/sqle/dolt_procedures_diff_table.go
  go/libraries/doltcore/sqle/integration_test/dolt_schemas_history_diff_test.go
  integration-tests/bats/system-tables.bats
Labels: correctness_approved

#9402 Fix 9391 test for max1row err
  go/libraries/doltcore/sqle/enginetest/dolt_queries.go
Labels: correctness_approved

#9408 [auto-bump] [no-release-notes] dependency by angelamayxie
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9420 [auto-bump] [no-release-notes] dependency by angelamayxie
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9421 Another overflow issue in archive reader
  go/store/nbs/archive_reader.go
Labels: correctness_approved
