Repository dolthub/dolt, pull requests merged in 2025-02, with the labels that each got.

#8798 [no-release-notes] go: sqle: dprocedures: dolt_gc: Implement a session-aware GC safepoint controller.
  .gitignore
  go/cmd/dolt/commands/engine/sqlengine.go
  go/cmd/dolt/commands/sqlserver/server.go
  go/libraries/doltcore/dconfig/envvars.go
  go/libraries/doltcore/doltdb/doltdb.go
  go/libraries/doltcore/doltdb/workingset.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_metadata_persistence.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_replica_applier.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_replica_controller.go
  go/libraries/doltcore/sqle/database_provider.go
  go/libraries/doltcore/sqle/dprocedures/dolt_gc.go
  go/libraries/doltcore/sqle/dprocedures/init.go
  go/libraries/doltcore/sqle/dsess/gc_safepoint_controller.go
  go/libraries/doltcore/sqle/dsess/gc_safepoint_controller_test.go
  go/libraries/doltcore/sqle/dsess/session.go
  go/libraries/doltcore/sqle/dsess/transactions.go
  go/libraries/doltcore/sqle/enginetest/dolt_harness.go
  go/libraries/doltcore/sqle/logictest/dolt/doltharness.go
  go/libraries/doltcore/sqle/remotesrv.go
  go/libraries/doltcore/sqle/sqlddl_test.go
  go/libraries/doltcore/sqle/testutil.go
  integration-tests/go-sql-server-driver/concurrent_gc_test.go
Labels: correctness_approved

#8732 Tidy up journal writer code comments and error handling
  go/store/nbs/journal_record.go
  go/store/nbs/journal_record_test.go
  go/store/nbs/journal_writer.go
Labels: correctness_approved

#8812 [kvexec] fix left join nullability bug
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/kvexec/lookup_join.go
Labels: correctness_approved

#8808 [kvexec] literal types cast to lookup expr type
  go/libraries/doltcore/sqle/kvexec/builder.go
  go/libraries/doltcore/sqle/kvexec/lookup_join.go
  go/libraries/doltcore/sqle/kvexec/lookup_join_test.go
Labels: correctness_approved

#8814 [auto-bump] [no-release-notes] dependency by max-hoffman
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8809 go: sqle/binlogreplication: Add some waits for more reliable observations of IO_error results.
  go/libraries/doltcore/sqle/binlogreplication/binlog_primary_test.go
Labels: correctness_approved

#8811 [no-release-notes] go: store/nbs: GhostBlockStore: Add refCheck which participates in updating hasRecords.
  go/store/nbs/generational_chunk_store.go
  go/store/nbs/ghost_store.go
Labels: correctness_approved

#8810 [no-release-notes] go: nbs/store: Small cleanups to iterateAllChunks.
  go/store/nbs/archive_chunk_source.go
  go/store/nbs/archive_test.go
  go/store/nbs/chunk_source_adapter.go
  go/store/nbs/empty_chunk_source.go
  go/store/nbs/file_table_reader.go
  go/store/nbs/journal_chunk_source.go
  go/store/nbs/store.go
  go/store/nbs/table.go
  go/store/nbs/table_reader.go
Labels: correctness_approved

#8813 [no-release-notes] go: store/nbs: Unify logic from UpdateManifest and UpdateManifestWithAppendix
  go/store/nbs/store.go
  go/store/nbs/store_test.go
Labels: correctness_approved

#8817 Bug fix for encoding extended types in keys
  go/libraries/doltcore/schema/schema_impl.go
Labels: correctness_approved

#8831 Expand `ItemAccess::itemWidth` to 32 bits
  go/store/prolly/message/blob.go
  go/store/prolly/message/commit_closure.go
  go/store/prolly/message/item_access.go
  go/store/prolly/message/prolly_map_test.go
  go/store/prolly/tree/json_chunker.go
  go/store/prolly/tree/json_indexed_document.go
  go/store/prolly/tree/json_scanner.go
  go/store/prolly/tree/node_test.go
  integration-tests/bats/json.bats
Labels: correctness_approved

#8837 [no-release-notes] fix bad tests and bump
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/database_test.go
Labels: correctness_approved

#8838 allow `dolt init` on dolt repo with just `config.json`
  go/libraries/doltcore/env/config.go
  go/libraries/doltcore/env/environment.go
  integration-tests/bats/init.bats
Labels: correctness_approved

#8842 move status messages from parquet to stderr
  go/cmd/dolt/cli/stdio.go
  go/cmd/dolt/commands/sql.go
  integration-tests/bats/sql.bats
Labels: correctness_approved

#8828 [no-release-notes] go/store/nbs: Check for context cancelation in SaveHashes.
  go/store/nbs/store.go
Labels: correctness_approved

#8824 [no-release-notes] go: nbs,chunks: Have AddTableFilesToManifest check all dependencies are present.
  go/libraries/doltcore/doltdb/doltdb.go
  go/libraries/doltcore/remotesrv/grpc.go
  go/libraries/doltcore/remotestorage/chunk_store.go
  go/store/chunks/tablefilestore.go
  go/store/datas/pull/clone.go
  go/store/datas/pull/pull_table_file_writer.go
  go/store/datas/pull/pull_table_file_writer_test.go
  go/store/datas/pull/puller.go
  go/store/nbs/generational_chunk_store.go
  go/store/nbs/journal.go
  go/store/nbs/nbs_metrics_wrapper.go
  go/store/nbs/store.go
  go/store/nbs/store_test.go
  go/store/nbs/table.go
  go/store/nbs/table_set.go
  go/store/nbs/table_set_test.go
Labels: correctness_approved

#8830 [no-release-notes] go: sqle: DatabaseProvider: Fix double-creation of push-on-write commit hooks in registerNewDatabase.
  go/cmd/dolt/commands/engine/sqlengine.go
  go/cmd/dolt/commands/filter-branch.go
  go/libraries/doltcore/doltdb/commit_hooks_test.go
  go/libraries/doltcore/doltdb/doltdb.go
  go/libraries/doltcore/sqle/cluster/controller.go
  go/libraries/doltcore/sqle/cluster/initdbhook.go
  go/libraries/doltcore/sqle/database_provider.go
  go/libraries/doltcore/sqle/database_provider_test.go
  go/libraries/doltcore/sqle/dprocedures/dolt_backup.go
  go/libraries/doltcore/sqle/enginetest/dolt_harness.go
  go/libraries/doltcore/sqle/index/mergeable_indexes_setup_test.go
  go/libraries/doltcore/sqle/logictest/dolt/doltharness.go
  go/libraries/doltcore/sqle/replication.go
  go/libraries/doltcore/sqle/show_create_table.go
  go/libraries/doltcore/sqle/sqlddl_test.go
  go/libraries/doltcore/sqle/testutil.go
Labels: correctness_approved

#8821 New skipped test for bug merging roots with overlapping index defs
  go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
  go/libraries/doltcore/sqle/enginetest/dolt_transaction_queries.go
Labels: correctness_approved

#8820 [no-release-notes] go: sqle,doltdb: Make commit hooks take a DoltDB instead of a datas.Database. Move them to sqle.
  go/cmd/dolt/commands/sql_test.go
  go/cmd/dolt/commands/sqlserver/server_test.go
  go/libraries/doltcore/doltdb/doltdb.go
  go/libraries/doltcore/doltdb/hooksdatabase.go
  go/libraries/doltcore/sqle/cluster/commithook.go
  go/libraries/doltcore/sqle/commit_hooks.go
  go/libraries/doltcore/sqle/commit_hooks_test.go
  go/libraries/doltcore/sqle/database_provider_test.go
  go/libraries/doltcore/sqle/replication.go
  go/libraries/doltcore/sqle/replication_test.go
Labels: correctness_approved

#8846 [no-release-notes] go: nbs,remotesrv: Cleanup and comments for AddTableFilesToManifest ref checks PR.
  go/libraries/doltcore/remotesrv/grpc.go
  go/store/nbs/journal.go
  go/store/nbs/table_set.go
Labels: correctness_approved

#8847 Added an extension point for doltgres to lookup values in the dolt_ignore table
  go/libraries/doltcore/doltdb/ignore.go
Labels: correctness_approved

#8854 [no-release-notes] go: statspro: Add session lifecycle callbacks to integrate with session-aware GC safepoint controller.
  go/libraries/doltcore/sqle/statspro/auto_refresh.go
  go/libraries/doltcore/sqle/statspro/configure.go
Labels: correctness_approved

#8851 [no-release-notes] go/store/types: value_store: Add some unit tests for gc states and gcAddChunk behavior.
  go/store/types/value_store.go
  go/store/types/value_store_test.go
Labels: correctness_approved

#8858 [no-release-notes] go: sqle: dolt_gc: Purge read caches associated with the DoltDB as we begin GC.
  go/libraries/doltcore/doltdb/doltdb.go
  go/libraries/doltcore/doltdb/gc_test.go
  go/libraries/doltcore/sqle/dprocedures/dolt_gc.go
  go/store/nbs/gc_copier.go
  go/store/nbs/journal_chunk_source.go
  go/store/nbs/store_test.go
  go/store/prolly/tree/node_cache.go
  go/store/prolly/tree/node_cache_test.go
  go/store/prolly/tree/node_store.go
  go/store/prolly/tree/testutils.go
  go/store/types/value_store.go
  go/store/types/value_store_test.go
  go/store/valuefile/file_value_store.go
  integration-tests/go-sql-server-driver/concurrent_gc_test.go
Labels: correctness_approved

#8848 [no-release-notes] go: sqle: Change how we run background threads for replication hooks. Add session lifecycle callbacks for replication hooks.
  go/cmd/dolt/commands/engine/sqlengine.go
  go/cmd/dolt/commands/filter-branch.go
  go/cmd/dolt/commands/sql_test.go
  go/libraries/doltcore/sqle/commit_hooks.go
  go/libraries/doltcore/sqle/commit_hooks_test.go
  go/libraries/doltcore/sqle/database_provider.go
  go/libraries/doltcore/sqle/database_provider_test.go
  go/libraries/doltcore/sqle/enginetest/dolt_harness.go
  go/libraries/doltcore/sqle/index/mergeable_indexes_setup_test.go
  go/libraries/doltcore/sqle/logictest/dolt/doltharness.go
  go/libraries/doltcore/sqle/replication.go
  go/libraries/doltcore/sqle/replication_test.go
  go/libraries/doltcore/sqle/show_create_table.go
  go/libraries/doltcore/sqle/sqlddl_test.go
  go/libraries/doltcore/sqle/testutil.go
Labels: correctness_approved

#8863 [auto-bump] [no-release-notes] dependency by reltuk
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8864 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8860 Add pointer for checking super user perms for backup restore for doltgres
  go/libraries/doltcore/sqle/dprocedures/dolt_backup.go
Labels: correctness_approved

#8867 [auto-bump] [no-release-notes] dependency by max-hoffman
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8872 Add the dolt_backups table
  go/libraries/doltcore/doltdb/system_table.go
  go/libraries/doltcore/sqle/database.go
  go/libraries/doltcore/sqle/dtables/backups_table.go
  go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries.go
  go/libraries/doltcore/sqle/enginetest/dolt_system_table_queries.go
  integration-tests/bats/ls.bats
Labels: correctness_approved

#8861 [no-release-notes] go: remotestorage: chunk_store.go: Clean up ChunkCache.
  go/libraries/doltcore/remotestorage/chunk_cache.go
  go/libraries/doltcore/remotestorage/chunk_store.go
  go/libraries/doltcore/remotestorage/map_chunk_cache.go
  go/libraries/doltcore/remotestorage/map_chunk_cache_test.go
  go/libraries/doltcore/remotestorage/noop_chunk_cache.go
  go/libraries/doltcore/remotestorage/writebuffer.go
  go/libraries/doltcore/remotestorage/writebuffer_test.go
Labels: correctness_approved

#8877 [auto-bump] [no-release-notes] dependency by max-hoffman
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8880 go: publishrelease: buildpgobinaries.sh: Manually specify the SDK version of our toolchain so it shows up in our release binaries.
  go/utils/publishrelease/buildpgobinaries.sh
Labels: correctness_approved

#8849 sql-server: Add behavior: auto_gc_behavior: enable.
  go/cmd/dolt/commands/engine/sqlengine.go
  go/cmd/dolt/commands/sqlserver/command_line_config.go
  go/cmd/dolt/commands/sqlserver/server.go
  go/libraries/doltcore/doltdb/doltdb.go
  go/libraries/doltcore/remotesrv/grpc.go
  go/libraries/doltcore/remotesrv/http.go
  go/libraries/doltcore/servercfg/serverconfig.go
  go/libraries/doltcore/servercfg/yaml_config.go
  go/libraries/doltcore/servercfg/yaml_config_test.go
  go/libraries/doltcore/sqle/auto_gc.go
  go/libraries/doltcore/sqle/auto_gc_test.go
  go/libraries/doltcore/sqle/cluster/controller.go
  go/libraries/doltcore/sqle/cluster/initdbhook.go
  go/libraries/doltcore/sqle/dprocedures/dolt_gc.go
  go/store/nbs/file_table_reader.go
  go/store/nbs/journal.go
  go/store/nbs/journal_writer.go
  go/store/nbs/store.go
  integration-tests/go-sql-server-driver/auto_gc_test.go
Labels: correctness_approved

#8889 [no-release-notes] Account for null values in AddressTypeHandler columns.
  go/store/val/tuple_descriptor.go
Labels: correctness_approved

#8865 Don't rewrite table data when changing enum/varchar/varbinary type to make it more permissive.
  go/libraries/doltcore/dconfig/envvars.go
  go/libraries/doltcore/merge/merge_schema.go
  go/libraries/doltcore/schema/typecompatibility/type_compatibility.go
  go/libraries/doltcore/schema/typecompatibility/type_compatibility_test.go
  go/libraries/doltcore/sqle/alterschema.go
  go/libraries/doltcore/sqle/tables.go
  integration-tests/bats/schema-changes.bats
Labels: correctness_approved

#8894 [no-release-notes] go: statspro: auto_refresh: Fix session lifecycle leak in auto refresh thread.
  go/libraries/doltcore/sqle/statspro/auto_refresh.go
Labels: correctness_approved

#8895 [no-release-notes] go: sqle/cluster: commithook.go: Fix up some calls into the DoltDB layer to always use the contexts given to us from the context factory.
  go/libraries/doltcore/sqle/cluster/commithook.go
Labels: correctness_approved

#8896 go: sqle: remotesrv: Fix SqlContext interceptors to always forward along the sql.Context as the request Context as well.
  go/libraries/doltcore/sqle/remotesrv.go
Labels: correctness_approved

#8899 [auto-bump] [no-release-notes] dependency by reltuk
  go/cmd/dolt/commands/engine/sqlengine.go
  go/cmd/dolt/commands/sqlserver/server.go
  go/go.mod
  go/go.sum
Labels: gms-bump, keep-alive, correctness_approved

#8892 [no-release-notes] Add Archive Backup and AWS support
  go/cmd/dolt/commands/archive.go
  go/cmd/dolt/commands/backup.go
  go/libraries/doltcore/env/multi_repo_env.go
  go/store/nbs/archive_build.go
  go/store/nbs/archive_chunk_source.go
  go/store/nbs/archive_reader.go
  go/store/nbs/archive_test.go
  go/store/nbs/aws_table_chunk_source.go
  go/store/nbs/aws_table_chunk_source_test.go
  go/store/nbs/aws_table_persister.go
  go/store/nbs/bs_persister.go
  go/store/nbs/chunk_source_adapter.go
  go/store/nbs/empty_chunk_source.go
  go/store/nbs/file_table_persister.go
  go/store/nbs/file_table_reader.go
  go/store/nbs/file_table_reader_test.go
  go/store/nbs/gc_copier.go
  go/store/nbs/journal.go
  go/store/nbs/journal_chunk_source.go
  go/store/nbs/metadata.go
  go/store/nbs/no_conjoin_bs_persister.go
  go/store/nbs/root_tracker_test.go
  go/store/nbs/s3_object_reader.go
  go/store/nbs/s3_table_reader.go
  go/store/nbs/s3_table_reader_test.go
  go/store/nbs/store.go
  go/store/nbs/table.go
  go/store/nbs/table_persister.go
  go/store/nbs/table_reader.go
  go/utils/copyrightshdrs/main.go
  integration-tests/bats/archive-aws.bats
  integration-tests/bats/archive.bats
Labels: correctness_approved

#8897 go: Bump to go 1.24. Fix some `vet` errors related to non-constant format strings.
  .github/workflows/cd-release-pgo.yaml
  go/Godeps/LICENSES
  go/cmd/dolt/commands/add.go
  go/cmd/dolt/commands/backup.go
  go/cmd/dolt/commands/branch.go
  go/cmd/dolt/commands/checkout.go
  go/cmd/dolt/commands/clone.go
  go/cmd/dolt/commands/diff_output.go
  go/cmd/dolt/commands/dump_docs.go
  go/cmd/dolt/commands/log_test.go
  go/cmd/dolt/commands/login.go
  go/cmd/dolt/commands/push.go
  go/cmd/dolt/commands/read_tables.go
  go/cmd/dolt/commands/remote.go
  go/cmd/dolt/commands/reset.go
  go/cmd/dolt/commands/sql.go
  go/cmd/dolt/commands/tblcmds/import.go
  go/cmd/dolt/commands/utils.go
  go/cmd/dolt/commands/version.go
  go/cmd/dolt/errhand/panic_utils.go
  go/go.mod
  go/go.work
  go/libraries/doltcore/remotestorage/internal/reliable/http.go
  go/libraries/doltcore/rowconv/field_mapping.go
  go/libraries/doltcore/schema/typeinfo/typeinfo_test.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_primary_controller.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_replica_applier.go
  go/libraries/doltcore/sqle/database.go
  go/libraries/doltcore/sqle/dprocedures/dolt_checkout.go
  go/libraries/doltcore/sqle/dprocedures/dolt_clone.go
  go/libraries/doltcore/sqle/dprocedures/dolt_commit.go
  go/libraries/doltcore/sqle/dprocedures/dolt_merge.go
  go/libraries/doltcore/sqle/dsess/session.go
  go/libraries/doltcore/sqle/dtablefunctions/dolt_diff_stat_table_function.go
  go/libraries/doltcore/sqle/dtablefunctions/dolt_diff_summary_table_function.go
  go/libraries/doltcore/sqle/dtables/commit_diff_table.go
  go/libraries/doltcore/sqle/dtables/diff_table.go
  go/libraries/doltcore/sqle/schema_override.go
  go/libraries/doltcore/sqle/statspro/analyze.go
  go/libraries/doltcore/table/untyped/xlsx/marshaling.go
  go/performance/import_benchmarker/cmd/main.go
  go/performance/import_benchmarker/testdef.go
  go/performance/sysbench/cmd/main.go
  go/store/blobstore/blobstore_test.go
  go/store/datas/stashlist.go
  go/store/datas/statistics.go
  go/store/datas/tuple.go
  go/store/nbs/root_tracker_test.go
  go/store/prolly/artifact_map_test.go
  go/store/types/serial_message.go
  go/store/types/value_stats.go
  integration-tests/go-sql-server-driver/go.mod
Labels: correctness_approved

#8903 [no-release-notes] go/store/nbs: NomsBlockStore.UpdateManifest{,WithAppendix} pre-open table files before the manifest updates.
  go/store/nbs/store.go
Labels: correctness_approved

#8904 [auto-bump] [no-release-notes] dependency by reltuk
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8905 add pager support to sql shell
  go/cmd/dolt/commands/blame.go
  go/cmd/dolt/commands/cvcmds/verify_constraints.go
  go/cmd/dolt/commands/engine/sql_print.go
  go/cmd/dolt/commands/schcmds/tags.go
  go/cmd/dolt/commands/sql.go
  go/cmd/dolt/commands/sql_slash.go
Labels: correctness_approved
