Repository dolthub/dolt, pull requests merged in 2025-04, with the labels that each got.

#9063 Normalize AUTO_INCREMENT values in tables.
  go/libraries/doltcore/doltdb/durable/table.go
  go/libraries/doltcore/sqle/tables.go
  integration-tests/bats/auto_increment.bats
Labels: correctness_approved

#9061 Bug fix for doltgres range iter
  go/libraries/doltcore/sqle/index/doltgres_iter.go
Labels: correctness_approved

#9065 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9060 [no-release-notes] go: dsess/transactions.go: Improve comment about the presence of branches without working sets.
  go/libraries/doltcore/sqle/dsess/transactions.go
Labels: correctness_approved

#9066 go/store/nbs: Add info level logging for a store conjoin.
  go/libraries/doltcore/dbfactory/file.go
  go/libraries/doltcore/doltdb/doltdb.go
  go/store/nbs/generational_chunk_store.go
  go/store/nbs/store.go
Labels: correctness_approved

#9067 go: sqle/dprocedures: Implement operational inspection hook, dolt_thread_dump stored procedure.
  go/libraries/doltcore/sqle/dprocedures/dolt_thread_dump.go
  go/libraries/doltcore/sqle/dprocedures/init.go
  go/libraries/utils/goroutinedump/goroutinedump.go
  integration-tests/bats/sql-shell.bats
Labels: correctness_approved

#9068 [no-release-notes] go: store/nbs: store.go: Remove unused WithoutConjoiner. Rename some struct fields which were overly terse.
  go/store/nbs/root_tracker_test.go
  go/store/nbs/stats_test.go
  go/store/nbs/store.go
  go/store/nbs/store_test.go
Labels: correctness_approved

#9080 [no-release-notes] Update local benchamark scripts to match current server config.
  go/performance/scripts/local_sysbench.sh
  go/performance/scripts/local_tpcc.sh
Labels: correctness_approved

#9071 Fix typo mistake of commmitted
  go/libraries/doltcore/table/editor/table_edit_accumulator_test.go
Labels: contribution

#9089 refactor: use the built-in max/min to simplify the code
  go/store/nbs/generational_chunk_store.go
Labels: correctness_approved

#9084 [no release notes] Handle NULL adaptive values
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/enginetest/blob_queries.go
  go/store/val/adaptive_value.go
  go/store/val/tuple_builder.go
Labels: correctness_approved

#9075 Don't alter branch head outside of transactions when amending a commit
  go/libraries/doltcore/doltdb/commit.go
  go/libraries/doltcore/env/actions/commit.go
  go/libraries/doltcore/migrate/progress.go
  go/libraries/doltcore/sqle/dsess/session.go
  go/store/datas/commit_options.go
  go/store/datas/database_common.go
  integration-tests/go-sql-server-driver/sql_server_commit_concurrency_test.go
Labels: correctness_approved

#9093 [no-release-notes] Have TextStorage and ByteArray implement driver.Value
  go/store/prolly/tree/prolly_fields.go
  go/store/val/adaptive_value.go
  go/store/val/tuple_builder_test.go
  go/store/val/value_store.go
Labels: correctness_approved

#9083 Support for non-MySQL query elements during merge
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/expranalysis/expranalysis.go
  go/libraries/doltcore/sqle/sqlfmt/row_fmt.go
  go/libraries/doltcore/sqle/sqlfmt/schema_fmt.go
Labels: correctness_approved

#9095 Add the archive --purge flag to clean up table files
  go/cmd/dolt/commands/archive.go
  go/store/nbs/archive_build.go
  integration-tests/bats/archive.bats
Labels: correctness_approved

#9097 Prevent unnecessary bytes <-> string conversions and unnecessary allocations when converying to bytes.
  go/cmd/dolt/commands/remote.go
  go/go.mod
  go/go.sum
  go/go.work.sum
  go/store/prolly/tree/json_indexed_document.go
Labels: correctness_approved

#9100 Consistently use pointer receivers for TextStorage methods.
  go/store/val/value_store.go
Labels: correctness_approved

#9105 [auto-bump] [no-release-notes] dependency by zachmu
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9112 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9108 [no-release-notes] Correctly identify when we can get the address of a ByteArray or TextStorage without unwrapping it.
  go/store/prolly/tree/prolly_fields.go
Labels: correctness_approved

#9115 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump, keep-alive, correctness_approved

#9124 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9129 More precision on the date column in the dolt_diff table
  go/libraries/doltcore/sqle/dtables/unscoped_diff_table.go
Labels: minor version bump, correctness_approved

#9128 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9131 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
  go/libraries/doltcore/doltdb/foreign_key_coll.go
  go/libraries/doltcore/sqle/tables.go
Labels: gms-bump, correctness_approved

#9132 Bump golang.org/x/net in /go/gen/proto/dolt/services/eventsapi
  go/gen/proto/dolt/services/eventsapi/go.mod
  go/gen/proto/dolt/services/eventsapi/go.sum
  go/go.mod
  go/go.sum
  go/go.work.sum
  integration-tests/go-sql-server-driver/go.mod
  integration-tests/go-sql-server-driver/go.sum
Labels: correctness_approved

#9118 Enable the GC process to write to archive files
  go/cmd/dolt/cli/arg_parser_helpers.go
  go/cmd/dolt/cli/flags.go
  go/cmd/dolt/commands/gc.go
  go/cmd/dolt/commands/sqlserver/command_line_config.go
  go/cmd/dolt/commands/sqlserver/server.go
  go/cmd/dolt/commands/sqlserver/server_test.go
  go/libraries/doltcore/doltdb/doltdb.go
  go/libraries/doltcore/doltdb/gc_test.go
  go/libraries/doltcore/servercfg/serverconfig.go
  go/libraries/doltcore/servercfg/yaml_config.go
  go/libraries/doltcore/servercfg/yaml_config_test.go
  go/libraries/doltcore/sqle/auto_gc.go
  go/libraries/doltcore/sqle/auto_gc_test.go
  go/libraries/doltcore/sqle/dprocedures/dolt_gc.go
  go/store/chunks/chunk_store.go
  go/store/chunks/memory_store.go
  go/store/chunks/test_utils.go
  go/store/datas/database.go
  go/store/datas/database_common.go
  go/store/nbs/archive_writer.go
  go/store/nbs/cmp_chunk_table_writer.go
  go/store/nbs/gc_copier.go
  go/store/nbs/generational_chunk_store.go
  go/store/nbs/nbs_metrics_wrapper.go
  go/store/nbs/store.go
  go/store/nbs/store_test.go
  go/store/nbs/table_persister.go
  go/store/types/value_store.go
  go/store/types/value_store_test.go
  integration-tests/bats/garbage_collection.bats
Labels: correctness_approved

#9140 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, keep-alive, correctness_approved

#9144 Bug fix: allow dropping tables with FK constraints
  go/libraries/doltcore/merge/merge.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_schema_merge.go
Labels: correctness_approved

#9135 go/store/nbs: conjoiner.go,store.go: Make conjoin asynchronous.
  go/store/blobstore/inmem.go
  go/store/nbs/conjoiner.go
  go/store/nbs/stats_test.go
  go/store/nbs/store.go
  go/store/nbs/store_test.go
Labels: correctness_approved

#9046 [dfunctions] dolt_join_cost prints full join memo
  go/libraries/doltcore/sqle/dfunctions/init.go
  go/libraries/doltcore/sqle/dfunctions/join_cost.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries.go
Labels: correctness_approved

#9106 Stats NBS gc safety
  go/cmd/dolt/commands/sqlserver/server_test.go
  go/libraries/doltcore/sqle/dprocedures/dolt_gc.go
  go/libraries/doltcore/sqle/statspro/controller.go
  go/libraries/doltcore/sqle/statspro/jobqueue/serialqueue.go
  go/libraries/doltcore/sqle/statspro/jobqueue/serialqueue_test.go
  go/libraries/doltcore/sqle/statspro/listener.go
  go/libraries/doltcore/sqle/statspro/stats_kv.go
  go/libraries/doltcore/sqle/statspro/stats_kv_test.go
  go/libraries/doltcore/sqle/statspro/worker.go
Labels: correctness_approved

#9146 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9141 Add a smoke test for server-side cursor support
  integration-tests/mysql-client-tests/java/MySQLConnectorTest.java
Labels: correctness_approved

#9148 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9152 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9151 go: Thread Context a bit. Cleanup some uses of sql.NewContext.
  go/cmd/dolt/commands/archive.go
  go/cmd/dolt/commands/filter-branch.go
  go/cmd/dolt/commands/schcmds/copy-tags.go
  go/cmd/dolt/commands/show.go
  go/cmd/dolt/commands/stashcmds/pop.go
  go/cmd/dolt/commands/stashcmds/stash.go
  go/libraries/doltcore/cherry_pick/cherry_pick.go
  go/libraries/doltcore/doltdb/commit_itr.go
  go/libraries/doltcore/dtestutils/testcommands/multienv.go
  go/libraries/doltcore/env/actions/branch.go
  go/libraries/doltcore/env/actions/checkout.go
  go/libraries/doltcore/env/actions/clone.go
  go/libraries/doltcore/env/actions/commitwalk/commitwalk.go
  go/libraries/doltcore/env/actions/remotes.go
  go/libraries/doltcore/env/actions/reset.go
  go/libraries/doltcore/env/actions/tag.go
  go/libraries/doltcore/env/actions/workspace.go
  go/libraries/doltcore/env/environment.go
  go/libraries/doltcore/env/memory.go
  go/libraries/doltcore/env/remotes.go
  go/libraries/doltcore/env/repo_state.go
  go/libraries/doltcore/merge/action.go
  go/libraries/doltcore/merge/merge_prolly_rows.go
  go/libraries/doltcore/merge/merge_schema.go
  go/libraries/doltcore/rebase/filter_branch.go
  go/libraries/doltcore/rebase/rebase.go
  go/libraries/doltcore/sqle/clusterdb/database.go
  go/libraries/doltcore/sqle/database.go
  go/libraries/doltcore/sqle/database_provider.go
  go/libraries/doltcore/sqle/dfunctions/dolt_merge_base.go
  go/libraries/doltcore/sqle/dprocedures/dolt_backup.go
  go/libraries/doltcore/sqle/dprocedures/dolt_branch.go
  go/libraries/doltcore/sqle/dprocedures/dolt_checkout.go
  go/libraries/doltcore/sqle/dprocedures/dolt_checkout_helpers.go
  go/libraries/doltcore/sqle/dprocedures/dolt_count_commits.go
  go/libraries/doltcore/sqle/dprocedures/dolt_merge.go
  go/libraries/doltcore/sqle/dprocedures/dolt_pull.go
  go/libraries/doltcore/sqle/dprocedures/dolt_push.go
  go/libraries/doltcore/sqle/dprocedures/dolt_remote.go
  go/libraries/doltcore/sqle/dprocedures/dolt_reset.go
  go/libraries/doltcore/sqle/dprocedures/dolt_tag.go
  go/libraries/doltcore/sqle/dsess/database_session_state.go
  go/libraries/doltcore/sqle/dsess/session.go
  go/libraries/doltcore/sqle/dsess/session_db_provider.go
  go/libraries/doltcore/sqle/dsess/session_state_adapter.go
  go/libraries/doltcore/sqle/dtablefunctions/dolt_log_table_function.go
  go/libraries/doltcore/sqle/dtablefunctions/dolt_patch_table_function.go
  go/libraries/doltcore/sqle/dtables/column_diff_table.go
  go/libraries/doltcore/sqle/dtables/commit_ancestors_table.go
  go/libraries/doltcore/sqle/dtables/commits_table.go
  go/libraries/doltcore/sqle/dtables/diff_table.go
  go/libraries/doltcore/sqle/dtables/log_table.go
  go/libraries/doltcore/sqle/dtables/status_table.go
  go/libraries/doltcore/sqle/dtables/unscoped_diff_table.go
  go/libraries/doltcore/sqle/history_table.go
  go/libraries/doltcore/sqle/index/mergeable_indexes_setup_test.go
  go/libraries/doltcore/sqle/testutil.go
  go/libraries/doltcore/sqle/user_space_database.go
Labels: correctness_approved

#9153 add `NUL` character to string increment
  go/go.mod
  go/go.sum
  go/store/prolly/tuple_range.go
Labels: correctness_approved

#9147 go: sqle/dsess: Serialize transactions on a given database branch, instead of globally on all databases and all branches.
  go/libraries/doltcore/sqle/dsess/transactions.go
  go/libraries/utils/keymutex/keymutex.go
  go/libraries/utils/keymutex/keymutex_test.go
Labels: correctness_approved

#9158 Fix NULL default bug when merging branches with different schemas
  go/libraries/doltcore/sqle/enginetest/dolt_queries_schema_merge.go
  go/libraries/doltcore/sqle/sqlfmt/schema_fmt.go
Labels: correctness_approved

#9159 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9114 [no-release-notes] bump stored procedure changes
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
  integration-tests/bats/sql.bats
Labels: correctness_approved
