Repository dolthub/dolt, pull requests merged in 2025-07, with the labels that each got.

#9432 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9411 go: sqle/statspro: Rework the way stats manages its session in order to make it safe to continue collecting stats during a GC run.
  go/libraries/doltcore/sqle/dprocedures/dolt_gc.go
  go/libraries/doltcore/sqle/statspro/controller.go
  go/libraries/doltcore/sqle/statspro/worker.go
  go/libraries/doltcore/sqle/statspro/worker_test.go
  integration-tests/go-sql-server-driver/auto_gc_test.go
Labels: correctness_approved

#9419 Add indexes to dolt_commit_diff_ tables that include the primary key of the underlying table
  go/libraries/doltcore/sqle/dtablefunctions/dolt_diff.go
  go/libraries/doltcore/sqle/dtablefunctions/dolt_patch.go
  go/libraries/doltcore/sqle/dtables/column_diff_table.go
  go/libraries/doltcore/sqle/dtables/commit_diff_table.go
  go/libraries/doltcore/sqle/dtables/diff_iter.go
  go/libraries/doltcore/sqle/dtables/diff_table.go
  go/libraries/doltcore/sqle/index/dolt_index.go
  integration-tests/bats/sql-commit-diff.bats
Labels: correctness_approved

#9445 Swallow gc NoOp err
  go/cmd/dolt/commands/gc.go
  go/store/types/value_store.go
Labels: correctness_approved

#9450 [auto-bump] [no-release-notes] dependency by angelamayxie
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9446 Flush outputs in archive command. Fixes flaky test
  go/cmd/dolt/commands/archive.go
Labels: correctness_approved

#9441 Only print `Query Ok` results in interactive shell.
  go/cmd/dolt/commands/blame.go
  go/cmd/dolt/commands/cvcmds/verify_constraints.go
  go/cmd/dolt/commands/engine/sql_print.go
  go/cmd/dolt/commands/schcmds/tags.go
  go/cmd/dolt/commands/sql.go
  go/cmd/dolt/commands/sql_test.go
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/enginetest/dolt_queries.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_merge.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_schema_override.go
  go/libraries/doltcore/sqle/enginetest/dolt_transaction_commit_test.go
  go/libraries/doltcore/sqle/enginetest/dolt_transaction_queries.go
  go/libraries/doltcore/sqle/enginetest/prepared_queries.go
  go/libraries/doltcore/sqle/enginetest/sysbench_test.go
  integration-tests/bats/1pk5col-ints.bats
  integration-tests/bats/1pk5col-strings.bats
  integration-tests/bats/2pk5cols-ints.bats
  integration-tests/bats/branch-control.bats
  integration-tests/bats/create-views.bats
  integration-tests/bats/db-revision-specifiers.bats
  integration-tests/bats/foreign-keys.bats
  integration-tests/bats/index.bats
  integration-tests/bats/keyless-foreign-keys.bats
  integration-tests/bats/remotes-sql-server.bats
  integration-tests/bats/replication-multidb.bats
  integration-tests/bats/replication.bats
  integration-tests/bats/sql-batch.bats
  integration-tests/bats/sql-shell-multi-stmt-timings.expect
  integration-tests/bats/sql-shell-ok-result.expect
  integration-tests/bats/sql-shell-use.expect
  integration-tests/bats/sql-shell.bats
  integration-tests/bats/sql-spatial-types.bats
  integration-tests/bats/sql.bats
  integration-tests/mysql-client-tests/node/workbenchTests/table.js
Labels: correctness_approved

#9442 [no-release-notes] More archive reader overflow fixes
  go/store/nbs/archive_chunk_source.go
  go/store/nbs/archive_reader.go
Labels: correctness_approved

#9455 [auto-bump] [no-release-notes] dependency by angelamayxie
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9458 [no-release-notes] go: store/nbs: file_table_reader.go: Fix clone() so that it actually uses the reference count.
  go/store/nbs/archive_reader.go
  go/store/nbs/archive_writer.go
  go/store/nbs/file_table_reader.go
  go/store/nbs/gc_copier.go
  go/store/nbs/store.go
  go/store/types/value_store.go
  integration-tests/go-sql-server-driver/auto_gc_test.go
Labels: correctness_approved

#9465 Bug fix: Copy lookup details for `dolt_commit_diff`
  go/libraries/doltcore/sqle/dtables/diff_iter.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_diff.go
Labels: correctness_approved

#9462 [no-release-notes] NewGen -> OldGen admin script
  go/cmd/dolt/commands/admin/admin.go
  go/cmd/dolt/commands/admin/newgen_to_oldgen.go
  go/store/nbs/admin_newgen_to_oldgen.go
Labels: correctness_approved

#9429 refactor(import): show actual arg count in import error messages
  go/cmd/dolt/commands/tblcmds/import.go
  integration-tests/bats/import-tables.bats
Labels: contribution

#9466 refactor(import): show actual arg count in import error messages
  go/cmd/dolt/commands/tblcmds/import.go
  integration-tests/bats/import-tables.bats
Labels: correctness_approved

#9435 go: statspro: Small cleanups in error handling and session command handling.
  go/libraries/doltcore/sqle/dprocedures/stats_funcs.go
  go/libraries/doltcore/sqle/statspro/worker.go
Labels: correctness_approved

#9495 [auto-bump] [no-release-notes] dependency by elianddb
  go/go.mod
  go/go.sum
  integration-tests/bats/import-append-tables.bats
Labels: gms-bump, keep-alive, correctness_approved

#9492 dolthub/dolt#9481 - Move auto_increment validation to GMS
  go/libraries/doltcore/schema/col_coll.go
  go/libraries/doltcore/schema/schema_impl.go
  go/libraries/doltcore/schema/schema_test.go
Labels: correctness_approved

#9436 Improve `dolt checkout` error handling for missing tables
  go/cmd/dolt/commands/checkout.go
  go/libraries/doltcore/sqle/dprocedures/dolt_checkout.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries.go
  integration-tests/bats/checkout.bats
Labels: contribution

#9504 [auto-bump] [no-release-notes] dependency by elianddb
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9518 [auto-bump] [no-release-notes] dependency by angelamayxie
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9526 Update GC docs to have correct max for archive level
  go/cmd/dolt/cli/arg_parser_helpers.go
Labels: correctness_approved

#9463 Fixed Skipped bats test for fetching a tag ref
  go/libraries/doltcore/env/actions/remotes.go
  go/libraries/doltcore/ref/ref_spec.go
  integration-tests/bats/fetch.bats
Labels: correctness_approved

#9533 [auto-bump] [no-release-notes] dependency by elianddb
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9537 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9538 [auto-bump] [no-release-notes] dependency by elianddb
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9545 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9547 Fix off-by-one error in deciding whether to match keys or prefixes
  go/libraries/doltcore/sqle/index/secondary_iter.go
Labels: correctness_approved

#9514 #9508 - Fix dolt_log table function to support bind variables in prepared statements
  go/libraries/doltcore/sqle/dtablefunctions/dolt_branch_status_table_function.go
  go/libraries/doltcore/sqle/dtablefunctions/dolt_log.go
  go/libraries/doltcore/sqle/dtablefunctions/dolt_log_test.go
  integration-tests/bats/system-tables.bats
Labels: correctness_approved

#9552 [auto-bump] [no-release-notes] dependency by angelamayxie
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9564 dolthub/dolt#9556 - Fix JSON path parsing for unnecessarily quoted field names
  go/store/prolly/tree/json_location.go
  integration-tests/bats/json.bats
Labels: correctness_approved

#9566 [auto-bump] [no-release-notes] dependency by angelamayxie
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9567 [auto-bump] [no-release-notes] dependency by angelamayxie
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
Labels: gms-bump, keep-alive, correctness_approved

#9577 Remove broken symlink
  go/performance/utils/benchmark_runner/tpcc.lua
Labels: correctness_approved

#9551 dolthub/dolt#9530 - Fix auto-increment display for SHOW CREATE TABLE
  go/libraries/doltcore/sqle/dsess/autoincrement_tracker.go
  integration-tests/bats/auto_increment.bats
Labels: correctness_approved

#9584 [auto-bump] [no-release-notes] dependency by elianddb
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9586 [no-release-notes] .github: workflows/bump-dependency.yaml: Add support for eventsapi_schema bump.
  .github/workflows/bump-dependency.yaml
Labels: github_actions

#9592 [auto-bump] [no-release-notes] dependency by angelamayxie
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9587 Bug fix: Update secondary index correctly during a merge with a schema change
  go/libraries/doltcore/merge/merge_prolly_rows.go
  go/libraries/doltcore/merge/violations_fk_prolly.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_schema_merge.go
Labels: correctness_approved

#9599 go: sqle: autoincrement_tracker: When we close the engine.SqlEngine, finalize any ongoing initialization of AutoIncrementTrackers.
  go/cmd/dolt/commands/engine/sqlengine.go
  go/libraries/doltcore/sqle/clusterdb/database.go
  go/libraries/doltcore/sqle/database.go
  go/libraries/doltcore/sqle/database_provider.go
  go/libraries/doltcore/sqle/dsess/auto_increment_tracker_test.go
  go/libraries/doltcore/sqle/dsess/autoincrement_tracker.go
  go/libraries/doltcore/sqle/dsess/globalstate.go
  go/libraries/doltcore/sqle/dsess/session_db_provider.go
  go/libraries/doltcore/sqle/user_space_database.go
Labels: correctness_approved

#9560 Better dolt_query_catalog system table
  go/cmd/dolt/commands/ci/view.go
  go/cmd/dolt/commands/sql.go
  go/cmd/dolt/commands/utils.go
  go/libraries/doltcore/doltdb/system_table.go
  go/libraries/doltcore/sqle/database.go
  go/libraries/doltcore/sqle/dtables/docs_table.go
  go/libraries/doltcore/sqle/dtables/ignore_table.go
  go/libraries/doltcore/sqle/dtables/query_catalog_table.go
  go/libraries/doltcore/sqle/dtables/query_catalog_table_test.go
  go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
  go/libraries/doltcore/sqle/enginetest/dolt_engine_tests.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_query_catalog.go
  go/libraries/doltcore/sqle/sqlddl_test.go
  go/libraries/doltcore/sqle/sqldelete_test.go
  go/libraries/doltcore/sqle/sqlinsert_test.go
  go/libraries/doltcore/sqle/sqlreplace_test.go
  go/libraries/doltcore/sqle/sqlselect_test.go
  go/libraries/doltcore/sqle/sqlupdate_test.go
  integration-tests/bats/helper/local-remote.bash
  integration-tests/bats/query-catalog.bats
  integration-tests/bats/sql-server.bats
Labels: correctness_approved

#9601 [auto-bump] [no-release-notes] dependency by angelamayxie
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9593 [no-release-notes] join opt bump and add test
  go/go.mod
  go/go.sum
Labels: correctness_approved

#9611 [auto-bump] [no-release-notes] dependency by angelamayxie
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#9561 dolthub/dolt#9554 - Fix varbinary fields displaying as unicode instead of hex
  go/cmd/dolt/commands/blame.go
  go/cmd/dolt/commands/cvcmds/verify_constraints.go
  go/cmd/dolt/commands/debug.go
  go/cmd/dolt/commands/engine/sql_print.go
  go/cmd/dolt/commands/schcmds/tags.go
  go/cmd/dolt/commands/sql.go
  go/cmd/dolt/commands/sqlserver/queryist_utils.go
  go/libraries/doltcore/sqle/sqlutil/sql_row.go
  integration-tests/bats/helper/common_expect_functions.tcl
  integration-tests/bats/sql-shell-binary-as-hex.expect
  integration-tests/bats/sql-shell.bats
Labels: correctness_approved
