Repository dolthub/dolt, pull requests merged in 2025-01, with the labels that each got.

#8709 [no-release-notes] /go/cmd/dolt/commands: export stream scanner
  go/cmd/dolt/commands/filter-branch.go
  go/cmd/dolt/commands/sql.go
  go/cmd/dolt/commands/sql_statement_scanner.go
  go/cmd/dolt/commands/sql_statement_scanner_test.go
Labels: correctness_approved

#8711 [no-release-notes] go,bats: Small fixes for some testing around GC.
  go/store/nbs/archive_build.go
  go/store/nbs/store_test.go
  go/store/types/value_store.go
  integration-tests/bats/archive.bats
  integration-tests/bats/fsck.bats
Labels: correctness_approved

#8713 Allow storing/reading 32 bit offsets in nodes.
  go/store/prolly/message/address_map.go
  go/store/prolly/message/blob.go
  go/store/prolly/message/commit_closure.go
  go/store/prolly/message/item_access.go
  go/store/prolly/message/merge_artifacts.go
  go/store/prolly/message/message.go
  go/store/prolly/message/prolly_map.go
  go/store/prolly/message/prolly_map_test.go
  go/store/prolly/message/serialize.go
  go/store/prolly/tree/node_test.go
  go/store/val/codec.go
  go/store/val/codec_test.go
  go/store/val/tuple_compare.go
  go/store/val/tuple_descriptor.go
Labels: correctness_approved

#8715 [no-release-notes] go/store/chunks: Remove unused remote_requests structs and related code.
  go/store/chunks/remote_requests.go
  go/store/chunks/remote_requests_test.go
  go/utils/copyrightshdrs/main.go
Labels: correctness_approved

#8714 [no-release-notes] go/libraries/doltcore/remotestorage/internal/reliable: grpc_test.go: Improve perf of NestErrorStreams so that it works and does not take forever.
  go/libraries/doltcore/remotestorage/internal/reliable/grpc_test.go
Labels: correctness_approved

#8720 unhide `dolt ci` commands
  go/cmd/dolt/commands/ci/ci.go
  go/cmd/dolt/commands/ci/destroy.go
  go/cmd/dolt/commands/ci/export.go
  go/cmd/dolt/commands/ci/import.go
  go/cmd/dolt/commands/ci/init.go
  go/cmd/dolt/commands/ci/ls.go
  go/cmd/dolt/commands/ci/remove.go
Labels: correctness_approved

#8721 Updating journal to allow chunk records larger than 1MB
  go/libraries/doltcore/sqle/enginetest/dolt_queries.go
  go/store/nbs/journal_record.go
  go/store/nbs/journal_writer.go
  integration-tests/bats/json-large-value-insert.sql
  integration-tests/bats/json.bats
Labels: correctness_approved

#8722 Add "dolt_optimize_json" system variable.
  go/libraries/doltcore/sqle/system_variables.go
  go/store/prolly/tree/prolly_fields.go
  integration-tests/bats/json.bats
Labels: correctness_approved

#8723 If a JSON document contains strings that can't fit in a single chunk, use the naive Blob chunker instead of the smart JSON chunker.
  go/go.mod
  go/go.sum
  go/libraries/doltcore/sqle/enginetest/dolt_queries.go
  go/store/prolly/tree/indexed_json_diff.go
  go/store/prolly/tree/json_chunker.go
  go/store/prolly/tree/json_cursor.go
  go/store/prolly/tree/json_indexed_document.go
  go/store/prolly/tree/json_indexed_document_test.go
  go/store/prolly/tree/json_location.go
  go/store/prolly/tree/json_scanner.go
  go/store/prolly/tree/prolly_fields.go
  integration-tests/bats/json.bats
Labels: correctness_approved

#8725 More information about types in int conversions
  go/store/prolly/tree/prolly_fields.go
Labels: correctness_approved

#8719 Replace min/max helpers with built-in min/max
  go/libraries/doltcore/schema/typeinfo/common_test.go
  go/libraries/doltcore/sqle/index/dolt_map_iter.go
  go/libraries/doltcore/table/untyped/tabular/stringwidth.go
  go/libraries/utils/iohelp/read_test.go
  go/libraries/utils/mathutil/max.go
  go/libraries/utils/mathutil/max_test.go
  go/store/blobstore/gcs.go
  go/store/cmd/noms/noms_cat.go
  go/store/types/blob.go
  go/store/types/edit_distance.go
Labels: contribution

#8726 Replace min/max helpers with built-in min/max
  go/libraries/doltcore/schema/typeinfo/common_test.go
  go/libraries/doltcore/sqle/index/dolt_map_iter.go
  go/libraries/doltcore/table/untyped/tabular/stringwidth.go
  go/libraries/utils/iohelp/read_test.go
  go/libraries/utils/mathutil/max.go
  go/libraries/utils/mathutil/max_test.go
  go/store/blobstore/gcs.go
  go/store/cmd/noms/noms_cat.go
  go/store/types/blob.go
  go/store/types/edit_distance.go
Labels: correctness_approved

#8644 Generate config.yaml when running sql-server
  go/cmd/dolt/commands/sqlserver/command_line_config.go
  go/cmd/dolt/commands/sqlserver/server_test.go
  go/cmd/dolt/commands/sqlserver/sqlserver.go
  go/libraries/doltcore/servercfg/serverconfig.go
  go/libraries/doltcore/servercfg/testdata/minver_validation.txt
  go/libraries/doltcore/servercfg/yaml_config.go
  go/libraries/doltcore/servercfg/yaml_config_test.go
  integration-tests/bats/helper/query-server-common.bash
  integration-tests/bats/sql-server-config-file-generation.bats
Labels: contribution

#8731 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8730 Make show command more resilient when resolving references
  go/cmd/dolt/commands/show.go
  integration-tests/bats/show.bats
Labels: correctness_approved

#8742 Don't panic when attempting to update workspace table
  go/libraries/doltcore/sqle/dtables/workspace_table.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries_workspace.go
Labels: correctness_approved

#8740 /go/libraries/doltcore/sql/dsess: parallelize sql.NewDatabase work
  go/libraries/doltcore/sqle/dsess/autoincrement_tracker.go
  go/libraries/doltcore/sqle/dsess/globalstate.go
Labels: correctness_approved

#8743 [no-release-notes] Cleaning up a couple issues in yaml config missed during review
  go/libraries/doltcore/servercfg/testdata/minver_validation.txt
  go/libraries/doltcore/servercfg/yaml_config.go
  go/libraries/doltcore/servercfg/yaml_config_test.go
Labels: correctness_approved

#8745 Add --prune option to dolt_pull procedure
  go/cmd/dolt/cli/arg_parser_helpers.go
  go/cmd/dolt/commands/pull.go
  go/libraries/doltcore/sqle/dprocedures/dolt_pull.go
  integration-tests/bats/pull.bats
Labels: correctness_approved

#8746 Allow `dolt sql` to always log in as the `root` superuser
  go/cmd/dolt/commands/utils.go
  integration-tests/bats/sql-privs.bats
Labels: correctness_approved

#8750 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8748 [no-release-notes] go/store/nbs: Make CompressedChunk support ghost chunks and make and GhostBlockStore support GetManyCompressed.
  go/store/datas/pull/puller.go
  go/store/datas/pull/puller_test.go
  go/store/nbs/cmp_chunk_table_writer.go
  go/store/nbs/cmp_chunk_table_writer_test.go
  go/store/nbs/generational_chunk_store.go
  go/store/nbs/ghost_store.go
  go/store/nbs/ghost_store_test.go
  go/store/nbs/table_reader.go
  go/utils/copyrightshdrs/main.go
Labels: correctness_approved

#8751 [auto-bump] [no-release-notes] dependency by fulghum
  docker/docker-entrypoint.sh
  docker/serverREADME.md
  go/cmd/dolt/commands/engine/sqlengine.go
  go/cmd/dolt/commands/sqlserver/command_line_config.go
  go/cmd/dolt/commands/sqlserver/server.go
  go/cmd/dolt/commands/sqlserver/server_test.go
  go/cmd/dolt/commands/sqlserver/sqlserver.go
  go/cmd/dolt/commands/utils.go
  go/go.mod
  go/go.sum
  go/libraries/doltcore/dconfig/envvars.go
  go/libraries/doltcore/servercfg/serverconfig.go
  go/libraries/doltcore/servercfg/yaml_config.go
  go/libraries/doltcore/servercfg/yaml_config_test.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_replica_controller.go
  go/libraries/doltcore/sqle/enginetest/dolt_server_tests.go
  go/performance/replicationbench/replica_test.go
  go/performance/serverbench/bench_test.go
  integration-tests/bats/events.bats
  integration-tests/bats/sql-local-remote.bats
  integration-tests/bats/sql-privs.bats
  integration-tests/bats/sql-server.bats
Labels: gms-bump, correctness_approved

#8749 Allow importing parquet fields containing repeated elements.
  go/libraries/doltcore/table/typed/parquet/reader.go
  integration-tests/bats/helper/parquet/sequences.parquet
  integration-tests/bats/helper/parquet/sequences.sql
  integration-tests/bats/import-create-tables.bats
Labels: correctness_approved

#8756 [auto-bump] [no-release-notes] dependency by nicktobey
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8686 Proximity Map implementation with support for incremental edits.
  go/Godeps/LICENSES
  go/cmd/dolt/commands/indexcmds/cat.go
  go/gen/fb/serial/fileidentifiers.go
  go/gen/fb/serial/schema.go
  go/gen/fb/serial/vectorindexnode.go
  go/go.mod
  go/go.sum
  go/go.work.sum
  go/libraries/doltcore/doltdb/durable/index.go
  go/libraries/doltcore/doltdb/durable/proximity_index.go
  go/libraries/doltcore/doltdb/durable/table.go
  go/libraries/doltcore/schema/encoding/schema_marshaling.go
  go/libraries/doltcore/schema/encoding/serialization.go
  go/libraries/doltcore/schema/index.go
  go/libraries/doltcore/schema/index_coll.go
  go/libraries/doltcore/sqle/alterschema.go
  go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
  go/libraries/doltcore/sqle/index/dolt_index.go
  go/libraries/doltcore/sqle/index/index_reader.go
  go/libraries/doltcore/sqle/index/prolly_row_iter.go
  go/libraries/doltcore/sqle/indexed_dolt_table.go
  go/libraries/doltcore/sqle/sqlfmt/schema_fmt.go
  go/libraries/doltcore/sqle/sqlutil/schema.go
  go/libraries/doltcore/sqle/tables.go
  go/libraries/doltcore/sqle/temp_table.go
  go/libraries/doltcore/table/editor/creation/external_build_index.go
  go/libraries/doltcore/table/table_iterator.go
  go/libraries/doltcore/table/table_iterator_test.go
  go/serial/fileidentifiers.go
  go/serial/generate.sh
  go/serial/schema.fbs
  go/serial/vectorindexnode.fbs
  go/store/prolly/message/message.go
  go/store/prolly/message/vector_index.go
  go/store/prolly/proximity_map.go
  go/store/prolly/proximity_map_test.go
  go/store/prolly/proximity_mutable_map.go
  go/store/prolly/shim/shim.go
  go/store/prolly/tree/node_splitter.go
  go/store/prolly/tree/proximity_map.go
  go/store/prolly/vector_index_chunker.go
  go/store/types/serial_message.go
  integration-tests/bats/helper/local-remote.bash
  integration-tests/bats/vector-index.bats
Labels: correctness_approved

#8753 make autoincrement tracker load async
  go/libraries/doltcore/sqle/dsess/autoincrement_tracker.go
  go/libraries/doltcore/sqle/globalstate/auto_increment_tracker.go
  go/libraries/doltcore/sqle/writer/noms_write_session.go
  go/libraries/doltcore/sqle/writer/prolly_write_session.go
Labels: correctness_approved

#8747 go/libraries/doltcore/sqle/dprocedures: dolt_gc.go: Retry canceling running queries when waiting for safepoint establishment.
  go/libraries/doltcore/sqle/dprocedures/dolt_gc.go
Labels: correctness_approved

#8752 go/store/{nbs,types}: GC: Move the reference walk from types to nbs.
  go/store/chunks/chunk_store.go
  go/store/chunks/memory_store.go
  go/store/chunks/test_utils.go
  go/store/hash/hash.go
  go/store/nbs/generational_chunk_store.go
  go/store/nbs/nbs_metrics_wrapper.go
  go/store/nbs/store.go
  go/store/nbs/store_test.go
  go/store/types/parallel_ref_walker.go
  go/store/types/value_store.go
Labels: correctness_approved

#8759 [no-release-notes] go/store/nbs: archive_chunk_source.go: hasMany: Fix small bug in return value for `remaining`.
  go/store/nbs/archive_chunk_source.go
Labels: correctness_approved

#8766 [auto-bump] [no-release-notes] dependency by nicktobey
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8770 Speed up fetch when there are many tags which haven't changed
  go/libraries/doltcore/doltdb/doltdb.go
  go/libraries/doltcore/env/actions/remotes.go
  go/libraries/doltcore/env/actions/tag.go
Labels: correctness_approved

#8771 [auto-bump] [no-release-notes] dependency by fulghum
  go/go.mod
  go/go.sum
  integration-tests/bats/auto_increment_lock_modes.bats
Labels: gms-bump, correctness_approved

#8775 [no-release-notes] /{.github,go}: update protoc in protobufs
  .github/workflows/ci-check-repo.yaml
  go/gen/proto/dolt/services/eventsapi/v1alpha1/client_event.pb.go
  go/gen/proto/dolt/services/eventsapi/v1alpha1/client_event_grpc.pb.go
  go/gen/proto/dolt/services/eventsapi/v1alpha1/event_constants.pb.go
  go/gen/proto/dolt/services/remotesapi/v1alpha1/chunkstore.pb.go
  go/gen/proto/dolt/services/remotesapi/v1alpha1/chunkstore_grpc.pb.go
  go/gen/proto/dolt/services/remotesapi/v1alpha1/credentials.pb.go
  go/gen/proto/dolt/services/remotesapi/v1alpha1/credentials_grpc.pb.go
  go/gen/proto/dolt/services/replicationapi/v1alpha1/replication.pb.go
  go/gen/proto/dolt/services/replicationapi/v1alpha1/replication_grpc.pb.go
  go/libraries/doltcore/sqle/dtables/help_table.go
Labels: correctness_approved

#8778 [auto-bump] [no-release-notes] dependency by reltuk
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8781 implement and test `drop temporary table ...` and `show create table` statements
  go/go.mod
  go/go.sum
  go/libraries/doltcore/mvdata/engine_table_writer.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries.go
  go/libraries/doltcore/sqle/sqlfmt/schema_fmt.go
Labels: correctness_approved

#8782 [no-release-notes]: go/store/nbs: Improve cleanup if we encounter an error during GC.
  go/store/chunks/chunk_store.go
  go/store/chunks/memory_store.go
  go/store/nbs/cmp_chunk_table_writer.go
  go/store/nbs/gc_copier.go
  go/store/nbs/store.go
  go/store/nbs/store_test.go
  go/store/types/value_store.go
Labels: correctness_approved

#8787 better `nil` transaction checking for `commit`s
  go/libraries/doltcore/sqle/database_provider.go
  go/libraries/doltcore/sqle/dsess/session.go
  go/libraries/doltcore/sqle/testutil.go
Labels: correctness_approved

#8780 go/store/types: Move to a safepoint controller which will allow a caller better control over when to take actions while the GC is running.
  go/libraries/doltcore/doltdb/doltdb.go
  go/libraries/doltcore/sqle/dprocedures/dolt_gc.go
  go/libraries/doltcore/sqle/enginetest/dolt_queries.go
  go/store/datas/database.go
  go/store/datas/database_common.go
  go/store/types/value_store.go
Labels: correctness_approved

#8788 Bug fix: ref conflict can cause tags to be temporarily removed on a replica
  go/libraries/doltcore/sqle/read_replica_database.go
  go/libraries/doltcore/sqle/replication_test.go
  integration-tests/bats/replication.bats
Labels: correctness_approved

#8790 [auto-bump] [no-release-notes] dependency by jycor
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8793 Add the `dirty` column to the dolt_branches table
  go/libraries/doltcore/sqle/dtables/branches_table.go
  go/libraries/doltcore/sqle/sqlselect_test.go
  go/libraries/doltcore/sqle/testutil.go
  integration-tests/bats/sql-server.bats
  integration-tests/mysql-client-tests/node/workbenchTests/branches.js
Labels: correctness_approved

#8760 [no-release-notes] go/store/nbs: During a GC process, take dependencies on chunks that are read through the ChunkStore.
  go/store/nbs/archive_build.go
  go/store/nbs/archive_chunk_source.go
  go/store/nbs/archive_test.go
  go/store/nbs/aws_table_persister.go
  go/store/nbs/aws_table_persister_test.go
  go/store/nbs/bs_persister.go
  go/store/nbs/cmp_chunk_table_writer_test.go
  go/store/nbs/conjoiner_test.go
  go/store/nbs/empty_chunk_source.go
  go/store/nbs/file_table_persister.go
  go/store/nbs/file_table_persister_test.go
  go/store/nbs/frag/main.go
  go/store/nbs/generational_chunk_store.go
  go/store/nbs/ghost_store.go
  go/store/nbs/journal.go
  go/store/nbs/journal_chunk_source.go
  go/store/nbs/journal_test.go
  go/store/nbs/journal_writer_test.go
  go/store/nbs/mem_table.go
  go/store/nbs/mem_table_test.go
  go/store/nbs/no_conjoin_bs_persister.go
  go/store/nbs/root_tracker_test.go
  go/store/nbs/store.go
  go/store/nbs/store_test.go
  go/store/nbs/table.go
  go/store/nbs/table_persister.go
  go/store/nbs/table_reader.go
  go/store/nbs/table_set.go
  go/store/nbs/table_set_test.go
  go/store/nbs/table_test.go
Labels: correctness_approved

#8794 [no-release-notes] go: binlogreplication: Add Session{{Begin,End}Command,End} lifecycle callbacks to the replica controller execution context session.
  go/cmd/dolt/commands/engine/sqlengine.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_metadata_persistence.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_primary_test.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_replica_applier.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_replica_controller.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_replica_event_producer.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_replication_restart_test.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_replication_test.go
Labels: correctness_approved

#8795 [auto-bump] [no-release-notes] dependency by zachmu
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8796 [no-release-notes] go/store/nbs: generational_chunk_store.go: In GCMode_Full, also take dependencies on chunks read from OldGen.
  go/store/chunks/chunk_store.go
  go/store/chunks/memory_store.go
  go/store/chunks/test_utils.go
  go/store/nbs/generational_chunk_store.go
  go/store/nbs/nbs_metrics_wrapper.go
  go/store/nbs/store.go
  go/store/nbs/store_test.go
  go/store/types/value_store.go
  integration-tests/go-sql-server-driver/concurrent_gc_test.go
Labels: correctness_approved

#8774 /go/libraries/doltcore/env/actions: make iter resolved tags paginated sort in lexicographical order
  go/libraries/doltcore/env/actions/tag.go
  go/libraries/doltcore/env/actions/tag_test.go
Labels: correctness_approved

#8803 [auto-bump] [no-release-notes] dependency by Hydrocharged
  go/go.mod
  go/go.sum
Labels: gms-bump, correctness_approved

#8804 Include `deleteErr` message in returned error
  go/libraries/doltcore/sqle/database_provider.go
Labels: correctness_approved

#8801 go: store/types: Fix dolt_gc on databases that use vector indexes.
  go/store/types/serial_message.go
  integration-tests/bats/vector-index.bats
Labels: correctness_approved

#8797 [no-release-notes] go: sqle,remotesrv: Implement sql.Session lifecycle callbacks for sql.Contexts used in remotesrv RPCs.
  go/cmd/dolt/commands/engine/sqlengine.go
  go/cmd/dolt/commands/sqlserver/server.go
  go/libraries/doltcore/sqle/cluster/controller.go
  go/libraries/doltcore/sqle/cluster/jwks.go
  go/libraries/doltcore/sqle/remotesrv.go
Labels: correctness_approved

#8805 [no-release-notes] go: binlogreplication: tests: Parallelize the test suite, slightly improve process management.
  go/libraries/doltcore/sqle/binlogreplication/binlog_primary_test.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_replication_alltypes_test.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_replication_filters_test.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_replication_multidb_test.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_replication_reconnect_test.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_replication_restart_test.go
  go/libraries/doltcore/sqle/binlogreplication/binlog_replication_test.go
  go/libraries/doltcore/sqle/binlogreplication/cmd_attributes_unix_test.go
  go/libraries/doltcore/sqle/binlogreplication/cmd_attributes_windows_test.go
Labels: correctness_approved
